import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';let app:Awaited<ReturnType<typeof buildApp>>;let token='';let projectId=0;let jobId=0;let attachmentId=0;
async function request(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set('content-type','application/json');if(token)headers.set('authorization',`Bearer ${token}`);const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:Object.fromEntries(headers.entries()),payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return{status:response.statusCode,body};}
before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();const login=await app.inject({method:'POST',url:`${base}/auth/login`,headers:{'content-type':'application/json'},payload:JSON.stringify({email:'admin@kandyads.lk',password:'ChangeMe!123'})});assert.equal(login.statusCode,200);token=JSON.parse(login.body).data.token;const project=await prisma.project.findFirst({orderBy:{id:'asc'},select:{id:true}});assert.ok(project);projectId=project.id;const stamp=Date.now();const job=await prisma.job.create({data:{number:`TEST-JOB-ATT-${stamp}`,projectId,title:`Job attachment fixture ${stamp}`}});jobId=job.id;});
after(async()=>{if(attachmentId)await prisma.attachment.delete({where:{id:attachmentId}}).catch(()=>undefined);if(jobId)await prisma.job.delete({where:{id:jobId}}).catch(()=>undefined);await app.close();await prisma.$disconnect();});
test('job detail exposes attachments and generic attachment registration works',async()=>{const empty=await request(`${base}/jobs/${jobId}`);assert.equal(empty.status,200);assert.deepEqual(empty.body.data.attachments,[]);const created=await request(`${base}/attachments`,{method:'POST',body:JSON.stringify({entityType:'JOB',entityId:jobId,name:'Artwork reference',description:'Approved artwork link',url:'https://example.com/job-artwork.pdf'})});assert.equal(created.status,201);attachmentId=created.body.data.id;const detail=await request(`${base}/jobs/${jobId}`);assert.equal(detail.status,200);assert.equal(detail.body.data.attachments.length,1);assert.equal(detail.body.data.attachments[0].id,attachmentId);});
test('job attachment workflow rejects missing job and unauthenticated access',async()=>{const missing=await request(`${base}/attachments`,{method:'POST',body:JSON.stringify({entityType:'JOB',entityId:999999999,name:'Missing',url:'https://example.com/missing.pdf'})});assert.equal(missing.status,400);const saved=token;token='';const denied=await request(`${base}/jobs/${jobId}`);assert.equal(denied.status,401);token=saved;});
