import assert from 'node:assert/strict';
import { before, after, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';
let app:Awaited<ReturnType<typeof buildApp>>; let token=''; let leadId=0; let original:any;
async function request(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set('content-type','application/json');if(token)headers.set('authorization',`Bearer ${token}`);const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:Object.fromEntries(headers.entries()),payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return {status:response.statusCode,body};}

before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();const login=await app.inject({method:'POST',url:`${base}/auth/login`,headers:{'content-type':'application/json'},payload:JSON.stringify({email:'admin@kandyads.lk',password:'ChangeMe!123'})});assert.equal(login.statusCode,200);token=JSON.parse(login.body).data.token;const lead=await prisma.lead.findFirst({orderBy:{id:'desc'}});assert.ok(lead);leadId=lead.id;original={name:lead.name,company:lead.company,phone:lead.phone,email:lead.email,source:lead.source,requirement:lead.requirement,estimatedValue:lead.estimatedValue,status:lead.status,assignedToId:lead.assignedToId,clientId:lead.clientId,followUpAt:lead.followUpAt};});
after(async()=>{if(leadId){await prisma.lead.update({where:{id:leadId},data:original}).catch(()=>undefined);await prisma.auditLog.deleteMany({where:{entity:'Lead',entityId:String(leadId)}}).catch(()=>undefined);}await app.close();await prisma.$disconnect();});

test('lead detail returns related owner/client and activity',async()=>{const r=await request(`${base}/leads/${leadId}`);assert.equal(r.status,200);assert.equal(r.body.data.id,leadId);assert.ok(Array.isArray(r.body.activity));});
test('lead edit updates follow-up and writes audit',async()=>{const future=new Date(Date.now()+2*86400000).toISOString();const r=await request(`${base}/leads/${leadId}`,{method:'PATCH',body:JSON.stringify({company:`Automated Lead ${Date.now()}`,followUpAt:future})});assert.equal(r.status,200);assert.equal(r.body.data.id,leadId);assert.ok(r.body.data.followUpAt);const a=await prisma.auditLog.findFirst({where:{entity:'Lead',entityId:String(leadId),action:'UPDATE'}});assert.ok(a);});
test('lead list supports due and upcoming follow-up filters',async()=>{const overdue=new Date(Date.now()-86400000).toISOString();await request(`${base}/leads/${leadId}`,{method:'PATCH',body:JSON.stringify({status:'QUALIFIED',followUpAt:overdue})});const due=await request(`${base}/leads?followUp=due&pageSize=100`);assert.equal(due.status,200);assert.ok(due.body.data.some((x:any)=>x.id===leadId));const upcomingAt=new Date(Date.now()+86400000).toISOString();await request(`${base}/leads/${leadId}`,{method:'PATCH',body:JSON.stringify({followUpAt:upcomingAt})});const up=await request(`${base}/leads?followUp=upcoming&pageSize=100`);assert.equal(up.status,200);assert.ok(up.body.data.some((x:any)=>x.id===leadId));});
test('lead note requires text and creates audit activity',async()=>{const invalid=await request(`${base}/leads/${leadId}/notes`,{method:'POST',body:JSON.stringify({note:''})});assert.equal(invalid.status,400);const created=await request(`${base}/leads/${leadId}/notes`,{method:'POST',body:JSON.stringify({note:`Automated sales note ${Date.now()}`})});assert.equal(created.status,201);assert.equal(created.body.data.action,'NOTE_ADDED');const activity=await request(`${base}/leads/${leadId}/activity`);assert.equal(activity.status,200);assert.ok(activity.body.data.some((x:any)=>x.action==='NOTE_ADDED'));});
test('lead activity and update reject missing lead',async()=>{const missing=await request('/leads/999999999');assert.equal(missing.status,404);const note=await request('/leads/999999999/notes',{method:'POST',body:JSON.stringify({note:'x'})});assert.equal(note.status,404);const edit=await request('/leads/999999999',{method:'PATCH',body:JSON.stringify({name:'Missing Lead'})});assert.equal(edit.status,404);});
test('lead create validates related employee and client references',async()=>{const invalidEmployee=await request(`${base}/leads`,{method:'POST',body:JSON.stringify({name:'Bad Lead',assignedToId:999999999})});assert.equal(invalidEmployee.status,400);const invalidClient=await request(`${base}/leads`,{method:'POST',body:JSON.stringify({name:'Bad Lead',clientId:999999999})});assert.equal(invalidClient.status,400);});
test('unauthenticated lead detail is rejected',async()=>{const previous=token;token='';const r=await request(`${base}/leads/${leadId}`);token=previous;assert.equal(r.status,401);});
