import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';let app:Awaited<ReturnType<typeof buildApp>>;let clientId=0;let enquiryId=0;let quoteId=0;
async function request(path:string,options:RequestInit={}){const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:{'content-type':'application/json'},payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return{status:response.statusCode,body};}
before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();});
after(async()=>{if(quoteId)await prisma.quote.delete({where:{id:quoteId}}).catch(()=>undefined);if(enquiryId)await prisma.enquiry.delete({where:{id:enquiryId}}).catch(()=>undefined);if(clientId)await prisma.client.delete({where:{id:clientId}}).catch(()=>undefined);await app.close();await prisma.$disconnect();});

test('public quote estimator is accessible without auth and returns indicative pricing',async()=>{const response=await request(`${base}/public/quote-estimator`);assert.equal(response.status,200);assert.ok(response.body.data.services.length>=1);assert.ok(response.body.data.services[0].from<response.body.data.services[0].to);});
test('public quote estimator creates enquiry and draft quote atomically',async()=>{const stamp=Date.now();const response=await request(`${base}/public/quote-estimator`,{method:'POST',body:JSON.stringify({name:'Estimator Fixture',email:`estimator-${stamp}@example.com`,phone:'0777483502',company:`Estimator Fixture ${stamp}`,siteLocation:'Kandy',items:[{serviceSlug:'signage',quantity:2}]})});assert.equal(response.status,201);clientId=(await prisma.quote.findUnique({where:{id:response.body.data.quoteId},select:{clientId:true}}))!.clientId;enquiryId=response.body.data.enquiryId;quoteId=response.body.data.quoteId;const quote=await prisma.quote.findUnique({where:{id:quoteId},include:{items:true}});assert.equal(quote?.status,'DRAFT');assert.equal(quote?.enquiryId,enquiryId);assert.equal(quote?.items.length,1);assert.equal(response.body.data.estimate.from,30000);assert.equal(response.body.data.estimate.to,150000);});
test('public estimator validates services and required contact fields',async()=>{const missing=await request(`${base}/public/quote-estimator`,{method:'POST',body:JSON.stringify({name:'Fixture',email:'not-an-email',phone:'123',company:'Fixture',items:[]})});assert.equal(missing.status,400);const unsupported=await request(`${base}/public/quote-estimator`,{method:'POST',body:JSON.stringify({name:'Fixture',email:'fixture@example.com',phone:'0777483502',company:'Fixture',items:[{serviceSlug:'not-real',quantity:1}]})});assert.equal(unsupported.status,400);});
