import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';let app:Awaited<ReturnType<typeof buildApp>>;let clientId=0;let enquiryId=0;let quoteId=0;const contactLeadIds:number[]=[];
async function request(path:string,options:RequestInit={}){const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:{'content-type':'application/json',...(options.headers||{})},payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return{status:response.statusCode,body};}
before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();});
after(async()=>{for(const id of contactLeadIds){await prisma.auditLog.deleteMany({where:{entity:'Lead',entityId:String(id)}}).catch(()=>undefined);await prisma.lead.delete({where:{id}}).catch(()=>undefined);}if(quoteId)await prisma.quote.delete({where:{id:quoteId}}).catch(()=>undefined);if(enquiryId)await prisma.enquiry.delete({where:{id:enquiryId}}).catch(()=>undefined);if(clientId)await prisma.client.delete({where:{id:clientId}}).catch(()=>undefined);await app.close();await prisma.$disconnect();});

test('public quote estimator is accessible without auth and returns indicative pricing',async()=>{const response=await request(`${base}/public/quote-estimator`);assert.equal(response.status,200);assert.ok(response.body.data.services.length>=1);assert.ok(response.body.data.services[0].from<response.body.data.services[0].to);});
test('public quote estimator creates enquiry and draft quote atomically',async()=>{const stamp=Date.now();const response=await request(`${base}/public/quote-estimator`,{method:'POST',body:JSON.stringify({name:'Estimator Fixture',email:`estimator-${stamp}@example.com`,phone:'0777483502',company:`Estimator Fixture ${stamp}`,siteLocation:'Kandy',items:[{serviceSlug:'signage',quantity:2}]})});assert.equal(response.status,201);clientId=(await prisma.quote.findUnique({where:{id:response.body.data.quoteId},select:{clientId:true}}))!.clientId;enquiryId=response.body.data.enquiryId;quoteId=response.body.data.quoteId;const quote=await prisma.quote.findUnique({where:{id:quoteId},include:{items:true}});assert.equal(quote?.status,'DRAFT');assert.equal(quote?.enquiryId,enquiryId);assert.equal(quote?.items.length,1);assert.equal(response.body.data.estimate.from,30000);assert.equal(response.body.data.estimate.to,150000);});
test('public estimator validates services and required contact fields',async()=>{const missing=await request(`${base}/public/quote-estimator`,{method:'POST',body:JSON.stringify({name:'Fixture',email:'not-an-email',phone:'123',company:'Fixture',items:[]})});assert.equal(missing.status,400);const unsupported=await request(`${base}/public/quote-estimator`,{method:'POST',body:JSON.stringify({name:'Fixture',email:'fixture@example.com',phone:'0777483502',company:'Fixture',items:[{serviceSlug:'not-real',quantity:1}]})});assert.equal(unsupported.status,400);});
test('public contact rejects honeypot submissions and rate limits bursts',async()=>{const honey=await request(`${base}/public/contact`,{method:'POST',body:JSON.stringify({name:'Bot Fixture',phone:'0777483502',requirement:'spam',website:'filled'})});assert.equal(honey.status,400);for(let i=0;i<5;i++){const response=await request(`${base}/public/contact`,{method:'POST',body:JSON.stringify({name:`Rate Fixture ${i}`,phone:'0777483502',requirement:'rate limit test'})});assert.equal(response.status,201);contactLeadIds.push(response.body.data.leadId);}const limited=await request(`${base}/public/contact`,{method:'POST',body:JSON.stringify({name:'Rate Limited',phone:'0777483502',requirement:'rate limit test'})});assert.equal(limited.status,429);});
test('public contact captures lead and attribution',async()=>{const stamp=Date.now();const response=await request(`${base}/public/contact`,{method:'POST',body:JSON.stringify({name:'Website Fixture',company:`Website Fixture ${stamp}`,phone:'0777483502',email:`website-${stamp}@example.com`,service:'Signage & Signboards',requirement:'Public contact integration test',utmSource:'google',utmMedium:'cpc',utmCampaign:'brand',website:''})});assert.equal(response.status,201);const leadId=response.body.data.leadId;contactLeadIds.push(leadId);const lead=await prisma.lead.findUnique({where:{id:leadId}});assert.equal(lead?.source,'google');assert.match(lead?.requirement||'','Service: Signage & Signboards');const audit=await prisma.auditLog.findFirst({where:{entity:'Lead',entityId:String(leadId),action:'PUBLIC_CONTACT_SUBMITTED'}});assert.equal((audit?.afterJson as any)?.utmMedium,'cpc');assert.equal((audit?.afterJson as any)?.utmCampaign,'brand');});
