import assert from 'node:assert/strict';
import { before, after, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';
let app: Awaited<ReturnType<typeof buildApp>>; let token=''; let branchId=0; let sequenceId=0;
async function request(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set('content-type','application/json');if(token)headers.set('authorization',`Bearer ${token}`);const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:Object.fromEntries(headers.entries()),payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return {status:response.statusCode,body};}
before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS Branch (id INT NOT NULL AUTO_INCREMENT, code VARCHAR(50) NOT NULL, name VARCHAR(150) NOT NULL, address TEXT NULL, phone VARCHAR(50) NULL, email VARCHAR(191) NULL, active BOOLEAN NOT NULL DEFAULT true, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY(id), UNIQUE KEY Branch_code_key(code)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS NumberSequence (id INT NOT NULL AUTO_INCREMENT, entity VARCHAR(100) NOT NULL, prefix VARCHAR(30) NOT NULL, nextValue INT NOT NULL DEFAULT 1, padding INT NOT NULL DEFAULT 4, active BOOLEAN NOT NULL DEFAULT true, updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY(id), UNIQUE KEY NumberSequence_entity_key(entity)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);const login=await app.inject({method:'POST',url:`${base}/auth/login`,headers:{'content-type':'application/json'},payload:JSON.stringify({email:'admin@kandyads.lk',password:'ChangeMe!123'})});assert.equal(login.statusCode,200);token=JSON.parse(login.body).data.token;});
after(async()=>{if(sequenceId)await prisma.$executeRaw`DELETE FROM NumberSequence WHERE id=${sequenceId}`.catch(()=>undefined);if(branchId)await prisma.$executeRaw`DELETE FROM Branch WHERE id=${branchId}`.catch(()=>undefined);await app.close();await prisma.$disconnect();});
test('settings master data requires authentication',async()=>{assert.equal((await app.inject({method:'GET',url:`${base}/settings/branches`})).statusCode,401);});
test('branch create validates and supports update',async()=>{const invalid=await request(`${base}/settings/branches`,{method:'POST',body:JSON.stringify({code:'',name:'X'})});assert.equal(invalid.status,400);const created=await request(`${base}/settings/branches`,{method:'POST',body:JSON.stringify({code:`TEST-${Date.now()}`,name:'Test Branch',email:'branch@kandyads.lk'})});assert.equal(created.status,201);branchId=created.body.data.id;const updated=await request(`${base}/settings/branches/${branchId}`,{method:'PATCH',body:JSON.stringify({name:'Updated Test Branch',active:false})});assert.equal(updated.status,200);assert.equal(updated.body.data.name,'Updated Test Branch');assert.equal(Boolean(updated.body.data.active),false);assert.equal((await request(`${base}/settings/branches/999999999`,{method:'PATCH',body:JSON.stringify({name:'Nope'})})).status,404);});
test('number sequence generates the next formatted number and advances state',async()=>{const created=await request(`${base}/settings/number-sequences`,{method:'POST',body:JSON.stringify({entity:`TEST-${Date.now()}`,prefix:'TST-',nextValue:7,padding:4})});assert.equal(created.status,201);sequenceId=created.body.data.id;const first=await request(`${base}/settings/number-sequences/${sequenceId}/next`,{method:'POST',body:'{}'});assert.equal(first.status,200);assert.equal(first.body.data.number,'TST-0007');const second=await request(`${base}/settings/number-sequences/${sequenceId}/next`,{method:'POST',body:'{}'});assert.equal(second.status,200);assert.equal(second.body.data.number,'TST-0008');const row=(await request(`${base}/settings/number-sequences`)).body.data.find((item:any)=>item.id===sequenceId);assert.equal(row.nextValue,9);});
test('inactive number sequence cannot advance',async()=>{const updated=await request(`${base}/settings/number-sequences/${sequenceId}`,{method:'PATCH',body:JSON.stringify({active:false})});assert.equal(updated.status,200);const blocked=await request(`${base}/settings/number-sequences/${sequenceId}/next`,{method:'POST',body:'{}'});assert.equal(blocked.status,400);});
