import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';
let app:Awaited<ReturnType<typeof buildApp>>;
let token='';
let jobA=0;
let jobB=0;
let crossJobTask=0;
const taskIds:number[]=[];
const checklistIds:number[]=[];
const dependencyIds:number[]=[];

async function request(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set('content-type','application/json');if(token)headers.set('authorization',`Bearer ${token}`);const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:Object.fromEntries(headers.entries()),payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return {status:response.statusCode,body};}

before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();const login=await app.inject({method:'POST',url:`${base}/auth/login`,headers:{'content-type':'application/json'},payload:JSON.stringify({email:'admin@kandyads.lk',password:'ChangeMe!123'})});assert.equal(login.statusCode,200);token=JSON.parse(login.body).data.token;const jobs=await request(`${base}/jobs?pageSize=100`);jobA=jobs.body.data[0]?.id??0;jobB=jobs.body.data.find((j:any)=>j.id!==jobA)?.id??0;assert.ok(jobA&&jobB);const other=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobB,title:`Cross-job dependency target ${Date.now()}`})});assert.equal(other.status,201);crossJobTask=other.body.data.id;taskIds.push(crossJobTask);});

after(async()=>{for(const id of checklistIds)await prisma.taskChecklistItem.delete({where:{id}}).catch(()=>undefined);for(const id of dependencyIds)await prisma.taskDependency.delete({where:{id}}).catch(()=>undefined);for(const id of taskIds){await prisma.auditLog.deleteMany({where:{entity:'Task',entityId:String(id)}}).catch(()=>undefined);await prisma.task.delete({where:{id}}).catch(()=>undefined);}await app.close();await prisma.$disconnect();});

test('task hierarchy rejects missing or cross-job parents and creates a subtask',async()=>{const missing=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobA,title:'Bad subtask',parentTaskId:999999999})});assert.equal(missing.status,400);assert.match(missing.body.error.message,/parent task not found/i);const parent=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobA,title:`Parent ${Date.now()}`})});assert.equal(parent.status,201);taskIds.push(parent.body.data.id);const child=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobA,title:`Child ${Date.now()}`,parentTaskId:parent.body.data.id})});assert.equal(child.status,201);taskIds.push(child.body.data.id);const cross=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobB,title:`Cross ${Date.now()}`,parentTaskId:parent.body.data.id})});assert.equal(cross.status,400);assert.match(cross.body.error.message,/same job/i);const self=await request(`${base}/tasks/${parent.body.data.id}`,{method:'PATCH',body:JSON.stringify({parentTaskId:parent.body.data.id})});assert.equal(self.status,400);const detail=await request(`${base}/tasks/${parent.body.data.id}`);assert.equal(detail.status,200);assert.equal(detail.body.data.subtasks.length,1);assert.equal(detail.body.data.subtasks[0].id,child.body.data.id);});

test('task dependencies enforce same-job, no-self and no-cycle rules',async()=>{const first=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobA,title:`Dependency A ${Date.now()}`})});assert.equal(first.status,201);taskIds.push(first.body.data.id);const second=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobA,title:`Dependency B ${Date.now()}`})});assert.equal(second.status,201);taskIds.push(second.body.data.id);const self=await request(`${base}/tasks/${first.body.data.id}/dependencies`,{method:'POST',body:JSON.stringify({dependsOnTaskId:first.body.data.id})});assert.equal(self.status,400);const cross=await request(`${base}/tasks/${first.body.data.id}/dependencies`,{method:'POST',body:JSON.stringify({dependsOnTaskId:crossJobTask})});assert.equal(cross.status,400);assert.match(cross.body.error.message,/same job/i);const created=await request(`${base}/tasks/${second.body.data.id}/dependencies`,{method:'POST',body:JSON.stringify({dependsOnTaskId:first.body.data.id})});assert.equal(created.status,201);dependencyIds.push(created.body.data.id);const cycle=await request(`${base}/tasks/${first.body.data.id}/dependencies`,{method:'POST',body:JSON.stringify({dependsOnTaskId:second.body.data.id})});assert.equal(cycle.status,400);assert.match(cycle.body.error.message,/cycle/i);const duplicate=await request(`${base}/tasks/${second.body.data.id}/dependencies`,{method:'POST',body:JSON.stringify({dependsOnTaskId:first.body.data.id})});assert.equal(duplicate.status,400);});

test('required checklist blocks completion until completed, then records timestamp',async()=>{const task=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId:jobA,title:`Checklist task ${Date.now()}`})});assert.equal(task.status,201);taskIds.push(task.body.data.id);const invalid=await request(`${base}/tasks/${task.body.data.id}/checklist`,{method:'POST',body:JSON.stringify({title:''})});assert.equal(invalid.status,400);const item=await request(`${base}/tasks/${task.body.data.id}/checklist`,{method:'POST',body:JSON.stringify({title:'Final quality check',required:true})});assert.equal(item.status,201);checklistIds.push(item.body.data.id);const ready=await request(`${base}/tasks/${task.body.data.id}/status`,{method:'PATCH',body:JSON.stringify({status:'READY'})});assert.equal(ready.status,200);const progress=await request(`${base}/tasks/${task.body.data.id}/status`,{method:'PATCH',body:JSON.stringify({status:'IN_PROGRESS'})});assert.equal(progress.status,200);const blocked=await request(`${base}/tasks/${task.body.data.id}/status`,{method:'PATCH',body:JSON.stringify({status:'COMPLETED'})});assert.equal(blocked.status,400);assert.match(blocked.body.error.message,/checklist/i);const completed=await request(`${base}/tasks/${task.body.data.id}/checklist/${item.body.data.id}`,{method:'PATCH',body:JSON.stringify({completed:true})});assert.equal(completed.status,200);assert.ok(completed.body.data.completedAt);const final=await request(`${base}/tasks/${task.body.data.id}/status`,{method:'PATCH',body:JSON.stringify({status:'COMPLETED'})});assert.equal(final.status,200);assert.ok(final.body.data.completedAt);const detail=await request(`${base}/tasks/${task.body.data.id}`);assert.equal(detail.status,200);assert.equal(detail.body.data.checklistItems[0].completed,true);});
