import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';
let app:Awaited<ReturnType<typeof buildApp>>;let token='';let employeeId=0;let taskId=0;let timeId=0;let jobId=0;
async function request(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set('content-type','application/json');if(token)headers.set('authorization',`Bearer ${token}`);const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:Object.fromEntries(headers.entries()),payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return {status:response.statusCode,body};}
before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();const login=await app.inject({method:'POST',url:`${base}/auth/login`,headers:{'content-type':'application/json'},payload:JSON.stringify({email:'admin@kandyads.lk',password:'ChangeMe!123'})});assert.equal(login.statusCode,200);token=JSON.parse(login.body).data.token;});
after(async()=>{if(employeeId){await prisma.auditLog.deleteMany({where:{entity:'Employee',entityId:String(employeeId)}}).catch(()=>undefined);await prisma.employee.update({where:{id:employeeId},data:{status:'ACTIVE'}}).catch(()=>undefined);}if(taskId)await prisma.task.delete({where:{id:taskId}}).catch(()=>undefined);if(timeId){await prisma.auditLog.deleteMany({where:{entity:'TimeEntry',entityId:String(timeId)}}).catch(()=>undefined);await prisma.timeEntry.delete({where:{id:timeId}}).catch(()=>undefined);}await app.close();await prisma.$disconnect();});

test('employee master CRUD updates and audits employee data',async()=>{const employees=await request(`${base}/employees?pageSize=1`);assert.equal(employees.status,200);employeeId=employees.body.data[0]?.id??0;assert.ok(employeeId);const detail=await request(`${base}/employees/${employeeId}`);assert.equal(detail.status,200);const before=detail.body.data;const updated=await request(`${base}/employees/${employeeId}`,{method:'PATCH',body:JSON.stringify({department:'Automated QA',status:'INACTIVE'})});assert.equal(updated.status,200);assert.equal(updated.body.data.department,'Automated QA');assert.equal(updated.body.data.status,'INACTIVE');const invalid=await request(`${base}/employees/${employeeId}`,{method:'PATCH',body:JSON.stringify({email:'not-an-email'})});assert.equal(invalid.status,400);const audit=await request(`${base}/approvals/audit?entity=Employee&entityId=${employeeId}&action=UPDATE`);assert.equal(audit.status,200);assert.ok(audit.body.data.length>=1);await prisma.employee.update({where:{id:employeeId},data:{department:before.department,status:before.status}});});

test('task edit workflow saves fields and protects completed tasks',async()=>{const employees=await prisma.employee.findMany({take:1,orderBy:{id:'asc'}});const job=await prisma.job.findFirst({where:{project:{isNot:null}},orderBy:{id:'asc'}});assert.ok(employees[0]&&job);employeeId=employees[0].id;jobId=job.id;const created=await request(`${base}/tasks`,{method:'POST',body:JSON.stringify({jobId,title:`Automated task ${Date.now()}`,employeeId,priority:'Normal',estimatedHours:3,status:'READY'})});assert.equal(created.status,201);taskId=created.body.data.id;const edited=await request(`${base}/tasks/${taskId}`,{method:'PATCH',body:JSON.stringify({title:'Edited automated task',estimatedHours:4,description:'Updated description'})});assert.equal(edited.status,200);assert.equal(edited.body.data.title,'Edited automated task');assert.equal(Number(edited.body.data.estimatedHours),4);const completed=await request(`${base}/tasks/${taskId}/status`,{method:'PATCH',body:JSON.stringify({status:'IN_PROGRESS'})});assert.equal(completed.status,200);const done=await request(`${base}/tasks/${taskId}/status`,{method:'PATCH',body:JSON.stringify({status:'COMPLETED'})});assert.equal(done.status,200);assert.ok(done.body.data.completedAt);const reopen=await request(`${base}/tasks/${taskId}`,{method:'PATCH',body:JSON.stringify({title:'Should fail',status:'READY'})});assert.equal(reopen.status,400);assert.match(reopen.body.error.message,/cannot be reopened/i);});

test('time entry edit and approval locks approved records',async()=>{const employee=await prisma.employee.findFirst({orderBy:{id:'asc'}});const job=await prisma.job.findFirst({where:{project:{isNot:null}},orderBy:{id:'asc'}});assert.ok(employee&&job);const created=await request(`${base}/time`,{method:'POST',body:JSON.stringify({employeeId:employee.id,jobId:job.id,workDate:new Date().toISOString(),hours:2,billable:true,notes:'Automated time workflow'})});assert.equal(created.status,201);timeId=created.body.data.id;assert.equal(created.body.data.approved,false);const edited=await request(`${base}/time/${timeId}`,{method:'PATCH',body:JSON.stringify({hours:2.5,notes:'Edited automated time'})});assert.equal(edited.status,200);assert.equal(Number(edited.body.data.hours),2.5);const approved=await request(`${base}/approvals/time/${timeId}/approve`,{method:'POST',body:'{}'});assert.equal(approved.status,200);assert.equal(approved.body.data.approved,true);const locked=await request(`${base}/time/${timeId}`,{method:'PATCH',body:JSON.stringify({hours:3})});assert.equal(locked.status,400);assert.match(locked.body.error.message,/cannot be edited/i);const detail=await request(`${base}/time/${timeId}`);assert.equal(detail.status,200);assert.equal(detail.body.data.approved,true);});
