import assert from 'node:assert/strict';
import { before, after, test } from 'node:test';
import { buildApp } from '../src/app.js';
import { prisma } from '../src/lib/prisma.js';

const base='/api/v1';
let app:Awaited<ReturnType<typeof buildApp>>;let token='';let vendorId=0;
async function request(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set('content-type','application/json');if(token)headers.set('authorization',`Bearer ${token}`);const response=await app.inject({method:(options.method??'GET') as any,url:path,headers:Object.fromEntries(headers.entries()),payload:options.body});const body=response.body?JSON.parse(response.body):{};assert.ok(response.statusCode<500,`${response.statusCode}: ${response.body}`);return{status:response.statusCode,body};}
before(async()=>{if(process.env.NODE_ENV==='production')throw new Error('Tests must not run against production');if(!process.env.KANDYADS_TEST_MODE)throw new Error('Set KANDYADS_TEST_MODE=1 before running the integration suite.');app=buildApp();await app.ready();const login=await app.inject({method:'POST',url:`${base}/auth/login`,headers:{'content-type':'application/json'},payload:JSON.stringify({email:'admin@kandyads.lk',password:'ChangeMe!123'})});assert.equal(login.statusCode,200);token=JSON.parse(login.body).data.token;});
after(async()=>{if(vendorId){await prisma.$executeRaw`DELETE FROM VendorInvoice WHERE vendorId=${vendorId}`.catch(()=>undefined);await prisma.$executeRaw`DELETE FROM VendorDeliverable WHERE vendorId=${vendorId}`.catch(()=>undefined);await prisma.vendor.delete({where:{id:vendorId}}).catch(()=>undefined);}await prisma.$disconnect();await app.close();});

test('vendor deliverable validates linked outsource order ownership',async()=>{const vendor=await prisma.vendor.create({data:{code:`WVD-${Date.now()}`,companyName:`Vendor Deliverable ${Date.now()}`,active:true}});vendorId=vendor.id;const missing=await request(`${base}/vendors/${vendor.id}/deliverables`,{method:'POST',body:JSON.stringify({type:'DELIVERY',description:'Test delivery',outsourceOrderId:999999999})});assert.equal(missing.status,400);assert.match(missing.body.error.message,/Outsource order not found/);});

test('vendor deliverable and supplier invoice are persisted and returned in vendor detail',async()=>{const deliverable=await request(`${base}/vendors/${vendorId}/deliverables`,{method:'POST',body:JSON.stringify({type:'COMPLETION',reference:'DEL-001',description:'Completed fabricated signboard',deliveredAt:'2026-09-02T10:00:00.000Z',accepted:true,notes:'Accepted by production'})});assert.equal(deliverable.status,201);const invoice=await request(`${base}/vendors/${vendorId}/invoices`,{method:'POST',body:JSON.stringify({invoiceNumber:'SUP-001',invoiceDate:'2026-09-02',dueDate:'2026-09-30',amount:125000.5,status:'RECEIVED',notes:'Supplier invoice'})});assert.equal(invoice.status,201);const duplicate=await request(`${base}/vendors/${vendorId}/invoices`,{method:'POST',body:JSON.stringify({invoiceNumber:'SUP-001',invoiceDate:'2026-09-02',amount:100,status:'RECEIVED'})});assert.equal(duplicate.status,409);const detail=await request(`${base}/vendors/${vendorId}`);assert.equal(detail.status,200);assert.equal(detail.body.data.deliverables.length,1);assert.equal(detail.body.data.deliverables[0].accepted,true);assert.equal(detail.body.data.invoices.length,1);assert.equal(detail.body.data.invoices[0].invoiceNumber,'SUP-001');assert.equal(detail.body.data.invoices[0].amount,125000.5);});
