import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';

const createSchema=z.object({employeeId:z.coerce.number().int().positive(),projectId:z.coerce.number().int().positive().optional(),jobId:z.coerce.number().int().positive().optional(),taskId:z.coerce.number().int().positive().optional(),workDate:z.coerce.date(),startTime:z.coerce.date().optional(),endTime:z.coerce.date().optional(),hours:z.coerce.number().positive(),billable:z.coerce.boolean().default(false),notes:z.string().max(2000).optional()});
export async function timeTrackingRoutes(app:FastifyInstance){
  app.get('/api/v1/time',async request=>{const q=z.object({employeeId:z.coerce.number().int().positive().optional(),jobId:z.coerce.number().int().positive().optional(),from:z.coerce.date().optional(),to:z.coerce.date().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(50)}).parse(request.query);const where={...(q.employeeId?{employeeId:q.employeeId}:{}),...(q.jobId?{jobId:q.jobId}:{}),...(q.from||q.to?{workDate:{...(q.from?{gte:q.from}:{}),...(q.to?{lte:q.to}:{})}}:{})};const [items,total]=await Promise.all([prisma.timeEntry.findMany({where,include:{employee:true,project:true,job:true,task:true},orderBy:{workDate:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.timeEntry.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.post('/api/v1/time',async(request,reply)=>{const input=createSchema.parse(request.body);const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');if(input.jobId){const job=await prisma.job.findUnique({where:{id:input.jobId}});if(!job)return reply.badRequest('Job not found');}const item=await prisma.timeEntry.create({data:input,include:{employee:true,project:true,job:true,task:true}});return reply.code(201).send({data:item});});
}
