import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';

const createSchema=z.object({employeeId:z.coerce.number().int().positive(),projectId:z.coerce.number().int().positive().nullish(),jobId:z.coerce.number().int().positive().nullish(),taskId:z.coerce.number().int().positive().nullish(),workDate:z.coerce.date(),startTime:z.coerce.date().optional(),endTime:z.coerce.date().optional(),hours:z.coerce.number().positive(),billable:z.coerce.boolean().default(false),notes:z.string().max(2000).optional()});
const updateSchema=createSchema.partial();
function actorId(request:FastifyRequest){const id=Number((request.user as {sub?:string}).sub);return Number.isInteger(id)&&id>0?id:null;}
async function audit(request:FastifyRequest,action:string,id:number,before:unknown,after:unknown){await prisma.auditLog.create({data:{userId:actorId(request),action,entity:'TimeEntry',entityId:String(id),beforeJson:before as any,afterJson:after as any}});}
async function approved(id:number){return Boolean(await prisma.auditLog.findFirst({where:{entity:'TimeEntry',entityId:String(id),action:'APPROVE'}}));}
async function validateRelations(input:z.infer<typeof createSchema>){const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return 'Employee not found';if(input.jobId){const job=await prisma.job.findUnique({where:{id:input.jobId}});if(!job)return 'Job not found';}if(input.taskId){const task=await prisma.task.findUnique({where:{id:input.taskId}});if(!task)return 'Task not found';}if(input.projectId){const project=await prisma.project.findUnique({where:{id:input.projectId}});if(!project)return 'Project not found';}return null;}
export async function timeTrackingRoutes(app:FastifyInstance){
  app.get('/api/v1/time',async request=>{const q=z.object({employeeId:z.coerce.number().int().positive().optional(),jobId:z.coerce.number().int().positive().optional(),from:z.coerce.date().optional(),to:z.coerce.date().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(50)}).parse(request.query);const where={...(q.employeeId?{employeeId:q.employeeId}:{}),...(q.jobId?{jobId:q.jobId}:{}),...(q.from||q.to?{workDate:{...(q.from?{gte:q.from}:{}),...(q.to?{lte:q.to}:{})}}:{})};const [items,total]=await Promise.all([prisma.timeEntry.findMany({where,include:{employee:true,project:true,job:true,task:true},orderBy:{workDate:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.timeEntry.count({where})]);const approvedIds=await prisma.auditLog.findMany({where:{entity:'TimeEntry',action:'APPROVE',entityId:{in:items.map(x=>String(x.id))}},select:{entityId:true}});const approvedSet=new Set(approvedIds.map(x=>x.entityId));return {data:items.map(x=>({...x,approved:approvedSet.has(String(x.id))})),meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.post('/api/v1/time',async(request,reply)=>{const input=createSchema.parse(request.body);const relationError=await validateRelations(input);if(relationError)return reply.badRequest(relationError);const item=await prisma.timeEntry.create({data:input,include:{employee:true,project:true,job:true,task:true}});await audit(request,'CREATE',item.id,null,item);return reply.code(201).send({data:{...item,approved:false}});});
  app.get('/api/v1/time/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const item=await prisma.timeEntry.findUnique({where:{id},include:{employee:true,project:true,job:true,task:true}});if(!item)return reply.notFound('Time entry not found');return {data:{...item,approved:await approved(id)}};});
  app.patch('/api/v1/time/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=updateSchema.parse(request.body);const existing=await prisma.timeEntry.findUnique({where:{id}});if(!existing)return reply.notFound('Time entry not found');if(await approved(id))return reply.badRequest('Approved time entries cannot be edited');const merged={...existing,...input};const relationError=await validateRelations(createSchema.parse(merged));if(relationError)return reply.badRequest(relationError);const item=await prisma.timeEntry.update({where:{id},data:input,include:{employee:true,project:true,job:true,task:true}});await audit(request,'UPDATE',id,existing,item);return {data:{...item,approved:false}};});
}
