import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';

const querySchema=z.object({from:z.coerce.date().optional(),to:z.coerce.date().optional(),employeeId:z.coerce.number().int().positive().optional()}).refine(v=>!v.from||!v.to||v.from<=v.to,{message:'from must be on or before to',path:['from']});

export async function hoursReportRoutes(app:FastifyInstance){
  app.get('/api/v1/reports/planned-vs-actual-hours',async(request)=>{const q=querySchema.parse(request.query);if(q.employeeId){const employee=await prisma.employee.findUnique({where:{id:q.employeeId},select:{id:true}});if(!employee)return app.httpErrors.notFound('Employee not found');}const where={employeeId:q.employeeId??undefined,job:{project:{is:{}}},...(q.from||q.to?{AND:[...(q.from?[{OR:[{dueDate:{gte:q.from}},{dueDate:null}]}]:[]),...(q.to?[{OR:[{startDate:{lte:q.to}},{startDate:null}]}]:[])]}: {})};const tasks=await prisma.task.findMany({where,orderBy:[{employeeId:'asc'},{dueDate:'asc'},{id:'asc'}],select:{id:true,title:true,status:true,employeeId:true,estimatedHours:true,actualHours:true,startDate:true,dueDate:true,jobId:true,job:{select:{number:true,title:true}},employee:{select:{id:true,code:true,name:true}}}});const taskIds=tasks.map(task=>task.id);const entries=taskIds.length?await prisma.timeEntry.findMany({where:{taskId:{in:taskIds}},select:{taskId:true,hours:true}}):[];const actualByTask=new Map<number,number>();for(const entry of entries)actualByTask.set(entry.taskId!, (actualByTask.get(entry.taskId!)||0)+Number(entry.hours||0));const rows=tasks.map(task=>{const planned=Number(task.estimatedHours||0);const logged=actualByTask.get(task.id)||0;const actual=logged||Number(task.actualHours||0);return {taskId:task.id,title:task.title,status:task.status,employeeId:task.employeeId,employee:task.employee,jobId:task.jobId,jobNumber:task.job.number,jobTitle:task.job.title,startDate:task.startDate,dueDate:task.dueDate,plannedHours:planned,actualHours:actual,varianceHours:actual-planned};});const summary=rows.reduce((acc,row)=>({plannedHours:acc.plannedHours+row.plannedHours,actualHours:acc.actualHours+row.actualHours,varianceHours:acc.varianceHours+row.varianceHours}),{plannedHours:0,actualHours:0,varianceHours:0});return {data:{summary,rows},meta:{from:q.from??null,to:q.to??null,totalTasks:rows.length,totalEmployees:new Set(rows.map(row=>row.employeeId).filter(Boolean)).size}};});
}
