import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { canTransition, projectTransitions } from '../workflow/workflow.rules.js';

const createSchema=z.object({number:z.string().min(2).max(50),name:z.string().min(2).max(200),clientId:z.coerce.number().int().positive(),quoteId:z.coerce.number().int().positive().optional(),ownerId:z.coerce.number().int().positive().optional(),startDate:z.coerce.date().optional(),dueDate:z.coerce.date().optional(),value:z.coerce.number().nonnegative().default(0)});
const updateSchema=createSchema.partial();
const statusSchema=z.object({status:z.enum(['PLANNED','ACTIVE','ON_HOLD','COMPLETED','CANCELLED'])});

function actorId(request:FastifyRequest){const id=Number((request.user as {sub?:string}).sub);return Number.isInteger(id)&&id>0?id:null;}
async function audit(request:FastifyRequest,action:string,projectId:number,before:unknown,after:unknown){await prisma.auditLog.create({data:{userId:actorId(request),action,entity:'Project',entityId:String(projectId),beforeJson:before as any,afterJson:after as any}});}
function serializeAudit(entry:any){return {...entry,id:typeof entry.id==='bigint'?entry.id.toString():entry.id};}

export async function projectsRoutes(app:FastifyInstance){
  app.get('/api/v1/projects',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const where={...(q.status?{status:q.status as any}:{}),...(q.search?{OR:[{number:{contains:q.search}},{name:{contains:q.search}}]}:{})};const [items,total]=await Promise.all([prisma.project.findMany({where,include:{client:true,quote:true,owner:true,jobs:true},orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.project.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.get('/api/v1/projects/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const item=await prisma.project.findUnique({where:{id},include:{client:true,quote:true,owner:true,jobs:{orderBy:{createdAt:'asc'},include:{service:true,tasks:true}},expenses:{include:{category:true,job:true},orderBy:{expenseDate:'desc'}},installations:{orderBy:{scheduledAt:'asc'}},invoices:{include:{payments:true},orderBy:{invoiceDate:'desc'}},purchaseRequests:{orderBy:{createdAt:'desc'}},purchaseOrders:{include:{vendor:true,items:true,goodsReceipts:true},orderBy:{orderDate:'desc'}},timeEntries:{include:{employee:true,job:true,task:true},orderBy:{workDate:'desc'}},stockMovements:{include:{material:true,warehouse:true,job:true},orderBy:{createdAt:'desc'}}}});if(!item)return reply.notFound('Project not found');return {data:item};});
  app.get('/api/v1/projects/:id/activity',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const project=await prisma.project.findUnique({where:{id},select:{id:true}});if(!project)return reply.notFound('Project not found');const data=await prisma.auditLog.findMany({where:{entity:'Project',entityId:String(id)},include:{user:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:'desc'},take:200});return {data:data.map(serializeAudit)};});
  app.post('/api/v1/projects',async(request,reply)=>{const input=createSchema.parse(request.body);const client=await prisma.client.findUnique({where:{id:input.clientId}});if(!client)return reply.badRequest('Client not found');if(input.quoteId){const quote=await prisma.quote.findUnique({where:{id:input.quoteId}});if(!quote)return reply.badRequest('Quote not found');}if(input.ownerId){const owner=await prisma.employee.findUnique({where:{id:input.ownerId}});if(!owner)return reply.badRequest('Owner not found');}const item=await prisma.project.create({data:input,include:{client:true,quote:true,owner:true}});await audit(request,'CREATE',item.id,null,{number:item.number,name:item.name,status:item.status,clientId:item.clientId,quoteId:item.quoteId,ownerId:item.ownerId,startDate:item.startDate,dueDate:item.dueDate,value:Number(item.value)});return reply.code(201).send({data:item});});
  app.patch('/api/v1/projects/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=updateSchema.parse(request.body);const existing=await prisma.project.findUnique({where:{id}});if(!existing)return reply.notFound('Project not found');if(existing.status==='COMPLETED'||existing.status==='CANCELLED')return reply.badRequest(`Project cannot be edited from ${existing.status}`);if(input.clientId){const client=await prisma.client.findUnique({where:{id:input.clientId}});if(!client)return reply.badRequest('Client not found');}if(input.quoteId){const quote=await prisma.quote.findUnique({where:{id:input.quoteId}});if(!quote)return reply.badRequest('Quote not found');}if(input.ownerId){const owner=await prisma.employee.findUnique({where:{id:input.ownerId}});if(!owner)return reply.badRequest('Owner not found');}const item=await prisma.project.update({where:{id},data:input,include:{client:true,quote:true,owner:true}});await audit(request,'UPDATE',id,{number:existing.number,name:existing.name,status:existing.status,clientId:existing.clientId,quoteId:existing.quoteId,ownerId:existing.ownerId,startDate:existing.startDate,dueDate:existing.dueDate,value:Number(existing.value)},{number:item.number,name:item.name,status:item.status,clientId:item.clientId,quoteId:item.quoteId,ownerId:item.ownerId,startDate:item.startDate,dueDate:item.dueDate,value:Number(item.value)});return {data:item};});
  app.patch('/api/v1/projects/:id/status',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=statusSchema.parse(request.body);const existing=await prisma.project.findUnique({where:{id},include:{jobs:{select:{status:true}}}});if(!existing)return reply.notFound('Project not found');if(!canTransition(projectTransitions,existing.status,input.status))return reply.badRequest(`Invalid project transition: ${existing.status} -> ${input.status}`);if(input.status==='COMPLETED'){const openJobs=existing.jobs.filter(job=>!['COMPLETED','CANCELLED'].includes(job.status));if(openJobs.length>0)return reply.badRequest('Project cannot be completed while jobs are still open');}const item=await prisma.project.update({where:{id},data:{status:input.status},include:{client:true,owner:true,jobs:true}});await audit(request,'STATUS_CHANGE',id,{status:existing.status},{status:item.status});return {data:item};});
}
