import React from 'react';
import { Plus, RefreshCw, Search, ArrowRight } from 'lucide-react';
import { api } from '../../../api';
import ResourceTable from '../../shared/components/ResourceTable';
import Modal from '../../../components/common/Modal';
import QuoteForm from '../components/QuoteForm';

export default function QuotesPage(){
 const [search,setSearch]=React.useState('');const [state,setState]=React.useState({loading:true,error:'',items:[],total:0});const [open,setOpen]=React.useState(false);const [saving,setSaving]=React.useState(false);const [convertingId,setConvertingId]=React.useState(0);const [notice,setNotice]=React.useState('');
 const load=React.useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await api.listQuotes({search:search||undefined});setState({loading:false,error:'',items:r.data||[],total:r.meta?.total||0})}catch(e){setState({loading:false,error:e.message||'Unable to load quotes',items:[],total:0})}},[search]);
 React.useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 async function create(input){setSaving(true);try{await api.createQuote(input);setOpen(false);await load()}finally{setSaving(false)}}
 async function convert(row){setConvertingId(row.id);setNotice('');try{const result=await api.convertQuoteToProject(row.id);setNotice(`${row.number} converted to ${result.data.number}.`);await load()}catch(e){setNotice(e.message||'Unable to convert quote.')}finally{setConvertingId(0)}}
 return <div><div className="page-head"><div><p className="eyebrow">SALES & CRM</p><h1>Quotes</h1><p>Prepare estimates, compare expected delivery costs and track client decisions.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/> New Quote</button></div>{notice&&<div className="panel" style={{marginBottom:16}}>{notice}</div>}<section className="panel table-panel"><div className="table-toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotes…"/></label><button className="icon-button" onClick={load} aria-label="Refresh quotes"><RefreshCw size={16}/></button><span className="table-count">{state.total} quotes</span></div><ResourceTable loading={state.loading} error={state.error} rows={state.items} columns={[{key:'number',label:'Quote'},{key:'client',label:'Client',render:r=><strong>{r.client?.companyName||'—'}</strong>},{key:'status',label:'Status',render:r=><span className="table-status">{r.status}</span>},{key:'total',label:'Total',render:r=>`LKR ${Number(r.total||0).toLocaleString()}`},{key:'expectedMargin',label:'Expected Margin',render:r=>`LKR ${Number(r.expectedMargin||0).toLocaleString()}`},{key:'validUntil',label:'Valid Until',render:r=>r.validUntil?new Date(r.validUntil).toLocaleDateString():'—'},{key:'actions',label:'Actions',render:r=>r.status==='ACCEPTED'&&!r.project?<button className="secondary" onClick={()=>convert(r)} disabled={convertingId===r.id}>{convertingId===r.id?'Converting…':<>Convert <ArrowRight size={14}/></>}</button>:r.project?<span className="table-status">{r.project.number}</span>:'—'}]} /></section><Modal open={open} onClose={()=>setOpen(false)} title="New quote" description="Build the client estimate and record expected delivery costs for margin planning." width="980px"><QuoteForm onSubmit={create} onCancel={()=>setOpen(false)} submitting={saving}/></Modal></div>;
}
