import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';

const pricing=[
  {slug:'signage',name:'Signage & Signboards',unit:'project',from:15000,to:75000},
  {slug:'vehicle-branding',name:'Vehicle Branding',unit:'vehicle',from:25000,to:120000},
  {slug:'outdoor-advertising',name:'Outdoor Advertising',unit:'project',from:30000,to:150000},
  {slug:'printing',name:'Digital Printing & Displays',unit:'sq ft',from:180,to:950},
  {slug:'retail-branding',name:'Retail & Commercial Branding',unit:'project',from:25000,to:180000},
  {slug:'events',name:'Exhibitions & Promotional',unit:'project',from:20000,to:100000},
] as const;
const itemSchema=z.object({serviceSlug:z.string().min(2).max(180),quantity:z.coerce.number().positive().max(100000)});
const submitSchema=z.object({name:z.string().trim().min(2).max(160),email:z.string().email().max(160),phone:z.string().trim().min(7).max(40),company:z.string().trim().min(2).max(200),siteLocation:z.string().max(500).optional(),targetDate:z.coerce.date().optional(),items:z.array(itemSchema).min(1).max(10)});
const contactSchema=z.object({name:z.string().trim().min(2).max(160),company:z.string().trim().max(200).optional(),phone:z.string().trim().min(7).max(40),email:z.string().email().max(160).optional(),service:z.string().trim().max(150).optional(),requirement:z.string().trim().min(5).max(5000),utmSource:z.string().trim().max(80).optional(),utmMedium:z.string().trim().max(80).optional(),utmCampaign:z.string().trim().max(120).optional(),website:z.string().max(0).optional()});
const contactHits=new Map<string,number[]>();
function allowContact(ip:string){const now=Date.now(),windowMs=15*60*1000,limit=5;const recent=(contactHits.get(ip)||[]).filter(time=>now-time<windowMs);if(recent.length>=limit){contactHits.set(ip,recent);return false;}recent.push(now);contactHits.set(ip,recent);if(contactHits.size>500){for(const [key,times] of contactHits)if(times.every(time=>now-time>=windowMs))contactHits.delete(key);}return true;}
function estimateFor(slug:string,quantity:number){const p=pricing.find(item=>item.slug===slug);if(!p)throw new Error(`Unsupported service: ${slug}`);return {slug,name:p.name,unit:p.unit,quantity,from:Math.round(p.from*quantity),to:Math.round(p.to*quantity),rateFrom:p.from,rateTo:p.to};}

export async function publicQuoteEstimatorRoutes(app:FastifyInstance){
  app.get('/api/v1/public/quote-estimator',async()=>({data:{services:pricing.map(item=>({...item})),notice:'Indicative budget ranges only. Final pricing is confirmed after artwork, site and production review.'}}));
  app.post('/api/v1/public/quote-estimator',async(request,reply)=>{const input=submitSchema.parse(request.body);let estimates;try{estimates=input.items.map(item=>estimateFor(item.serviceSlug,item.quantity));}catch(error){return reply.badRequest((error as Error).message);}const totalFrom=estimates.reduce((sum,item)=>sum+item.from,0);const totalTo=estimates.reduce((sum,item)=>sum+item.to,0);const serviceSlugs=[...new Set(estimates.map(item=>item.slug))];const services=await prisma.service.findMany({where:{slug:{in:serviceSlugs},active:true},select:{id:true,slug:true,name:true}});const serviceMap=new Map(services.map(service=>[service.slug,service]));const missing=serviceSlugs.find(slug=>!serviceMap.has(slug));if(missing)return reply.badRequest(`Service '${missing}' is not available`);const stamp=Date.now();const result=await prisma.$transaction(async tx=>{const existing=input.email?await tx.client.findFirst({where:{email:input.email},orderBy:{id:'asc'}}):null;const client=existing??await tx.client.create({data:{code:`WEB-${stamp}`,companyName:input.company,contactName:input.name,email:input.email,phone:input.phone,notes:'Created through public quote estimator.'}});const enquiry=await tx.enquiry.create({data:{number:`WEB-E-${stamp}`,clientId:client.id,source:'WEBSITE_QUOTE_ESTIMATOR',requirement:estimates.map(item=>`${item.name}: ${item.quantity} ${item.unit}`).join('; '),siteLocation:input.siteLocation,targetDate:input.targetDate}});const items=input.items.map(inputItem=>{const estimate=estimates.find(item=>item.slug===inputItem.serviceSlug)!;const service=serviceMap.get(inputItem.serviceSlug)!;const rate=(estimate.rateFrom+estimate.rateTo)/2;return {serviceId:service.id,description:`Website estimate — ${service.name}`,quantity:inputItem.quantity,unit:estimate.unit,rate,discount:0,tax:0,total:rate*inputItem.quantity};});const subtotal=items.reduce((sum,item)=>sum+item.total,0);const quote=await tx.quote.create({data:{number:`WEB-Q-${stamp}`,clientId:client.id,enquiryId:enquiry.id,subtotal,discount:0,tax:0,total:subtotal,expectedMaterial:0,expectedLabour:0,expectedOutsource:0,expectedExpense:0,expectedMargin:subtotal,status:'DRAFT',items:{create:items}}});await tx.auditLog.create({data:{userId:null,action:'PUBLIC_QUOTE_REQUESTED',entity:'Enquiry',entityId:String(enquiry.id),afterJson:{quoteId:quote.id,clientId:client.id,estimateFrom:totalFrom,estimateTo:totalTo}}});return {client,enquiry,quote};});return reply.code(201).send({data:{enquiryId:result.enquiry.id,quoteId:result.quote.id,quoteNumber:result.quote.number,estimate:{from:totalFrom,to:totalTo},notice:'Your estimate is indicative. Our team will review the requirement and confirm the final quotation.'}});});
  app.post('/api/v1/public/contact',async(request,reply)=>{const input=contactSchema.parse(request.body);if(input.website)return reply.badRequest('Invalid submission');if(!allowContact(request.ip))return reply.status(429).send({error:{code:'RATE_LIMITED',message:'Too many enquiries. Please try again later.'}});const source=input.utmSource||'WEBSITE_CONTACT';const lead=await prisma.lead.create({data:{name:input.name,company:input.company||null,phone:input.phone,email:input.email||null,source,requirement:[input.service?`Service: ${input.service}`:'',input.requirement].filter(Boolean).join('\n')}});await prisma.auditLog.create({data:{userId:null,action:'PUBLIC_CONTACT_SUBMITTED',entity:'Lead',entityId:String(lead.id),afterJson:{utmSource:input.utmSource||null,utmMedium:input.utmMedium||null,utmCampaign:input.utmCampaign||null,service:input.service||null,ip:request.ip}}});const recipients=await prisma.user.findMany({where:{status:'ACTIVE',role:{permissions:{some:{permission:{key:'dashboard.view'}}}}},select:{id:true}});const key=`PUBLIC_CONTACT:${lead.id}`;for(const recipient of recipients){await prisma.$executeRaw`INSERT IGNORE INTO Notification (userId,type,title,message,entityType,entityId,dedupeKey) VALUES (${recipient.id},'LEAD_NEW','New website enquiry',${`${input.name}${input.company?` · ${input.company}`:''} submitted a website enquiry.`},'LEAD',${lead.id},${`${key}:${recipient.id}`})`;}return reply.code(201).send({data:{leadId:lead.id,message:'Thanks. Your enquiry has been received and our team will contact you shortly.'}});});
}
