import React from 'react';
import { ArrowLeft, FileText, Paperclip, Plus, ReceiptText, RefreshCw } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../../../api';
import Modal from '../../../components/common/Modal';

const dateTime=v=>v?new Date(v).toLocaleString():'—';
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});

export default function VendorDetailPage(){
  const {id}=useParams();
  const [state,setState]=React.useState({loading:true,error:'',vendor:null});
  const [documentOpen,setDocumentOpen]=React.useState(false),[deliverableOpen,setDeliverableOpen]=React.useState(false),[invoiceOpen,setInvoiceOpen]=React.useState(false),[saving,setSaving]=React.useState(false);
  const [documentForm,setDocumentForm]=React.useState({name:'',description:'',url:''});
  const [deliverableForm,setDeliverableForm]=React.useState({type:'COMPLETION',reference:'',description:'',deliveredAt:'',accepted:false,notes:'',outsourceOrderId:''});
  const [invoiceForm,setInvoiceForm]=React.useState({invoiceNumber:'',invoiceDate:'',dueDate:'',amount:'',status:'RECEIVED',notes:'',outsourceOrderId:''});
  const load=React.useCallback(async()=>{
    setState(s=>({...s,loading:true,error:''}));
    try{const result=await api.getVendor(id);setState({loading:false,error:'',vendor:result.data})}
    catch(e){setState({loading:false,error:e.message||'Unable to load vendor',vendor:null})}
  },[id]);
  React.useEffect(()=>{load()},[load]);
  async function addDocument(e){e.preventDefault();setSaving(true);try{await api.createAttachment({entityType:'VENDOR',entityId:Number(id),name:documentForm.name.trim(),description:documentForm.description||undefined,url:documentForm.url.trim()});setDocumentForm({name:'',description:'',url:''});setDocumentOpen(false);await load()}catch(err){setState(s=>({...s,error:err.message||'Unable to add vendor document'}))}finally{setSaving(false)}}
  async function addDeliverable(e){e.preventDefault();setSaving(true);try{await api.createVendorDeliverable(id,{type:deliverableForm.type,reference:deliverableForm.reference||undefined,description:deliverableForm.description,deliveredAt:deliverableForm.deliveredAt||undefined,accepted:Boolean(deliverableForm.accepted),notes:deliverableForm.notes||undefined,outsourceOrderId:deliverableForm.outsourceOrderId?Number(deliverableForm.outsourceOrderId):undefined});setDeliverableForm({type:'COMPLETION',reference:'',description:'',deliveredAt:'',accepted:false,notes:'',outsourceOrderId:''});setDeliverableOpen(false);await load()}catch(err){setState(s=>({...s,error:err.message||'Unable to add deliverable'}))}finally{setSaving(false)}}
  async function addInvoice(e){e.preventDefault();setSaving(true);try{await api.createVendorInvoice(id,{invoiceNumber:invoiceForm.invoiceNumber.trim(),invoiceDate:invoiceForm.invoiceDate,dueDate:invoiceForm.dueDate||undefined,amount:Number(invoiceForm.amount),status:invoiceForm.status,notes:invoiceForm.notes||undefined,outsourceOrderId:invoiceForm.outsourceOrderId?Number(invoiceForm.outsourceOrderId):undefined});setInvoiceForm({invoiceNumber:'',invoiceDate:'',dueDate:'',amount:'',status:'RECEIVED',notes:'',outsourceOrderId:''});setInvoiceOpen(false);await load()}catch(err){setState(s=>({...s,error:err.message||'Unable to add supplier invoice'}))}finally{setSaving(false)}}
  if(state.loading)return <div className="detail-state">Loading vendor…</div>;
  if(state.error&&!state.vendor)return <div className="detail-state error-state">{state.error}</div>;
  const vendor=state.vendor;
  return <div>
    <Link className="back-link" to="/vendors"><ArrowLeft size={15}/> Back to Vendors</Link>
    <div className="page-head"><div><p className="eyebrow">VENDOR / {vendor.code}</p><h1>{vendor.companyName}</h1><p>{vendor.category||'Production partner'} · {vendor.active?'Active':'Inactive'}</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="icon-button" onClick={load} aria-label="Refresh vendor"><RefreshCw size={16}/></button><button className="secondary" onClick={()=>setDocumentOpen(true)}><Paperclip size={15}/> Document</button><button className="secondary" onClick={()=>setDeliverableOpen(true)}><FileText size={15}/> Deliverable</button><button className="primary" onClick={()=>setInvoiceOpen(true)}><ReceiptText size={15}/> Supplier invoice</button></div></div>
    {state.error&&<div className="settings-notice error">{state.error}</div>}
    <section className="panel" style={{marginBottom:16}}><div className="panel-head"><div><span>VENDOR DETAILS</span><h2>{vendor.contactName||'No contact name'}</h2></div></div><div className="detail-grid"><div><small>Phone</small><strong>{vendor.phone||'—'}</strong></div><div><small>Email</small><strong>{vendor.email||'—'}</strong></div><div><small>WhatsApp</small><strong>{vendor.whatsapp||'—'}</strong></div><div><small>Payment terms</small><strong>{vendor.paymentTerms||'—'}</strong></div><div><small>Address</small><strong>{vendor.address||'—'}</strong></div><div><small>Bank / payment details</small><strong>{vendor.bankDetails||'—'}</strong></div></div></section>
    <section className="panel table-panel"><div className="panel-head"><div><span>VENDOR DOCUMENTS</span><h2><Paperclip size={17}/> {vendor.attachments?.length||0} document{(vendor.attachments?.length||0)===1?'':'s'}</h2></div></div>{vendor.attachments?.length?vendor.attachments.map(item=><div className="list-row compact" key={item.id}><div><strong>{item.name}</strong><small>{item.description||item.mimeType||'Document'} · {item.uploadedBy?.name||item.uploadedBy?.email||'System'} · {dateTime(item.createdAt)}</small></div>{item.url&&<a className="secondary" href={item.url} target="_blank" rel="noreferrer">Open</a>}</div>):<div className="empty-note">No vendor documents have been registered.</div>}</section>
    <section className="panel table-panel" style={{marginTop:16}}><div className="panel-head"><div><span>DELIVERABLES</span><h2><FileText size={17}/> {vendor.deliverables?.length||0} deliverable{(vendor.deliverables?.length||0)===1?'':'s'}</h2></div></div>{vendor.deliverables?.length?vendor.deliverables.map(item=><div className="list-row compact" key={item.id}><div><strong>{item.description}</strong><small>{item.type}{item.reference?` · ${item.reference}`:''} · {item.deliveredAt?dateTime(item.deliveredAt):'Date not set'} · {item.accepted?'Accepted':'Pending acceptance'}</small></div></div>):<div className="empty-note">No vendor deliverables have been recorded.</div>}</section>
    <section className="panel table-panel" style={{marginTop:16}}><div className="panel-head"><div><span>SUPPLIER INVOICES</span><h2><ReceiptText size={17}/> {vendor.invoices?.length||0} invoice{(vendor.invoices?.length||0)===1?'':'s'}</h2></div></div>{vendor.invoices?.length?vendor.invoices.map(item=><div className="list-row compact" key={item.id}><div><strong>{item.invoiceNumber}</strong><small>{dateTime(item.invoiceDate)} · Amount {money(item.amount)} · {item.status}{item.dueDate?` · Due ${dateTime(item.dueDate)}`:''}</small></div></div>):<div className="empty-note">No supplier invoices have been recorded.</div>}</section>

    <Modal open={documentOpen} title="Add vendor document" description={`Register a document or reference for ${vendor.companyName}.`} onClose={()=>setDocumentOpen(false)} width="620px"><form className="entity-form" onSubmit={addDocument}><label>Name<input value={documentForm.name} onChange={e=>setDocumentForm(v=>({...v,name:e.target.value}))} required/></label><label>Description<textarea rows="3" value={documentForm.description} onChange={e=>setDocumentForm(v=>({...v,description:e.target.value}))}/></label><label>URL<input type="url" value={documentForm.url} onChange={e=>setDocumentForm(v=>({...v,url:e.target.value}))} placeholder="https://…" required/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setDocumentOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Adding…':'Add document'}</button></div></form></Modal>
    <Modal open={deliverableOpen} title="Add vendor deliverable" description="Record a delivery received from the supplier." onClose={()=>setDeliverableOpen(false)} width="650px"><form className="entity-form" onSubmit={addDeliverable}><label>Type<input value={deliverableForm.type} onChange={e=>setDeliverableForm(v=>({...v,type:e.target.value}))} required/></label><label>Reference<input value={deliverableForm.reference} onChange={e=>setDeliverableForm(v=>({...v,reference:e.target.value}))}/></label><label>Description<textarea rows="3" value={deliverableForm.description} onChange={e=>setDeliverableForm(v=>({...v,description:e.target.value}))} required/></label><label>Delivered at<input type="datetime-local" value={deliverableForm.deliveredAt} onChange={e=>setDeliverableForm(v=>({...v,deliveredAt:e.target.value}))}/></label><label><input type="checkbox" checked={deliverableForm.accepted} onChange={e=>setDeliverableForm(v=>({...v,accepted:e.target.checked}))}/> Accepted</label><label>Notes<textarea rows="3" value={deliverableForm.notes} onChange={e=>setDeliverableForm(v=>({...v,notes:e.target.value}))}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setDeliverableOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Add deliverable'}</button></div></form></Modal>
    <Modal open={invoiceOpen} title="Add supplier invoice" description={`Record a supplier invoice for ${vendor.companyName}.`} onClose={()=>setInvoiceOpen(false)} width="650px"><form className="entity-form" onSubmit={addInvoice}><label>Invoice number<input value={invoiceForm.invoiceNumber} onChange={e=>setInvoiceForm(v=>({...v,invoiceNumber:e.target.value}))} required/></label><div className="form-grid"><label>Invoice date<input type="date" value={invoiceForm.invoiceDate} onChange={e=>setInvoiceForm(v=>({...v,invoiceDate:e.target.value}))} required/></label><label>Due date<input type="date" value={invoiceForm.dueDate} onChange={e=>setInvoiceForm(v=>({...v,dueDate:e.target.value}))}/></label></div><label>Amount<input type="number" min="0" step="0.01" value={invoiceForm.amount} onChange={e=>setInvoiceForm(v=>({...v,amount:e.target.value}))} required/></label><label>Status<select value={invoiceForm.status} onChange={e=>setInvoiceForm(v=>({...v,status:e.target.value}))}>{['RECEIVED','VERIFIED','PAID','DISPUTED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></label><label>Notes<textarea rows="3" value={invoiceForm.notes} onChange={e=>setInvoiceForm(v=>({...v,notes:e.target.value}))}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setInvoiceOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Add supplier invoice'}</button></div></form></Modal>
  </div>;
}
