import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';

const loginSchema=z.object({email:z.string().email(),password:z.string().min(8).max(200)});
function hashPassword(password:string,salt:string){return createHash('sha256').update(`${salt}:${password}`).digest('hex');}
function verifyPassword(password:string,stored:string){const [salt,hash]=stored.split('$');if(!salt||!hash)return false;const actual=Buffer.from(hashPassword(password,salt),'hex');const expected=Buffer.from(hash,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
export function createPasswordHash(password:string){const salt=randomBytes(16).toString('hex');return `${salt}$${hashPassword(password,salt)}`;}
export async function authRoutes(app:FastifyInstance){app.post('/api/v1/auth/login',async(request,reply)=>{const input=loginSchema.parse(request.body);const user=await prisma.user.findUnique({where:{email:input.email},include:{role:{include:{permissions:{include:{permission:true}}}}}});if(!user||user.status!=='ACTIVE'||!verifyPassword(input.password,user.passwordHash))return reply.unauthorized('Invalid email or password');const permissions=user.role.permissions.map(x=>x.permission.key);const token=await app.jwt.sign({sub:String(user.id),role:user.role.name,permissions},{expiresIn:'8h'});return {data:{token,user:{id:user.id,name:user.name,email:user.email,role:user.role.name,permissions}}};});app.get('/api/v1/auth/me',{onRequest:[async request=>{await request.jwtVerify();}]},async(request,reply)=>{const payload=request.user as {sub?:string};const id=Number(payload.sub);if(!Number.isInteger(id))return reply.unauthorized('Invalid session');const user=await prisma.user.findUnique({where:{id},include:{role:{include:{permissions:{include:{permission:true}}}}}});if(!user||user.status!=='ACTIVE')return reply.unauthorized('Session expired');return {data:{id:user.id,name:user.name,email:user.email,role:user.role.name,permissions:user.role.permissions.map(x=>x.permission.key)}};});}
