import React from 'react';
import { Plus, RefreshCw, Search } from 'lucide-react';
import { api } from '../api';

export default function EnquiriesPage(){
  const [search,setSearch]=React.useState('');
  const [state,setState]=React.useState({loading:true,error:'',items:[],total:0});
  const load=React.useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await api.listEnquiries({search:search||undefined});setState({loading:false,error:'',items:r.data||[],total:r.meta?.total||0});}catch(e){setState({loading:false,error:e.message||'Unable to load enquiries',items:[],total:0});}},[search]);
  React.useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
  return <div><div className="page-head"><div><p className="eyebrow">SALES & CRM</p><h1>Enquiries</h1><p>Capture incoming requirements before they become quotations and projects.</p></div><button className="primary"><Plus size={16}/> New Enquiry</button></div><section className="panel table-panel"><div className="table-toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search enquiries…"/></label><button className="icon-button" onClick={load} aria-label="Refresh enquiries"><RefreshCw size={16}/></button><span className="table-count">{state.total} enquiries</span></div>{state.loading&&<div className="table-state">Loading enquiries…</div>}{!state.loading&&state.error&&<div className="table-state error-state">{state.error}</div>}{!state.loading&&!state.error&&!state.items.length&&<div className="table-state">No enquiries found.</div>}{!state.loading&&!state.error&&state.items.length>0&&<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Number</th><th>Client</th><th>Requirement</th><th>Source</th><th>Target date</th><th>Status</th></tr></thead><tbody>{state.items.map(x=><tr key={x.id}><td>{x.number}</td><td><strong>{x.client?.companyName||'—'}</strong><small>{x.client?.contactName||''}</small></td><td>{x.requirement}</td><td>{x.source||'—'}</td><td>{x.targetDate?new Date(x.targetDate).toLocaleDateString():'—'}</td><td><span className="table-status">{x.status.replaceAll('_',' ')}</span></td></tr>)}</tbody></table></div>}</section></div>;
}
