import React from 'react';
import { Plus, RefreshCw, Search } from 'lucide-react';
import { api } from '../api';

export default function ProjectsPage(){
  const [search,setSearch]=React.useState(''); const [state,setState]=React.useState({loading:true,error:'',items:[],total:0});
  const load=React.useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await api.listProjects({search:search||undefined});setState({loading:false,error:'',items:r.data||[],total:r.meta?.total||0});}catch(e){setState({loading:false,error:e.message||'Unable to load projects',items:[],total:0});}},[search]);
  React.useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
  return <div><div className="page-head"><div><p className="eyebrow">DELIVERY</p><h1>Projects</h1><p>Manage client engagements and the jobs, costs and delivery work inside them.</p></div><button className="primary"><Plus size={16}/> New Project</button></div><section className="panel table-panel"><div className="table-toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects…"/></label><button className="icon-button" onClick={load} aria-label="Refresh projects"><RefreshCw size={16}/></button><span className="table-count">{state.total} projects</span></div>{state.loading&&<div className="table-state">Loading projects…</div>}{!state.loading&&state.error&&<div className="table-state error-state">{state.error}</div>}{!state.loading&&!state.error&&!state.items.length&&<div className="table-state">No projects found.</div>}{!state.loading&&!state.error&&state.items.length>0&&<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Project</th><th>Client</th><th>Owner</th><th>Jobs</th><th>Value</th><th>Status</th><th>Due</th></tr></thead><tbody>{state.items.map(x=><tr key={x.id}><td><strong>{x.number}</strong><small>{x.name}</small></td><td>{x.client?.companyName||'—'}</td><td>{x.owner?.name||'Unassigned'}</td><td>{x._count?.jobs??0}</td><td>LKR {Number(x.value||0).toLocaleString()}</td><td><span className="table-status">{x.status.replaceAll('_',' ')}</span></td><td>{x.dueDate?new Date(x.dueDate).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div>}</section></div>;
}
