import React from 'react';
import { Plus, RefreshCw, Search } from 'lucide-react';
import { api } from '../api';

export default function QuotesPage(){
  const [search,setSearch]=React.useState(''); const [state,setState]=React.useState({loading:true,error:'',items:[],total:0});
  const load=React.useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await api.listQuotes({search:search||undefined});setState({loading:false,error:'',items:r.data||[],total:r.meta?.total||0});}catch(e){setState({loading:false,error:e.message||'Unable to load quotes',items:[],total:0});}},[search]);
  React.useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
  return <div><div className="page-head"><div><p className="eyebrow">SALES & CRM</p><h1>Quotes</h1><p>Manage quotations, expected delivery costs and client decisions.</p></div><button className="primary"><Plus size={16}/> New Quote</button></div><section className="panel table-panel"><div className="table-toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotes…"/></label><button className="icon-button" onClick={load} aria-label="Refresh quotes"><RefreshCw size={16}/></button><span className="table-count">{state.total} quotes</span></div>{state.loading&&<div className="table-state">Loading quotes…</div>}{!state.loading&&state.error&&<div className="table-state error-state">{state.error}</div>}{!state.loading&&!state.error&&!state.items.length&&<div className="table-state">No quotes found.</div>}{!state.loading&&!state.error&&state.items.length>0&&<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Quote</th><th>Client</th><th>Items</th><th>Total</th><th>Expected margin</th><th>Status</th></tr></thead><tbody>{state.items.map(x=><tr key={x.id}><td><strong>{x.number}</strong><small>{x.validUntil?`Valid to ${new Date(x.validUntil).toLocaleDateString()}`:'No expiry'}</small></td><td>{x.client?.companyName||'—'}</td><td>{x.items?.length??0}</td><td>LKR {Number(x.total||0).toLocaleString()}</td><td>LKR {Number(x.expectedMargin||0).toLocaleString()}</td><td><span className="table-status">{x.status}</span></td></tr>)}</tbody></table></div>}</section></div>;
}
