import React from 'react';
import { Check, Edit3, Plus, RefreshCw, Search } from 'lucide-react';
import ResourceTable from '../../shared/components/ResourceTable';
import Modal from '../../../components/common/Modal';
import TimeEntryForm from '../components/TimeEntryForm';
import { api } from '../../../api';

export default function TimeTrackingPage(){
  const [search,setSearch]=React.useState('');const [state,setState]=React.useState({loading:true,error:'',items:[],total:0});const [open,setOpen]=React.useState(false);const [editing,setEditing]=React.useState(null);const [saving,setSaving]=React.useState(false);const [lookups,setLookups]=React.useState({employees:[],jobs:[],error:''});
  const load=React.useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await api.listTime({pageSize:100});const term=search.toLowerCase();const items=(r.data||[]).filter(x=>!term||x.employee?.name?.toLowerCase().includes(term)||x.job?.number?.toLowerCase().includes(term)||x.task?.title?.toLowerCase().includes(term));setState({loading:false,error:'',items,total:items.length})}catch(e){setState({loading:false,error:e.message||'Unable to load time entries',items:[],total:0})}},[search]);
  React.useEffect(()=>{load()},[load]);
  React.useEffect(()=>{Promise.all([api.listEmployees({pageSize:100}),api.listJobs({pageSize:100})]).then(([e,j])=>setLookups({employees:e.data||[],jobs:j.data||[],error:''})).catch(e=>setLookups(v=>({...v,error:e.message||'Unable to load time entry form data'})))},[]);
  async function save(input){setSaving(true);try{if(editing)await api.updateTime(editing.id,input);else await api.createTime(input);setOpen(false);setEditing(null);await load()}finally{setSaving(false)}}
  async function approve(id){setSaving(true);try{await api.approveTimeEntry(id);await load()}catch(e){setState(s=>({...s,error:e.message||'Unable to approve time entry'}))}finally{setSaving(false)}}
  return <div><div className="page-head"><div><p className="eyebrow">TEAM & LABOUR</p><h1>Time Tracking</h1><p>Record production hours against employees, projects, jobs and tasks for labour costing.</p></div><button className="primary" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={16}/> Log Time</button></div>{lookups.error&&<div className="form-error">{lookups.error}</div>}<section className="panel table-panel"><div className="table-toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employee or job…"/></label><button className="icon-button" onClick={load} aria-label="Refresh time entries"><RefreshCw size={16}/></button><span className="table-count">{state.total} entries</span></div><ResourceTable loading={state.loading} error={state.error} rows={state.items} columns={[{key:'workDate',label:'Date',render:r=>new Date(r.workDate).toLocaleDateString()},{key:'employee',label:'Employee',render:r=>r.employee?.name||'—'},{key:'job',label:'Job',render:r=>r.job?.number||'—'},{key:'task',label:'Task',render:r=>r.task?.title||'—'},{key:'hours',label:'Hours',render:r=>r.hours},{key:'billable',label:'Billable',render:r=>r.billable?'Yes':'No'},{key:'approval',label:'Approval',render:r=>r.approved?<span className="table-status">Approved</span>:<button className="icon-button" onClick={()=>approve(r.id)} disabled={saving} aria-label={`Approve time entry for ${r.employee?.name||'employee'}`}><Check size={15}/></button>},{key:'actions',label:'',render:r=>r.approved?null:<button className="icon-button" onClick={()=>{setEditing(r);setOpen(true)}} aria-label={`Edit time entry for ${r.employee?.name||'employee'}`}><Edit3 size={15}/></button>}]} /></section><Modal open={open} title={editing?'Edit time entry':'Log time'} description="Record employee hours used for labour costing. Approved entries are locked." onClose={()=>{setOpen(false);setEditing(null)}} width="760px"><TimeEntryForm editMode={Boolean(editing)} initialValues={editing||{}} employees={lookups.employees} jobs={lookups.jobs} onSubmit={save} onCancel={()=>{setOpen(false);setEditing(null)}} submitting={saving}/></Modal></div>;
}
