CREATE TABLE IF NOT EXISTS WorkflowTransition (
  id INT NOT NULL AUTO_INCREMENT,
  entity VARCHAR(30) NOT NULL,
  fromStatus VARCHAR(50) NOT NULL,
  toStatus VARCHAR(50) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY WorkflowTransition_entity_from_to_key (entity, fromStatus, toStatus),
  KEY WorkflowTransition_entity_from_idx (entity, fromStatus),
  KEY WorkflowTransition_entity_to_idx (entity, toStatus)
);

INSERT IGNORE INTO WorkflowTransition (entity, fromStatus, toStatus, active) VALUES
('QUOTE','DRAFT','SENT',TRUE),('QUOTE','DRAFT','CANCELLED',TRUE),
('QUOTE','SENT','VIEWED',TRUE),('QUOTE','SENT','ACCEPTED',TRUE),('QUOTE','SENT','REJECTED',TRUE),('QUOTE','SENT','EXPIRED',TRUE),('QUOTE','SENT','CANCELLED',TRUE),
('QUOTE','VIEWED','ACCEPTED',TRUE),('QUOTE','VIEWED','REJECTED',TRUE),('QUOTE','VIEWED','EXPIRED',TRUE),('QUOTE','VIEWED','CANCELLED',TRUE),
('ENQUIRY','OPEN','QUOTING',TRUE),('ENQUIRY','OPEN','CLOSED',TRUE),
('ENQUIRY','QUOTING','CLOSED',TRUE),('ENQUIRY','QUOTING','CONVERTED',TRUE),
('PROJECT','PLANNED','ACTIVE',TRUE),('PROJECT','PLANNED','CANCELLED',TRUE),
('PROJECT','ACTIVE','ON_HOLD',TRUE),('PROJECT','ACTIVE','COMPLETED',TRUE),('PROJECT','ACTIVE','CANCELLED',TRUE),
('PROJECT','ON_HOLD','ACTIVE',TRUE),('PROJECT','ON_HOLD','CANCELLED',TRUE),
('JOB','DRAFT','READY',TRUE),('JOB','DRAFT','CANCELLED',TRUE),
('JOB','READY','IN_PROGRESS',TRUE),('JOB','READY','BLOCKED',TRUE),('JOB','READY','CANCELLED',TRUE),
('JOB','IN_PROGRESS','BLOCKED',TRUE),('JOB','IN_PROGRESS','REVIEW',TRUE),('JOB','IN_PROGRESS','COMPLETED',TRUE),('JOB','IN_PROGRESS','CANCELLED',TRUE),
('JOB','BLOCKED','READY',TRUE),('JOB','BLOCKED','IN_PROGRESS',TRUE),('JOB','BLOCKED','CANCELLED',TRUE),
('JOB','REVIEW','IN_PROGRESS',TRUE),('JOB','REVIEW','COMPLETED',TRUE),('JOB','REVIEW','CANCELLED',TRUE),
('TASK','PENDING','READY',TRUE),('TASK','PENDING','CANCELLED',TRUE),
('TASK','READY','IN_PROGRESS',TRUE),('TASK','READY','BLOCKED',TRUE),('TASK','READY','CANCELLED',TRUE),
('TASK','IN_PROGRESS','BLOCKED',TRUE),('TASK','IN_PROGRESS','REVIEW',TRUE),('TASK','IN_PROGRESS','COMPLETED',TRUE),('TASK','IN_PROGRESS','CANCELLED',TRUE),
('TASK','BLOCKED','READY',TRUE),('TASK','BLOCKED','IN_PROGRESS',TRUE),('TASK','BLOCKED','CANCELLED',TRUE),
('TASK','REVIEW','IN_PROGRESS',TRUE),('TASK','REVIEW','COMPLETED',TRUE),('TASK','REVIEW','CANCELLED',TRUE);
