import React from 'react';
import { Plus, Search, CheckCircle2 } from 'lucide-react';
import { api } from '../../../api';
import Modal from '../../../components/common/Modal';
import ResourceTable from '../../shared/components/ResourceTable';

function Field({label,children}){return <label className="form-field"><span>{label}</span>{children}</label>}

export default function InstallationsPage(){
  const [rows,setRows]=React.useState([]);const [projects,setProjects]=React.useState([]);const [jobs,setJobs]=React.useState([]);const [query,setQuery]=React.useState('');const [open,setOpen]=React.useState(false);const [loading,setLoading]=React.useState(true);const [error,setError]=React.useState('');const [saving,setSaving]=React.useState(false);
  const [form,setForm]=React.useState({number:'',projectId:'',jobId:'',siteAddress:'',siteContact:'',scheduledAt:'',team:'',vehicle:'',status:'SCHEDULED',requirements:'',notes:''});
  const load=React.useCallback(async()=>{setLoading(true);setError('');try{const [i,p,j]=await Promise.all([api.listInstallations({q:query}),api.listProjects(),api.listJobs()]);setRows(i.data??[]);setProjects(p.data??[]);setJobs(j.data??[])}catch(e){setError(e.message)}finally{setLoading(false)}},[query]);
  React.useEffect(()=>{load()},[load]);
  const create=async()=>{setSaving(true);setError('');try{await api.createInstallation({...form,projectId:Number(form.projectId),jobId:form.jobId?Number(form.jobId):null,scheduledAt:form.scheduledAt?new Date(form.scheduledAt).toISOString():null});setOpen(false);setForm({number:'',projectId:'',jobId:'',siteAddress:'',siteContact:'',scheduledAt:'',team:'',vehicle:'',status:'SCHEDULED',requirements:'',notes:''});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const complete=async(row)=>{try{await api.updateInstallationStatus(row.id,{status:'COMPLETED'});await load()}catch(e){setError(e.message)}};
  const columns=[{key:'number',label:'Installation'},{key:'project',label:'Project',render:r=>r.project?.number||'—'},{key:'client',label:'Client',render:r=>r.project?.client?.companyName||'—'},{key:'scheduledAt',label:'Schedule',render:r=>r.scheduledAt?new Date(r.scheduledAt).toLocaleString():'Unscheduled'},{key:'team',label:'Team',render:r=>r.team||'—'},{key:'vehicle',label:'Vehicle',render:r=>r.vehicle||'—'},{key:'status',label:'Status',render:r=><><span className="table-status">{r.status}</span>{r.status!=='COMPLETED'&&<button className="icon-button" style={{marginLeft:8}} title="Mark complete" onClick={()=>complete(r)}><CheckCircle2 size={14}/></button>}</>}];
  return <><div className="page-head"><div><p className="eyebrow">PRODUCTION / FIELD OPERATIONS</p><h1>Installations</h1><p>Schedule site work, assign teams and vehicles, and capture completion.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/> New installation</button></div><div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search installation, site or team"/></div></div><ResourceTable columns={columns} rows={rows} loading={loading} error={error}/><Modal open={open} title="New installation" description="Schedule a field installation against a project or job." onClose={()=>setOpen(false)} width="800px"><div className="form-grid form-grid-2"><Field label="Installation number"><input value={form.number} onChange={e=>setForm({...form,number:e.target.value})} placeholder="INS-2026-001"/></Field><Field label="Project"><select value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value,jobId:''})}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.number} · {p.name}</option>)}</select></Field><Field label="Job (optional)"><select value={form.jobId} onChange={e=>setForm({...form,jobId:e.target.value})}><option value="">Select job</option>{jobs.filter(j=>!form.projectId||j.projectId===Number(form.projectId)).map(j=><option key={j.id} value={j.id}>{j.number} · {j.title}</option>)}</select></Field><Field label="Scheduled date/time"><input type="datetime-local" value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})}/></Field><Field label="Site address"><input value={form.siteAddress} onChange={e=>setForm({...form,siteAddress:e.target.value})}/></Field><Field label="Site contact"><input value={form.siteContact} onChange={e=>setForm({...form,siteContact:e.target.value})}/></Field><Field label="Team"><input value={form.team} onChange={e=>setForm({...form,team:e.target.value})} placeholder="Installation Team A"/></Field><Field label="Vehicle"><input value={form.vehicle} onChange={e=>setForm({...form,vehicle:e.target.value})} placeholder="KA-1234"/></Field><Field label="Requirements"><textarea value={form.requirements} onChange={e=>setForm({...form,requirements:e.target.value})}/></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={saving||!form.number||!form.projectId||!form.siteAddress} onClick={create}>{saving?'Creating…':'Create installation'}</button></div></Modal></>;
}
