import Fastify, { type FastifyError } from 'fastify';
import cors from '@fastify/cors';
import jwt from '@fastify/jwt';
import sensible from '@fastify/sensible';
import { randomUUID } from 'node:crypto';
import { env, corsOrigins } from './config/env.js';
import { authRoutes } from './modules/auth/auth.routes.js';
import { dashboardRoutes } from './modules/dashboard/dashboard.routes.js';
import { leadsRoutes } from './modules/leads/leads.routes.js';
import { clientsRoutes } from './modules/clients/clients.routes.js';
import { enquiriesRoutes } from './modules/enquiries/enquiries.routes.js';
import { quotesRoutes } from './modules/quotes/quotes.routes.js';
import { projectsRoutes } from './modules/projects/projects.routes.js';
import { servicesRoutes } from './modules/services/services.routes.js';
import { jobsRoutes } from './modules/jobs/jobs.routes.js';
import { tasksRoutes } from './modules/tasks/tasks.routes.js';
import { employeesRoutes } from './modules/employees/employees.routes.js';
import { timeTrackingRoutes } from './modules/time-tracking/time.routes.js';
import { materialsRoutes } from './modules/materials/materials.routes.js';
import { inventoryRoutes } from './modules/inventory/inventory.routes.js';
import { vendorsRoutes } from './modules/vendors/vendors.routes.js';
import { outsourcingRoutes } from './modules/outsourcing/outsourcing.routes.js';
import { expensesRoutes } from './modules/expenses/expenses.routes.js';
import { purchasingRoutes } from './modules/purchasing/purchasing.routes.js';
import { profitabilityRoutes } from './modules/profitability/profitability.routes.js';
import { installationsRoutes } from './modules/installations/installations.routes.js';
import { financeRoutes } from './modules/finance/finance.routes.js';

export function buildApp(){
  const app=Fastify({logger:true,requestIdHeader:'x-request-id',genReqId:()=>randomUUID()});
  app.register(cors,{origin:corsOrigins,credentials:true});
  app.register(sensible);
  app.register(jwt,{secret:env.JWT_SECRET});
  app.get('/health',async()=>({status:'ok',service:'kandy-ads-backend',environment:env.NODE_ENV,timestamp:new Date().toISOString()}));
  app.get('/api/v1',async()=>({name:'Kandy Ads Operations API',version:'v1'}));
  app.register(authRoutes);
  app.register(dashboardRoutes);
  app.register(leadsRoutes);
  app.register(clientsRoutes);
  app.register(enquiriesRoutes);
  app.register(quotesRoutes);
  app.register(projectsRoutes);
  app.register(servicesRoutes);
  app.register(jobsRoutes);
  app.register(tasksRoutes);
  app.register(employeesRoutes);
  app.register(timeTrackingRoutes);
  app.register(materialsRoutes);
  app.register(inventoryRoutes);
  app.register(vendorsRoutes);
  app.register(outsourcingRoutes);
  app.register(expensesRoutes);
  app.register(purchasingRoutes);
  app.register(profitabilityRoutes);
  app.register(installationsRoutes);
  app.register(financeRoutes);
  app.setErrorHandler((error,request,reply)=>{
    const fastifyError=error as FastifyError;
    request.log.error(fastifyError);
    const status=fastifyError.statusCode&&fastifyError.statusCode>=400?fastifyError.statusCode:500;
    return reply.status(status).send({error:{code:fastifyError.code??'INTERNAL_ERROR',message:fastifyError.message??'Unexpected server error',requestId:request.id}});
  });
  return app;
}
