import React from 'react';
import { Save } from 'lucide-react';
import { api } from '../../../api';

export default function EnquiryQuoteForm({enquiry,onSubmit,onCancel,submitting=false}){
 const [form,setForm]=React.useState({number:`QT-${enquiry.id}-${Date.now()}`,validUntil:'',serviceId:'',quantity:'1',unit:'job',rate:'0',expectedMaterial:'0',expectedLabour:'0',expectedOutsource:'0',expectedExpense:'0'});
 const [services,setServices]=React.useState([]);const [error,setError]=React.useState('');const [loading,setLoading]=React.useState(true);
 React.useEffect(()=>{api.listServices({pageSize:100}).then(r=>setServices(r.data||[])).catch(e=>setError(e.message||'Unable to load services')).finally(()=>setLoading(false));},[]);
 const set=k=>e=>setForm(v=>({...v,[k]:e.target.value}));
 async function submit(e){e.preventDefault();setError('');if(!form.rate||Number(form.rate)<0){setError('Enter a valid quote rate.');return;}try{await onSubmit({number:form.number.trim()||undefined,validUntil:form.validUntil||undefined,expectedMaterial:Number(form.expectedMaterial)||0,expectedLabour:Number(form.expectedLabour)||0,expectedOutsource:Number(form.expectedOutsource)||0,expectedExpense:Number(form.expectedExpense)||0,items:[{serviceId:form.serviceId?Number(form.serviceId):undefined,description:enquiry.requirement,quantity:Number(form.quantity),unit:form.unit.trim()||'job',rate:Number(form.rate),discount:0,tax:0}]});}catch(err){setError(err.message||'Unable to create quote.');}}
 return <form className="entity-form" onSubmit={submit}><div className="form-grid two"><label>Quote number<input value={form.number} onChange={set('number')} required/></label><label>Client<input value={`${enquiry.client?.companyName||''} (${enquiry.client?.code||''})`} disabled/></label><label>Requirement<textarea value={enquiry.requirement} disabled rows="4"/></label><label>Service<select value={form.serviceId} onChange={set('serviceId')} disabled={loading}><option value="">Optional service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Quantity<input type="number" min="0.001" step="0.001" value={form.quantity} onChange={set('quantity')}/></label><label>Unit<input value={form.unit} onChange={set('unit')}/></label><label>Rate (LKR)<input type="number" min="0" step="0.01" value={form.rate} onChange={set('rate')}/></label><label>Valid until<input type="date" value={form.validUntil} onChange={set('validUntil')}/></label><label>Expected material cost (LKR)<input type="number" min="0" step="0.01" value={form.expectedMaterial} onChange={set('expectedMaterial')}/></label><label>Expected labour cost (LKR)<input type="number" min="0" step="0.01" value={form.expectedLabour} onChange={set('expectedLabour')}/></label><label>Expected outsourcing cost (LKR)<input type="number" min="0" step="0.01" value={form.expectedOutsource} onChange={set('expectedOutsource')}/></label><label>Expected direct expense (LKR)<input type="number" min="0" step="0.01" value={form.expectedExpense} onChange={set('expectedExpense')}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={submitting||loading}>{submitting?'Creating…':<><Save size={16}/> Create Quote</>}</button></div></form>;
}
