import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { convertEnquiryToQuote, EnquiryQuoteConversionError } from './enquiry-quote-conversion.service.js';
import { canTransition, enquiryTransitions } from '../workflow/workflow.rules.js';

const createSchema=z.object({number:z.string().trim().min(2).max(50),clientId:z.coerce.number().int().positive(),source:z.string().max(80).optional(),requirement:z.string().min(2).max(5000),siteLocation:z.string().max(500).optional(),targetDate:z.coerce.date().optional(),priority:z.string().max(30).optional()});
const updateSchema=createSchema.partial().omit({number:true});
const statusSchema=z.object({status:z.enum(['OPEN','QUOTING','CONVERTED','CLOSED'])});
const quoteItemSchema=z.object({serviceId:z.coerce.number().int().positive().optional(),description:z.string().min(1).max(1000),quantity:z.coerce.number().positive(),unit:z.string().min(1).max(30),rate:z.coerce.number().nonnegative(),discount:z.coerce.number().nonnegative().default(0),tax:z.coerce.number().nonnegative().default(0)});
const convertSchema=z.object({number:z.string().trim().min(2).max(50).optional(),validUntil:z.coerce.date().optional(),expectedMaterial:z.coerce.number().nonnegative().default(0),expectedLabour:z.coerce.number().nonnegative().default(0),expectedOutsource:z.coerce.number().nonnegative().default(0),expectedExpense:z.coerce.number().nonnegative().default(0),items:z.array(quoteItemSchema).min(1)});

function actorId(request:FastifyRequest){const sub=(request.user as {sub?:string}).sub;const id=Number(sub);return Number.isInteger(id)&&id>0?id:null;}
async function audit(request:FastifyRequest,action:string,enquiryId:number,before:unknown,after:unknown){await prisma.auditLog.create({data:{userId:actorId(request),action,entity:'Enquiry',entityId:String(enquiryId),beforeJson:before as any,afterJson:after as any}});}
function serializeAudit(entry:any){return {...entry,id:typeof entry.id==='bigint'?entry.id.toString():entry.id};}

export async function enquiriesRoutes(app: FastifyInstance){
  app.get('/api/v1/enquiries',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const where={...(q.status?{status:q.status as any}:{}),...(q.search?{OR:[{number:{contains:q.search}},{requirement:{contains:q.search}}]}:{})};const [items,total]=await Promise.all([prisma.enquiry.findMany({where,include:{client:true,quote:true},orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.enquiry.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};});
  app.get('/api/v1/enquiries/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const item=await prisma.enquiry.findUnique({where:{id},include:{client:true,quote:{include:{items:true}},}});if(!item)return reply.notFound('Enquiry not found');return {data:item};});
  app.get('/api/v1/enquiries/:id/activity',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const enquiry=await prisma.enquiry.findUnique({where:{id},select:{id:true}});if(!enquiry)return reply.notFound('Enquiry not found');const data=await prisma.auditLog.findMany({where:{entity:'Enquiry',entityId:String(id)},include:{user:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:'desc'},take:200});return {data:data.map(serializeAudit)};});
  app.post('/api/v1/enquiries',async(request,reply)=>{const input=createSchema.parse(request.body);const client=await prisma.client.findUnique({where:{id:input.clientId}});if(!client)return reply.badRequest('Client not found');const item=await prisma.enquiry.create({data:input,include:{client:true}});await audit(request,'CREATE',item.id,null,{number:item.number,status:item.status,clientId:item.clientId,source:item.source,requirement:item.requirement,siteLocation:item.siteLocation,targetDate:item.targetDate,priority:item.priority});return reply.code(201).send({data:item});});
  app.patch('/api/v1/enquiries/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=updateSchema.parse(request.body);const existing=await prisma.enquiry.findUnique({where:{id}});if(!existing)return reply.notFound('Enquiry not found');if(['CONVERTED','CLOSED'].includes(existing.status))return reply.badRequest(`Enquiry cannot be edited from ${existing.status}`);if(input.clientId){const client=await prisma.client.findUnique({where:{id:input.clientId}});if(!client)return reply.badRequest('Client not found');}const item=await prisma.enquiry.update({where:{id},data:input,include:{client:true,quote:true}});await audit(request,'UPDATE',id,{status:existing.status,clientId:existing.clientId,source:existing.source,requirement:existing.requirement,siteLocation:existing.siteLocation,targetDate:existing.targetDate,priority:existing.priority},{status:item.status,clientId:item.clientId,source:item.source,requirement:item.requirement,siteLocation:item.siteLocation,targetDate:item.targetDate,priority:item.priority});return {data:item};});
  app.patch('/api/v1/enquiries/:id/status',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=statusSchema.parse(request.body);const existing=await prisma.enquiry.findUnique({where:{id},include:{quote:true}});if(!existing)return reply.notFound('Enquiry not found');if(!canTransition(enquiryTransitions,existing.status,input.status))return reply.badRequest(`Invalid enquiry transition: ${existing.status} -> ${input.status}`);if(input.status==='CONVERTED'&&!existing.quote)return reply.badRequest('Enquiry cannot be marked converted before a quote is created');const item=await prisma.enquiry.update({where:{id},data:{status:input.status},include:{client:true,quote:true}});await audit(request,'STATUS_CHANGE',id,{status:existing.status},{status:item.status});return {data:item};});
  app.post('/api/v1/enquiries/:id/convert-to-quote',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=convertSchema.parse(request.body);try{const quote=await convertEnquiryToQuote(id,{...input,actorId:actorId(request)});return reply.code(201).send({data:quote});}catch(error){if(error instanceof EnquiryQuoteConversionError)return reply.status(error.statusCode).send({error:{code:error.statusCode===409?'CONFLICT':'ENQUIRY_QUOTE_CONVERSION_ERROR',message:error.message,requestId:request.id}});throw error;}});
}
