import React from 'react';
import { NavLink } from 'react-router-dom';
import { api } from '../../../api';

export default function DashboardPage(){
  const [summary,setSummary]=React.useState(null);const [error,setError]=React.useState('');
  React.useEffect(()=>{let active=true;api.getDashboardSummary().then(r=>{if(active)setSummary(r.data)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
  const cards=[['Active Projects',summary?.activeProjects??'—','live from API'],['Jobs In Production',summary?.jobsNeedingAttention??'—','needs attention'],['Pending Quotes',summary?.pendingQuotes??'—','awaiting action'],['Active Clients',summary?.activeClients??'—','current clients']];
  return <div><div className="page-head"><div><p className="eyebrow">COMMAND CENTER</p><h1>Good afternoon.</h1><p>Here is what needs attention across Kandy Ads today.</p></div><NavLink to="/projects" className="primary">+ New Project</NavLink></div>{error&&<div className="form-error">{error}</div>}<div className="stat-grid">{cards.map(c=><div className="stat" key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><small>{c[2]}</small></div>)}</div><div className="content-grid"><section className="panel"><div className="panel-head"><div><span>DELIVERY</span><h2>Jobs needing attention</h2></div><NavLink to="/jobs">View all →</NavLink></div>{[['KA-1042','DSI Branch Signage','In Production','Due today'],['KA-1047','NinetyNine Retail Graphics','Blocked','Needs artwork'],['KA-1051','KFC Pylon Upgrade','Ready','Starts tomorrow'],['KA-1056','Hotel Signage Package','Outsourced','Vendor delivery']].map(x=><div className="list-row" key={x[0]}><div><b>{x[0]}</b><strong>{x[1]}</strong></div><span className={'badge '+x[2].toLowerCase().replace(' ','-')}>{x[2]}</span><small>{x[3]}</small></div>)}</section><section className="panel"><div className="panel-head"><div><span>STOCK</span><h2>Low stock</h2></div><NavLink to="/inventory">Inventory →</NavLink></div>{[['Acrylic 3mm','8 sheets','Reorder 20'],['LED Module','14 units','Reorder 50'],['ACM Sheet','3 sheets','Reorder 10'],['Vinyl White','12 m','Reorder 40']].map(x=><div className="list-row compact" key={x[0]}><div><strong>{x[0]}</strong><small>{x[2]}</small></div><b>{x[1]}</b></div>)}</section></div></div>;
}
