import React from 'react';
import { NavLink } from 'react-router-dom';
import { api } from '../../../api';

const money=v=>`LKR ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=v=>v?new Date(v).toLocaleDateString():'—';

export default function DashboardPage(){
  const [summary,setSummary]=React.useState(null); const [ops,setOps]=React.useState(null); const [error,setError]=React.useState('');
  React.useEffect(()=>{let active=true;Promise.all([api.getDashboardSummary(),api.getDashboardOperational({days:14})]).then(([a,b])=>{if(active){setSummary(a.data);setOps(b.data)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
  const cards=[['Active Projects',summary?.activeProjects??'—','live from API'],['Jobs In Production',summary?.jobsNeedingAttention??'—','needs attention'],['Pending Quotes',summary?.pendingQuotes??'—','awaiting action'],['Active Clients',summary?.activeClients??'—','current clients']];
  const f=ops?.finance;
  return <div><div className="page-head"><div><p className="eyebrow">COMMAND CENTER</p><h1>Good afternoon.</h1><p>Live operational signals across delivery, stock, finance and field operations.</p></div><NavLink to="/projects" className="primary">+ New Project</NavLink></div>{error&&<div className="form-error">{error}</div>}<div className="stat-grid">{cards.map(c=><div className="stat" key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><small>{c[2]}</small></div>)}</div>
    <div className="stat-grid">{[['Revenue',f?.revenue,'invoiced'],['Expenses',f?.expenses,'approved / paid'],['Profit',f?.profit,'operational estimate'],['Receivables',f?.receivables,'outstanding']].map(c=><div className="stat" key={c[0]}><span>{c[0]}</span><strong>{c[1]===undefined?'—':money(c[1])}</strong><small>{c[2]}</small></div>)}</div>
    <div className="content-grid">
      <section className="panel"><div className="panel-head"><div><span>DELIVERY</span><h2>Due / overdue jobs</h2></div><NavLink to="/jobs">View all →</NavLink></div>{(ops?.jobs?.due||[]).length===0&&<p>No overdue jobs.</p>}{(ops?.jobs?.due||[]).slice(0,6).map(x=><div className="list-row" key={x.id}><div><b>{x.number}</b><strong>{x.title}</strong></div><span className="badge blocked">Overdue</span><small>{date(x.dueDate)}</small></div>)}</section>
      <section className="panel"><div className="panel-head"><div><span>STOCK</span><h2>Reorder alerts</h2></div><NavLink to="/inventory">Inventory →</NavLink></div>{(ops?.inventory?.reorderAlerts||[]).length===0&&<p>No reorder alerts.</p>}{(ops?.inventory?.reorderAlerts||[]).slice(0,6).map(x=><div className="list-row compact" key={x.id}><div><strong>{x.name}</strong><small>Reorder at {x.reorderLevel} {x.unit}</small></div><b>{x.availableQty} {x.unit}</b></div>)}</section>
      <section className="panel"><div className="panel-head"><div><span>PURCHASING</span><h2>Upcoming deliveries</h2></div><NavLink to="/purchasing">Purchasing →</NavLink></div>{(ops?.purchasing?.due||[]).length===0&&<p>No deliveries in the next 14 days.</p>}{(ops?.purchasing?.due||[]).slice(0,6).map(x=><div className="list-row" key={x.id}><div><b>{x.number}</b><strong>{x.vendor}</strong></div><span className={'badge '+(x.overdue?'blocked':'ready')}>{x.overdue?'Overdue':x.status}</span><small>{date(x.expectedDate)}</small></div>)}</section>
      <section className="panel"><div className="panel-head"><div><span>FIELD OPERATIONS</span><h2>Upcoming installations</h2></div><NavLink to="/installations">Installations →</NavLink></div>{(ops?.installations||[]).length===0&&<p>No installations in the next 14 days.</p>}{(ops?.installations||[]).slice(0,6).map(x=><div className="list-row" key={x.id}><div><b>{x.number}</b><strong>{x.project.name}</strong><small>{x.siteAddress}</small></div><span className="badge ready">{x.status}</span><small>{date(x.scheduledAt)}</small></div>)}</section>
      <section className="panel"><div className="panel-head"><div><span>TEAM</span><h2>Employee workload</h2></div><NavLink to="/employees">Team →</NavLink></div>{(ops?.workload||[]).slice(0,8).map(x=><div className="list-row compact" key={x.id}><div><strong>{x.name}</strong><small>{x.department||'General'} · {x.assignedTaskCount} open tasks{x.overdueTasks?` · ${x.overdueTasks} overdue`:''}</small></div><b>{x.remainingHours}h remaining</b></div>)}{(ops?.workload||[]).length===0&&<p>No active employees.</p>}</section>
      <section className="panel"><div className="panel-head"><div><span>RECEIVABLES</span><h2>Collections watch</h2></div><NavLink to="/invoices">Invoices →</NavLink></div><div className="list-row compact"><div><strong>Outstanding</strong><small>All non-cancelled invoices</small></div><b>{f?money(f.receivables):'—'}</b></div><div className="list-row compact"><div><strong>Overdue</strong><small>Past due with balance</small></div><b>{f?money(f.overdueReceivables):'—'}</b></div></section>
    </div></div>;
}
