import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';

const itemSchema=z.object({serviceId:z.coerce.number().int().positive().optional(),description:z.string().min(1).max(1000),quantity:z.coerce.number().positive(),unit:z.string().min(1).max(30),rate:z.coerce.number().nonnegative(),discount:z.coerce.number().nonnegative().default(0),tax:z.coerce.number().nonnegative().default(0)});
const createSchema=z.object({number:z.string().min(2).max(50),clientId:z.coerce.number().int().positive(),enquiryId:z.coerce.number().int().positive().optional(),validUntil:z.coerce.date().optional(),expectedMaterial:z.coerce.number().nonnegative().default(0),expectedLabour:z.coerce.number().nonnegative().default(0),expectedOutsource:z.coerce.number().nonnegative().default(0),expectedExpense:z.coerce.number().nonnegative().default(0),items:z.array(itemSchema).min(1)});

export async function quotesRoutes(app:FastifyInstance){
  app.get('/api/v1/quotes',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const where={...(q.status?{status:q.status as any}:{}),...(q.search?{OR:[{number:{contains:q.search}},{client:{companyName:{contains:q.search}}}]}:{})};const [items,total]=await Promise.all([prisma.quote.findMany({where,include:{client:true,items:true,enquiry:true,project:true},orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.quote.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.post('/api/v1/quotes',async(request,reply)=>{const input=createSchema.parse(request.body);const items=input.items.map(i=>{const net=i.quantity*i.rate-i.discount;const total=net+i.tax;return {...i,total};});const subtotal=items.reduce((s,i)=>s+i.quantity*i.rate-i.discount,0);const discount=items.reduce((s,i)=>s+i.discount,0);const tax=items.reduce((s,i)=>s+i.tax,0);const total=subtotal+tax;const expectedCost=input.expectedMaterial+input.expectedLabour+input.expectedOutsource+input.expectedExpense;const expectedMargin=total-expectedCost;const quote=await prisma.quote.create({data:{number:input.number,clientId:input.clientId,enquiryId:input.enquiryId,validUntil:input.validUntil,subtotal,discount,tax,total,expectedMaterial:input.expectedMaterial,expectedLabour:input.expectedLabour,expectedOutsource:input.expectedOutsource,expectedExpense:input.expectedExpense,expectedMargin,items:{create:items}} ,include:{items:true,client:true}});return reply.code(201).send({data:quote});});
}
