type QuotePdfLine = {
  description: string;
  quantity: number;
  unit: string;
  rate: number;
  discount: number;
  tax: number;
  total: number;
};

type QuotePdfData = {
  number: string;
  status: string;
  validUntil: Date | null;
  client: { companyName: string; contactName: string | null; phone: string | null; email: string | null; address: string | null };
  items: QuotePdfLine[];
  subtotal: number;
  discount: number;
  tax: number;
  total: number;
  expectedMaterial: number;
  expectedLabour: number;
  expectedOutsource: number;
  expectedExpense: number;
  expectedMargin: number;
};

function ascii(value: unknown) {
  return String(value ?? '').normalize('NFKD').replace(/[^\x20-\x7E]/g, '?');
}

function money(value: number) {
  return `LKR ${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function escapePdfText(value: string) {
  return ascii(value).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrap(value: string, max = 86) {
  const words = ascii(value).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (candidate.length > max && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [''];
}

export function buildQuotePdf(quote: QuotePdfData) {
  const lines: string[] = [
    'KANDY ADS',
    `QUOTATION ${quote.number}`,
    `Status: ${quote.status}`,
    `Valid until: ${quote.validUntil ? quote.validUntil.toLocaleDateString('en-GB') : 'Not specified'}`,
    '',
    `Client: ${quote.client.companyName}`,
    `Contact: ${quote.client.contactName || 'Not specified'}`,
    `Phone: ${quote.client.phone || 'Not specified'}`,
    `Email: ${quote.client.email || 'Not specified'}`,
    `Address: ${quote.client.address || 'Not specified'}`,
    '',
    'ITEMS',
  ];

  quote.items.forEach((item, index) => {
    lines.push(`${index + 1}. ${item.description}`);
    lines.push(`   ${item.quantity} ${item.unit} x ${money(item.rate)} | Discount ${money(item.discount)} | Tax ${money(item.tax)} | Total ${money(item.total)}`);
  });

  lines.push('', 'TOTALS');
  lines.push(`Subtotal: ${money(quote.subtotal)}`);
  lines.push(`Discount: ${money(quote.discount)}`);
  lines.push(`Tax: ${money(quote.tax)}`);
  lines.push(`TOTAL: ${money(quote.total)}`);
  lines.push('', 'EXPECTED DELIVERY COSTS');
  lines.push(`Materials: ${money(quote.expectedMaterial)}`);
  lines.push(`Labour: ${money(quote.expectedLabour)}`);
  lines.push(`Outsourcing: ${money(quote.expectedOutsource)}`);
  lines.push(`Direct expenses: ${money(quote.expectedExpense)}`);
  lines.push(`Expected margin: ${money(quote.expectedMargin)}`);
  lines.push('', 'Generated by Kandy Ads Operations Platform');

  const wrapped = lines.flatMap(line => wrap(line));
  const linesPerPage = 44;
  const pages: string[][] = [];
  for (let i = 0; i < wrapped.length; i += linesPerPage) pages.push(wrapped.slice(i, i + linesPerPage));
  if (!pages.length) pages.push(['KANDY ADS']);

  const objects: string[] = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  const pageIds: number[] = [];
  const contentIds: number[] = [];

  const reserve = () => { objects.push(''); return objects.length; };
  const buildPageStream = (pageLines: string[]) => {
    const commands = ['BT', '/F1 10 Tf', '50 760 Td', '13 TL'];
    pageLines.forEach(line => commands.push(`(${escapePdfText(line)}) Tj`, 'T*'));
    commands.push('ET');
    return commands.join('\n');
  };

  pages.forEach(pageLines => {
    contentIds.push(reserve());
    pageIds.push(reserve());
  });

  objects[1] = `<< /Type /Pages /Kids [${pageIds.map(id => `${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`;
  pageIds.forEach((pageId, index) => {
    const stream = buildPageStream(pages[index]);
    const contentId = contentIds[index];
    objects[contentId - 1] = `<< /Length ${Buffer.byteLength(stream, 'binary')} >>\nstream\n${stream}\nendstream`;
    objects[pageId - 1] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`;
  });

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];
  objects.forEach((object, index) => {
    offsets[index + 1] = Buffer.byteLength(pdf, 'binary');
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'binary');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i += 1) pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, 'binary');
}
