import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { convertAcceptedQuoteToProject, QuoteConversionError } from './quote-conversion.service.js';
import { canTransition, quoteTransitions } from '../workflow/workflow.rules.js';

const itemSchema=z.object({serviceId:z.coerce.number().int().positive().optional(),description:z.string().min(1).max(1000),quantity:z.coerce.number().positive(),unit:z.string().min(1).max(30),rate:z.coerce.number().nonnegative(),discount:z.coerce.number().nonnegative().default(0),tax:z.coerce.number().nonnegative().default(0)});
const createSchema=z.object({number:z.string().min(2).max(50),clientId:z.coerce.number().int().positive(),enquiryId:z.coerce.number().int().positive().optional(),validUntil:z.coerce.date().optional(),expectedMaterial:z.coerce.number().nonnegative().default(0),expectedLabour:z.coerce.number().nonnegative().default(0),expectedOutsource:z.coerce.number().nonnegative().default(0),expectedExpense:z.coerce.number().nonnegative().default(0),items:z.array(itemSchema).min(1)});
const statusSchema=z.object({status:z.enum(['DRAFT','SENT','VIEWED','ACCEPTED','REJECTED','EXPIRED','CANCELLED'])});
const conversionSchema=z.object({number:z.string().trim().min(2).max(50).optional(),name:z.string().trim().min(2).max(200).optional(),ownerId:z.coerce.number().int().positive().optional(),startDate:z.coerce.date().optional(),dueDate:z.coerce.date().optional()}).default({});

function actorId(request:FastifyRequest){const sub=(request.user as {sub?:string}).sub;const id=Number(sub);return Number.isInteger(id)&&id>0?id:null;}

export async function quotesRoutes(app:FastifyInstance){
  app.get('/api/v1/quotes',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const where={...(q.status?{status:q.status as any}:{}),...(q.search?{OR:[{number:{contains:q.search}},{client:{companyName:{contains:q.search}}}]}:{})};const [items,total]=await Promise.all([prisma.quote.findMany({where,include:{client:true,items:true,enquiry:true,project:true},orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.quote.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.post('/api/v1/quotes',async(request,reply)=>{const input=createSchema.parse(request.body);const items=input.items.map(i=>{const net=i.quantity*i.rate-i.discount;const total=net+i.tax;return {...i,total};});const subtotal=items.reduce((s,i)=>s+i.quantity*i.rate-i.discount,0);const discount=items.reduce((s,i)=>s+i.discount,0);const tax=items.reduce((s,i)=>s+i.tax,0);const total=subtotal+tax;const expectedCost=input.expectedMaterial+input.expectedLabour+input.expectedOutsource+input.expectedExpense;const expectedMargin=total-expectedCost;const quote=await prisma.quote.create({data:{number:input.number,clientId:input.clientId,enquiryId:input.enquiryId,validUntil:input.validUntil,subtotal,discount,tax,total,expectedMaterial:input.expectedMaterial,expectedLabour:input.expectedLabour,expectedOutsource:input.expectedOutsource,expectedExpense:input.expectedExpense,expectedMargin,items:{create:items}} ,include:{items:true,client:true}});return reply.code(201).send({data:quote});});
  app.patch('/api/v1/quotes/:id/status',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=statusSchema.parse(request.body);const existing=await prisma.quote.findUnique({where:{id},include:{items:true}});if(!existing)return reply.notFound('Quote not found');if(!canTransition(quoteTransitions,existing.status,input.status))return reply.badRequest(`Invalid quote transition: ${existing.status} -> ${input.status}`);if(input.status==='SENT'&&existing.items.length===0)return reply.badRequest('Quote must contain at least one item before sending');const item=await prisma.quote.update({where:{id},data:{status:input.status},include:{client:true,items:true}});return {data:item};});
  app.post('/api/v1/quotes/:id/convert-to-project',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=conversionSchema.parse(request.body??{});try{const project=await convertAcceptedQuoteToProject(id,{...input,actorId:actorId(request)});return reply.code(201).send({data:project});}catch(error){if(error instanceof QuoteConversionError)return reply.status(error.statusCode).send({error:{code:error.statusCode===409?'CONFLICT':'QUOTE_CONVERSION_ERROR',message:error.message,requestId:request.id}});throw error;}});
}
