import React from 'react';
import { api } from '../../../api';
import './settings.css';

export default function SettingsCataloguesPage(){
  const [tax,setTax]=React.useState({name:'VAT',rate:18,inclusive:false,active:true});
  const [payments,setPayments]=React.useState([]); const [units,setUnits]=React.useState([]); const [categories,setCategories]=React.useState([]);
  const [payment,setPayment]=React.useState({name:'',code:'',sortOrder:0}); const [unit,setUnit]=React.useState({name:'',code:''}); const [category,setCategory]=React.useState({name:''});
  const [loading,setLoading]=React.useState(true); const [saving,setSaving]=React.useState(false); const [message,setMessage]=React.useState(''); const [error,setError]=React.useState('');
  const load=React.useCallback(async()=>{setLoading(true);setError('');try{const [t,p,u,c]=await Promise.all([api.getTaxSetting().catch(()=>({data:null})),api.listPaymentMethods(),api.listUnits(),api.listExpenseCategories()]);if(t.data)setTax({...t.data});setPayments(p.data||[]);setUnits(u.data||[]);setCategories(c.data||[]);}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
  React.useEffect(()=>{load()},[load]);
  const saveTax=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.updateTaxSetting({...tax,rate:Number(tax.rate)});setMessage('Tax configuration saved.')}catch(e){setError(e.message)}finally{setSaving(false)}};
  const addPayment=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.createPaymentMethod({...payment,sortOrder:Number(payment.sortOrder)});setPayment({name:'',code:'',sortOrder:0});await load();setMessage('Payment method added.')}catch(e){setError(e.message)}finally{setSaving(false)}};
  const addUnit=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.createUnit(unit);setUnit({name:'',code:''});await load();setMessage('Unit added.')}catch(e){setError(e.message)}finally{setSaving(false)}};
  const addCategory=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.createExpenseCategory(category);setCategory({name:''});await load();setMessage('Expense category added.')}catch(e){setError(e.message)}finally{setSaving(false)}};
  const toggle=async(type,row)=>{setSaving(true);setError('');try{if(type==='payment')await api.updatePaymentMethod(row.id,{active:!Boolean(row.active)});if(type==='unit')await api.updateUnit(row.id,{active:!Boolean(row.active)});await load();setMessage('Status updated.')}catch(e){setError(e.message)}finally{setSaving(false)}};
  return <div className="settings-page"><div className="page-head"><div><p className="eyebrow">MASTER DATA</p><h1>Tax, Payments & Units</h1><p>Manage tax defaults, accepted payment methods, units of measure and expense categories.</p></div></div>{message&&<div className="settings-notice success">{message}</div>}{error&&<div className="settings-notice error">{error}</div>}
    <div className="settings-grid"><section className="panel"><div className="panel-head"><div><h2>Tax configuration</h2><span>Default tax setting for future financial documents.</span></div></div>{loading?<p>Loading…</p>:<form className="settings-form" onSubmit={saveTax}><label>Name<input value={tax.name||''} onChange={e=>setTax({...tax,name:e.target.value})} required/></label><label>Rate (%)<input type="number" min="0" max="100" step="0.001" value={tax.rate} onChange={e=>setTax({...tax,rate:e.target.value})} required/></label><label><input type="checkbox" checked={!!tax.inclusive} onChange={e=>setTax({...tax,inclusive:e.target.checked})}/> Tax inclusive</label><button className="primary" disabled={saving}>{saving?'Saving…':'Save Tax'}</button></form>}</section>
    <section className="panel"><div className="panel-head"><div><h2>Payment methods</h2><span>Values available to finance workflows.</span></div></div><form className="settings-form" onSubmit={addPayment}><label>Name<input value={payment.name} onChange={e=>setPayment({...payment,name:e.target.value})} required/></label><label>Code<input value={payment.code} onChange={e=>setPayment({...payment,code:e.target.value})} required/></label><button className="primary" disabled={saving}>Add payment method</button></form><div className="role-list" style={{marginTop:14}}>{payments.map(row=><button key={row.id} disabled={saving} onClick={()=>toggle('payment',row)}><b>{row.name}</b><small>{row.code} · {Number(row.active)?'Active':'Inactive'}</small></button>)}</div></section>
    <section className="panel"><div className="panel-head"><div><h2>Units of measure</h2><span>Standard units for materials, quote and purchase lines.</span></div></div><form className="settings-form" onSubmit={addUnit}><label>Name<input value={unit.name} onChange={e=>setUnit({...unit,name:e.target.value})} required/></label><label>Code<input value={unit.code} onChange={e=>setUnit({...unit,code:e.target.value})} required/></label><button className="primary" disabled={saving}>Add unit</button></form><div className="role-list" style={{marginTop:14}}>{units.map(row=><button key={row.id} disabled={saving} onClick={()=>toggle('unit',row)}><b>{row.name}</b><small>{row.code} · {Number(row.active)?'Active':'Inactive'}</small></button>)}</div></section>
    <section className="panel"><div className="panel-head"><div><h2>Expense categories</h2><span>Classification for expense entries.</span></div></div><form className="settings-form" onSubmit={addCategory}><label>Name<input value={category.name} onChange={e=>setCategory({name:e.target.value})} required/></label><button className="primary" disabled={saving}>Add category</button></form><div className="role-list" style={{marginTop:14}}>{categories.map(row=><button key={row.id}><b>{row.name}</b><small>Category #{row.id}</small></button>)}</div></section></div>
  </div>;
}
