import React from 'react';
import { Plus, RefreshCw, Search, ArrowRight, Edit3, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../../../api';
import ResourceTable from '../../shared/components/ResourceTable';
import Modal from '../../../components/common/Modal';
import EnquiryForm from '../components/EnquiryForm';
import EnquiryQuoteForm from '../components/EnquiryQuoteForm';

export default function EnquiriesPage(){
 const [search,setSearch]=React.useState('');const [state,setState]=React.useState({loading:true,error:'',items:[],total:0});const [open,setOpen]=React.useState(false);const [editing,setEditing]=React.useState(null);const [quoteEnquiry,setQuoteEnquiry]=React.useState(null);const [saving,setSaving]=React.useState(false);const [notice,setNotice]=React.useState('');
 const load=React.useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await api.listEnquiries({search:search||undefined});setState({loading:false,error:'',items:r.data||[],total:r.meta?.total||0})}catch(e){setState({loading:false,error:e.message||'Unable to load enquiries',items:[],total:0})}},[search]);
 React.useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 async function create(input){setSaving(true);try{await api.createEnquiry(input);setOpen(false);await load()}finally{setSaving(false)}}
 async function saveEdit(input){setSaving(true);try{await api.updateEnquiry(editing.id,input);setEditing(null);setNotice(`${editing.number} updated.`);await load()}catch(e){setNotice(e.message||'Unable to update enquiry.')}finally{setSaving(false)}}
 async function createQuote(input){setSaving(true);setNotice('');try{const result=await api.convertEnquiryToQuote(quoteEnquiry.id,input);setQuoteEnquiry(null);setNotice(`${quoteEnquiry.number} converted to ${result.data.number}.`);await load()}catch(e){setNotice(e.message||'Unable to create quote.')}finally{setSaving(false)}}
 return <div><div className="page-head"><div><p className="eyebrow">SALES & CRM</p><h1>Enquiries</h1><p>Track incoming requirements and move qualified work into quotations.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/> New Enquiry</button></div>{notice&&<div className="panel" style={{marginBottom:16}}>{notice}</div>}<section className="panel table-panel"><div className="table-toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search enquiries…"/></label><button className="icon-button" onClick={load} aria-label="Refresh enquiries"><RefreshCw size={16}/></button><span className="table-count">{state.total} enquiries</span></div><ResourceTable loading={state.loading} error={state.error} rows={state.items} columns={[{key:'number',label:'Number',render:r=><Link to={`/enquiries/${r.id}`} className="table-link">{r.number}</Link>},{key:'client',label:'Client',render:r=><strong>{r.client?.companyName||'—'}</strong>},{key:'requirement',label:'Requirement'},{key:'siteLocation',label:'Site'},{key:'status',label:'Status',render:r=><span className="table-status">{r.status.replaceAll('_',' ')}</span>},{key:'targetDate',label:'Target',render:r=>r.targetDate?new Date(r.targetDate).toLocaleDateString():'—'},{key:'actions',label:'Actions',render:r=><div className="table-actions">{!['CLOSED','CONVERTED'].includes(r.status)&&<button className="secondary" onClick={()=>setEditing(r)}><Edit3 size={14}/> Edit</button>}{!r.quote&&['OPEN','QUOTING'].includes(r.status)&&<button className="secondary" onClick={()=>setQuoteEnquiry(r)}><ArrowRight size={14}/> Create Quote</button>}{r.quote&&<Link className="secondary" to={`/quotes/${r.quote.id}`}><ExternalLink size={14}/> Quote</Link>}</div>}]} /></section><Modal open={open} onClose={()=>setOpen(false)} title="New enquiry" description="Capture the client requirement before preparing a quotation." width="760px"><EnquiryForm onSubmit={create} onCancel={()=>setOpen(false)} submitting={saving}/></Modal><Modal open={!!editing} onClose={()=>setEditing(null)} title="Edit enquiry" description={editing?`Update ${editing.number}.`:''} width="760px">{editing&&<EnquiryForm initialValues={editing} editing onSubmit={saveEdit} onCancel={()=>setEditing(null)} submitting={saving}/>}</Modal><Modal open={!!quoteEnquiry} onClose={()=>setQuoteEnquiry(null)} title="Create quote from enquiry" description={quoteEnquiry?`${quoteEnquiry.number} · ${quoteEnquiry.client?.companyName||''}`:''} width="820px">{quoteEnquiry&&<EnquiryQuoteForm enquiry={quoteEnquiry} onSubmit={createQuote} onCancel={()=>setQuoteEnquiry(null)} submitting={saving}/>}</Modal></div>;
}
