import type { FastifyInstance, FastifyRequest } from 'fastify';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';

const roleSchema=z.object({name:z.string().trim().min(2).max(100),description:z.string().max(500).optional().nullable(),active:z.boolean().optional().default(true)});
const skillSchema=z.object({name:z.string().trim().min(2).max(120),description:z.string().max(500).optional().nullable(),active:z.boolean().optional().default(true)});
const capabilitySchema=z.object({roleId:z.coerce.number().int().positive().nullable().optional(),skills:z.array(z.object({skillId:z.coerce.number().int().positive(),level:z.coerce.number().int().min(1).max(5)})).max(100)});
function actorId(request:FastifyRequest){const id=Number((request.user as {sub?:string}).sub);return Number.isInteger(id)&&id>0?id:null;}
async function audit(request:FastifyRequest,action:string,entity:string,entityId:number,before:unknown,after:unknown){await prisma.auditLog.create({data:{userId:actorId(request),action,entity,entityId:String(entityId),beforeJson:before as any,afterJson:after as any}});}

export async function employeeCapabilitiesRoutes(app:FastifyInstance){
  app.get('/api/v1/employee-roles',async request=>{const q=z.object({active:z.string().optional()}).parse(request.query);const active=q.active===undefined?undefined:q.active==='true';const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM EmployeeRole ${active===undefined?Prisma.empty:Prisma.sql`WHERE active=${active}`} ORDER BY name ASC`);return {data:rows.map(row=>({...row,active:Boolean(row.active)}))};});
  app.post('/api/v1/employee-roles',async(request,reply)=>{const input=roleSchema.parse(request.body);const existing=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id FROM EmployeeRole WHERE name=${input.name} LIMIT 1`);if(existing.length)return reply.conflict('Employee role already exists');const result=await prisma.$executeRaw(Prisma.sql`INSERT INTO EmployeeRole (name,description,active) VALUES (${input.name},${input.description??null},${input.active})`);const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM EmployeeRole WHERE name=${input.name} LIMIT 1`);const item=rows[0];await audit(request,'EMPLOYEE_ROLE_CREATED','EmployeeRole',Number(item.id),null,item);return reply.code(201).send({data:{...item,active:Boolean(item.active)}});});
  app.patch('/api/v1/employee-roles/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=roleSchema.partial().parse(request.body);const existing=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM EmployeeRole WHERE id=${id} LIMIT 1`))[0];if(!existing)return reply.notFound('Employee role not found');if(input.name&&input.name!==existing.name){const duplicate=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id FROM EmployeeRole WHERE name=${input.name} AND id<>${id} LIMIT 1`);if(duplicate.length)return reply.conflict('Employee role already exists');}await prisma.$executeRaw(Prisma.sql`UPDATE EmployeeRole SET name=COALESCE(${input.name??null},name),description=${input.description===undefined?Prisma.sql`description`:Prisma.sql`${input.description??null}`},active=COALESCE(${input.active??null},active),updatedAt=CURRENT_TIMESTAMP(3) WHERE id=${id}`);const item=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM EmployeeRole WHERE id=${id}`))[0];await audit(request,'EMPLOYEE_ROLE_UPDATED','EmployeeRole',id,existing,item);return {data:{...item,active:Boolean(item.active)}};});
  app.get('/api/v1/skills',async request=>{const q=z.object({active:z.string().optional()}).parse(request.query);const active=q.active===undefined?undefined:q.active==='true';const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM Skill ${active===undefined?Prisma.empty:Prisma.sql`WHERE active=${active}`} ORDER BY name ASC`);return {data:rows.map(row=>({...row,active:Boolean(row.active)}))};});
  app.post('/api/v1/skills',async(request,reply)=>{const input=skillSchema.parse(request.body);const existing=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id FROM Skill WHERE name=${input.name} LIMIT 1`);if(existing.length)return reply.conflict('Skill already exists');await prisma.$executeRaw(Prisma.sql`INSERT INTO Skill (name,description,active) VALUES (${input.name},${input.description??null},${input.active})`);const item=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM Skill WHERE name=${input.name} LIMIT 1`))[0];await audit(request,'SKILL_CREATED','Skill',Number(item.id),null,item);return reply.code(201).send({data:{...item,active:Boolean(item.active)}});});
  app.patch('/api/v1/skills/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=skillSchema.partial().parse(request.body);const existing=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM Skill WHERE id=${id} LIMIT 1`))[0];if(!existing)return reply.notFound('Skill not found');if(input.name&&input.name!==existing.name){const duplicate=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id FROM Skill WHERE name=${input.name} AND id<>${id} LIMIT 1`);if(duplicate.length)return reply.conflict('Skill already exists');}await prisma.$executeRaw(Prisma.sql`UPDATE Skill SET name=COALESCE(${input.name??null},name),description=${input.description===undefined?Prisma.sql`description`:Prisma.sql`${input.description??null}`},active=COALESCE(${input.active??null},active),updatedAt=CURRENT_TIMESTAMP(3) WHERE id=${id}`);const item=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,name,description,active,createdAt,updatedAt FROM Skill WHERE id=${id}`))[0];await audit(request,'SKILL_UPDATED','Skill',id,existing,item);return {data:{...item,active:Boolean(item.active)}};});
  app.get('/api/v1/employees/:id/capabilities',async(request,reply)=>{const employeeId=z.coerce.number().int().positive().parse((request.params as any).id);const employee=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,code,name,department FROM Employee WHERE id=${employeeId} LIMIT 1`))[0];if(!employee)return reply.notFound('Employee not found');const role=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT r.id,r.name,r.description,r.active FROM EmployeeRoleAssignment a JOIN EmployeeRole r ON r.id=a.roleId WHERE a.employeeId=${employeeId} LIMIT 1`))[0]??null;const skills=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT s.id,s.name,s.description,s.active,es.level FROM EmployeeSkill es JOIN Skill s ON s.id=es.skillId WHERE es.employeeId=${employeeId} ORDER BY s.name ASC`);return {data:{employee,role:role?{...role,active:Boolean(role.active)}:null,skills:skills.map(skill=>({...skill,active:Boolean(skill.active),level:Number(skill.level)}))}};});
  app.put('/api/v1/employees/:id/capabilities',async(request,reply)=>{const employeeId=z.coerce.number().int().positive().parse((request.params as any).id);const input=capabilitySchema.parse(request.body);const employee=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id FROM Employee WHERE id=${employeeId} LIMIT 1`))[0];if(!employee)return reply.notFound('Employee not found');if(input.roleId!==undefined&&input.roleId!==null){const role=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,active FROM EmployeeRole WHERE id=${input.roleId} LIMIT 1`))[0];if(!role)return reply.badRequest('Employee role not found');if(!Boolean(role.active))return reply.badRequest('Inactive employee role cannot be assigned');}const skillIds=[...new Set(input.skills.map(skill=>skill.skillId))];if(skillIds.length){const valid=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,active FROM Skill WHERE id IN (${Prisma.join(skillIds)})`);if(valid.length!==skillIds.length)return reply.badRequest('One or more skills were not found');if(valid.some(skill=>!Boolean(skill.active)))return reply.badRequest('Inactive skill cannot be assigned');}const before=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT r.id roleId,r.name roleName FROM EmployeeRoleAssignment a JOIN EmployeeRole r ON r.id=a.roleId WHERE a.employeeId=${employeeId} LIMIT 1`);const beforeSkills=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT skillId,level FROM EmployeeSkill WHERE employeeId=${employeeId} ORDER BY skillId`);const data=await prisma.$transaction(async tx=>{if(input.roleId===null){await tx.$executeRaw(Prisma.sql`DELETE FROM EmployeeRoleAssignment WHERE employeeId=${employeeId}`);}else if(input.roleId!==undefined){await tx.$executeRaw(Prisma.sql`INSERT INTO EmployeeRoleAssignment (employeeId,roleId) VALUES (${employeeId},${input.roleId}) ON DUPLICATE KEY UPDATE roleId=VALUES(roleId)`);}await tx.$executeRaw(Prisma.sql`DELETE FROM EmployeeSkill WHERE employeeId=${employeeId}`);for(const skill of input.skills){await tx.$executeRaw(Prisma.sql`INSERT INTO EmployeeSkill (employeeId,skillId,level) VALUES (${employeeId},${skill.skillId},${skill.level})`);}const role=await tx.$queryRaw<any[]>(Prisma.sql`SELECT r.id,r.name,r.description,r.active FROM EmployeeRoleAssignment a JOIN EmployeeRole r ON r.id=a.roleId WHERE a.employeeId=${employeeId} LIMIT 1`);const skills=await tx.$queryRaw<any[]>(Prisma.sql`SELECT s.id,s.name,s.description,s.active,es.level FROM EmployeeSkill es JOIN Skill s ON s.id=es.skillId WHERE es.employeeId=${employeeId} ORDER BY s.name ASC`);return {role:role[0]??null,skills};});await audit(request,'EMPLOYEE_CAPABILITIES_UPDATED','Employee',employeeId,{role:before[0]??null,skills:beforeSkills},{role:data.role,skills:data.skills});return {data:{role:data.role?{...data.role,active:Boolean(data.role.active)}:null,skills:data.skills.map(skill=>({...skill,active:Boolean(skill.active),level:Number(skill.level)}))}};});
}
