import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { canTransition, jobTransitions } from '../workflow/workflow.rules.js';

function actorId(request:FastifyRequest){const id=Number((request.user as {sub?:string}).sub);return Number.isInteger(id)&&id>0?id:null;}
async function audit(request:FastifyRequest,action:string,entityId:number,before:unknown,after:unknown){await prisma.auditLog.create({data:{userId:actorId(request),action,entity:'Job',entityId:String(entityId),beforeJson:before as any,afterJson:after as any}});}
function serializeAudit(entry:any){return {...entry,id:typeof entry.id==='bigint'?entry.id.toString():entry.id};}

const createSchema = z.object({ number:z.string().min(2).max(50), projectId:z.coerce.number().int().positive(), serviceId:z.coerce.number().int().positive().optional(), title:z.string().min(2).max(200), description:z.string().max(5000).optional(), priority:z.string().max(30).optional(), startDate:z.coerce.date().optional(), dueDate:z.coerce.date().optional(), status:z.enum(['DRAFT','READY','IN_PROGRESS','BLOCKED','REVIEW','COMPLETED','CANCELLED']).optional(), assignmentType:z.enum(['INTERNAL','OUTSOURCED','MIXED']).optional(), revenue:z.coerce.number().nonnegative().default(0), estimatedMaterial:z.coerce.number().nonnegative().default(0), estimatedLabour:z.coerce.number().nonnegative().default(0), estimatedOutsource:z.coerce.number().nonnegative().default(0), estimatedExpense:z.coerce.number().nonnegative().default(0) });
const assignmentSchema = z.object({employeeId:z.coerce.number().int().positive().optional(),vendorId:z.coerce.number().int().positive().optional(),estimatedHours:z.coerce.number().nonnegative().optional(),agreedCost:z.coerce.number().nonnegative().optional(),startDate:z.coerce.date().optional(),dueDate:z.coerce.date().optional()}).refine(v=>!!v.employeeId||!!v.vendorId,'Employee or vendor is required').refine(v=>!(v.employeeId&&v.vendorId),'Choose either an employee or a vendor');
const requirementSchema = z.object({materialId:z.coerce.number().int().positive(),requiredQty:z.coerce.number().positive(),reservedQty:z.coerce.number().nonnegative().optional()});
const statusSchema = z.object({status:z.enum(['DRAFT','READY','IN_PROGRESS','BLOCKED','REVIEW','COMPLETED','CANCELLED'])});
const movementSchema = z.object({materialId:z.coerce.number().int().positive(),warehouseId:z.coerce.number().int().positive(),type:z.enum(['ISSUE','RETURN','WASTE']),quantity:z.coerce.number().positive(),unitCost:z.coerce.number().nonnegative().optional(),reference:z.string().max(100).optional()});
const timeSchema = z.object({employeeId:z.coerce.number().int().positive(),taskId:z.coerce.number().int().positive().optional(),workDate:z.coerce.date(),startTime:z.coerce.date().optional(),endTime:z.coerce.date().optional(),hours:z.coerce.number().positive(),billable:z.coerce.boolean().default(false),notes:z.string().max(2000).optional()});

export async function jobsRoutes(app:FastifyInstance){
  app.get('/api/v1/jobs',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),projectId:z.coerce.number().int().positive().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const where={project:{is:{}},...(q.status?{status:q.status as any}:{}),...(q.projectId?{projectId:q.projectId}:{}),...(q.search?{OR:[{number:{contains:q.search}},{title:{contains:q.search}}]}:{})};const [items,total]=await Promise.all([prisma.job.findMany({where,include:{project:{include:{client:true}},service:true,assignments:{include:{employee:true,vendor:true}},tasks:true},orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.job.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.get('/api/v1/jobs/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const item=await prisma.job.findFirst({where:{id,project:{is:{}}},include:{project:{include:{client:true}},service:true,tasks:{include:{employee:true}},assignments:{include:{employee:true,vendor:true}},materialRequirements:{include:{material:true}},outsourceOrders:{include:{vendor:true}},expenses:{include:{category:true}},timeEntries:{include:{employee:true,task:true}},installations:true,stockMovements:{include:{material:true,warehouse:true}}}});if(!item)return reply.notFound('Job not found');return {data:item};});
  app.get('/api/v1/jobs/:id/activity',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const job=await prisma.job.findFirst({where:{id,project:{is:{}}},select:{id:true}});if(!job)return reply.notFound('Job not found');const data=await prisma.auditLog.findMany({where:{entity:'Job',entityId:String(id)},include:{user:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:'desc'},take:200});return {data:data.map(serializeAudit)};});
  app.post('/api/v1/jobs',async(request,reply)=>{const input=createSchema.parse(request.body);const project=await prisma.project.findUnique({where:{id:input.projectId}});if(!project)return reply.badRequest('Project not found');const item=await prisma.job.create({data:input,include:{project:{include:{client:true}},service:true}});await audit(request,'CREATED',item.id,null,{status:item.status,title:item.title,projectId:item.projectId});return reply.code(201).send({data:item});});
  app.patch('/api/v1/jobs/:id/status',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=statusSchema.parse(request.body);const existing=await prisma.job.findFirst({where:{id,project:{is:{}}},include:{tasks:{select:{status:true}}}});if(!existing)return reply.notFound('Job not found');if(!canTransition(jobTransitions,existing.status,input.status))return reply.badRequest(`Invalid job transition: ${existing.status} -> ${input.status}`);if(input.status==='COMPLETED'){const openTasks=existing.tasks.filter((task)=>!['COMPLETED','CANCELLED'].includes(task.status));if(openTasks.length>0)return reply.badRequest('Job cannot be completed while tasks are still open');}const item=await prisma.$transaction(async tx=>{const updated=await tx.job.update({where:{id},data:{status:input.status},include:{project:true,service:true}});await tx.auditLog.create({data:{userId:actorId(request),action:'STATUS_CHANGED',entity:'Job',entityId:String(id),beforeJson:{status:existing.status},afterJson:{status:updated.status}}});return updated;});return {data:item};});
  app.post('/api/v1/jobs/:id/assignments',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=assignmentSchema.parse(request.body);const job=await prisma.job.findFirst({where:{id,project:{is:{}}}});if(!job)return reply.notFound('Job not found');if(input.employeeId){const e=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!e)return reply.badRequest('Employee not found');}if(input.vendorId){const v=await prisma.vendor.findUnique({where:{id:input.vendorId}});if(!v)return reply.badRequest('Vendor not found');}const item=await prisma.jobAssignment.create({data:{jobId:id,...input},include:{employee:true,vendor:true}});await audit(request,'ASSIGNMENT_ADDED',id,null,{assignmentId:item.id,employeeId:item.employeeId,vendorId:item.vendorId});return reply.code(201).send({data:item});});
  app.post('/api/v1/jobs/:id/material-requirements',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=requirementSchema.parse(request.body);const material=await prisma.material.findUnique({where:{id:input.materialId}});if(!material)return reply.badRequest('Material not found');const job=await prisma.job.findFirst({where:{id,project:{is:{}}}});if(!job)return reply.notFound('Job not found');const item=await prisma.materialRequirement.create({data:{jobId:id,...input},include:{material:true}});await audit(request,'MATERIAL_REQUIREMENT_ADDED',id,null,{requirementId:item.id,materialId:item.materialId,requiredQty:Number(item.requiredQty)});return reply.code(201).send({data:item});});
  app.post('/api/v1/jobs/:id/stock-movements',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=movementSchema.parse(request.body);const result=await prisma.$transaction(async tx=>{const job=await tx.job.findFirst({where:{id,project:{is:{}}}});if(!job)throw app.httpErrors.notFound('Job not found');const material=await tx.material.findUnique({where:{id:input.materialId}});if(!material)throw app.httpErrors.notFound('Material not found');const warehouse=await tx.warehouse.findUnique({where:{id:input.warehouseId}});if(!warehouse)throw app.httpErrors.notFound('Warehouse not found');if(input.type==='ISSUE'){const movements=await tx.stockMovement.findMany({where:{materialId:input.materialId,warehouseId:input.warehouseId}});const onHand=movements.reduce((sum,m)=>{const q=Number(m.quantity);if(['ISSUE','WASTE'].includes(m.type))return sum-q;if(m.type==='TRANSFER')return sum;return sum+q;},0);if(onHand<input.quantity)throw app.httpErrors.badRequest(`Insufficient stock. Available: ${onHand.toFixed(3)}`);}const movement=await tx.stockMovement.create({data:{jobId:id,projectId:job.projectId,materialId:input.materialId,warehouseId:input.warehouseId,type:input.type,quantity:input.quantity,unitCost:input.unitCost??Number(material.standardCost),reference:input.reference},include:{material:true,warehouse:true}});await tx.auditLog.create({data:{userId:actorId(request),action:'STOCK_MOVEMENT_ADDED',entity:'Job',entityId:String(id),beforeJson:null,afterJson:{movementId:movement.id,type:movement.type,quantity:Number(movement.quantity),materialId:movement.materialId,warehouseId:movement.warehouseId}}});return movement;});return reply.code(201).send({data:result});});
  app.post('/api/v1/jobs/:id/time-entries',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=timeSchema.parse(request.body);const job=await prisma.job.findFirst({where:{id,project:{is:{}}}});if(!job)return reply.notFound('Job not found');const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');if(input.taskId){const task=await prisma.task.findUnique({where:{id:input.taskId}});if(!task||task.jobId!==id)return reply.badRequest('Task does not belong to this job');}const item=await prisma.timeEntry.create({data:{jobId:id,projectId:job.projectId,...input},include:{employee:true,task:true}});await audit(request,'TIME_ENTRY_ADDED',id,null,{timeEntryId:item.id,employeeId:item.employeeId,hours:Number(item.hours),taskId:item.taskId});return reply.code(201).send({data:item});});
}
