CREATE TABLE IF NOT EXISTS TaxSetting (
  id INT NOT NULL DEFAULT 1,
  name VARCHAR(150) NOT NULL,
  rate DECIMAL(6,3) NOT NULL,
  inclusive BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PaymentMethodSetting (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sortOrder INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY PaymentMethodSetting_code_key (code),
  UNIQUE KEY PaymentMethodSetting_name_key (name)
);

CREATE TABLE IF NOT EXISTS UnitOfMeasure (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(30) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  UNIQUE KEY UnitOfMeasure_code_key (code),
  UNIQUE KEY UnitOfMeasure_name_key (name)
);
