import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, useLocation, useParams } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowUpRight, Menu, X, MessageCircle, Phone, Mail, MapPin, ChevronRight, Sparkles, Factory, PenTool, ShieldCheck, Zap, Truck, Check } from 'lucide-react';
import './styles.css';

const ASSET='/src/assets/';
const LOGO='/brand/kandy-ads-logo.svg';
const portfolio=[
 ['Casting Signs','Signage','Screenshot 2026-08-30 142854.png'],['Uncommon Signs','Signage','Screenshot 2026-08-30 142840.png'],['Cladding & Facades','Retail Branding','Screenshot 2026-08-30 142816.png'],['Vehicle Branding','Vehicle Branding','Screenshot 2026-08-30 142803.png'],['LED Road Sign Boards','Signage','Screenshot 2026-08-30 142751.png'],['Sunboard Panels','Print & Displays','Screenshot 2026-08-30 142739.png'],['Promotional Items','Promotional','Screenshot 2026-08-30 142729.png'],['X Stands','Events','Screenshot 2026-08-30 142720.png'],['Neon Sign Boards','Signage','Screenshot 2026-08-30 142708.png'],['Stickers','Print & Displays','Screenshot 2026-08-30 142702.png'],['Exhibition Stalls','Events','Screenshot 2026-08-30 142653.png'],['Stainless Steel Sign Boards','Signage','Screenshot 2026-08-30 142607.png'],['Stand Boards','Displays','Screenshot 2026-08-30 142556.png'],['Dealer Boards','Retail Branding','Screenshot 2026-08-30 142548.png'],['Fiber Letter Sign Boards','Signage','Screenshot 2026-08-30 142541.png'],['Pylon Sign Boards','Outdoor Advertising','Screenshot 2026-08-30 142530.png'],['Export Sign Boards','Signage','Screenshot 2026-08-30 142523.png'],['LED Sign Boards','Signage','Screenshot 2026-08-30 142508.png'],['Flex Hoardings','Outdoor Advertising','Screenshot 2026-08-30 142458.png']
];
const services=[
 {slug:'signage',title:'Signage & Signboards',kicker:'BE SEEN. BE REMEMBERED.',desc:'Indoor, outdoor, LED, neon, stainless steel, channel letters, pylon boards and custom sign systems built for visibility.',icon:Zap},
 {slug:'vehicle-branding',title:'Vehicle Branding',kicker:'TURN EVERY JOURNEY INTO MEDIA.',desc:'High-impact vehicle graphics and wraps that turn fleets into moving brand touchpoints.',icon:Truck},
 {slug:'outdoor-advertising',title:'Outdoor Advertising',kicker:'OWN THE STREET.',desc:'Hoardings, flex displays, road signs, dealer boards and physical campaigns designed for local reach.',icon:MapPin},
 {slug:'printing',title:'Digital Printing & Displays',kicker:'FROM ARTWORK TO FINISH.',desc:'Large-format printing, stickers, sunboard panels, point-of-sale graphics and display systems.',icon:PenTool},
 {slug:'retail-branding',title:'Retail & Commercial Branding',kicker:'MAKE YOUR SPACE YOUR BRAND.',desc:'Shopfronts, wall graphics, cladding, internal branding and wayfinding designed as one experience.',icon:Factory},
 {slug:'events',title:'Exhibitions & Promotional',kicker:'SHOW UP STRONG.',desc:'Exhibition stalls, X stands and promotional items that make launches and events memorable.',icon:Sparkles}
];
const industries=['Retail & Supermarkets','Banking & Finance','Hotels & Tourism','Education','Healthcare','Food & Beverage','Real Estate','Corporate'];
const brandExamples=[
 {name:'DSI'},
 {name:'NinetyNine'},
 {name:'KFC',logo:'https://cdn.simpleicons.org/kfc'},
 {name:'Pepsi',logo:'https://cdn.simpleicons.org/pepsi'},
 {name:'Puma',logo:'https://cdn.simpleicons.org/puma'},
 {name:'Fancy Point'},
 {name:'Arpico'},
 {name:'Ceylon Brands'}
];
const reasons=[
 ['ONE TEAM','Design, production and installation coordinated through one accountable team.'],
 ['BUILT TO LAST','Materials, finishing and fabrication selected for demanding real-world conditions.'],
 ['SITE-FIRST THINKING','Visibility, scale, placement, access and installation are considered before production.'],
 ['BUSINESS-MINDED','Every deliverable is treated as part of your brand experience, not just an object.'],
 ['CLEAR PROCESS','A structured journey from brief and concept through production, installation and handover.'],
 ['LOCAL + RESPONSIVE','Kandy-based support with practical communication and on-site coordination.']
];

function useScrollTop(){const {pathname}=useLocation();React.useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});},[pathname]);}
function App(){useScrollTop();return <><Navbar/><PageTransition><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<ServiceDetail/>}/><Route path="/projects" element={<Projects/>}/><Route path="/industries" element={<Industries/>}/><Route path="/process" element={<Process/>}/><Route path="/contact" element={<Contact/>}/></Routes></PageTransition><Footer/><FloatingActions/></>}
function PageTransition({children}){const location=useLocation();return <AnimatePresence mode="wait"><motion.main key={location.pathname} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.28}}>{children}</motion.main></AnimatePresence>}
function Navbar(){const [open,setOpen]=React.useState(false);const nav=[['About','/about'],['Services','/services'],['Projects','/projects'],['Industries','/industries'],['Process','/process']];return <header className="nav"><div className="nav-inner"><Link to="/" className="brand" onClick={()=>setOpen(false)}><img src={LOGO} alt="Kandy Ads"/><span>KANDY<span>ADS</span></span></Link><nav className={open?'open':''}>{nav.map(([x,u])=><Link key={u} to={u} onClick={()=>setOpen(false)}>{x}</Link>)}<Link to="/contact" className="nav-cta" onClick={()=>setOpen(false)}>Get a Quote <ArrowUpRight size={16}/></Link></nav><button className="menu" onClick={()=>setOpen(v=>!v)} aria-label={open?'Close menu':'Open menu'}>{open?<X/>:<Menu/>}</button></div></header>}
function FloatingActions(){return <div className="float-actions"><a href="https://wa.me/94770000000" aria-label="WhatsApp"><MessageCircle/></a><Link to="/contact" aria-label="Request a quote"><ArrowUpRight/></Link></div>}
function Reveal({children,className='',delay=0}){return <motion.div className={className} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.52,delay,ease:'easeOut'}}>{children}</motion.div>}
function Hero(){return <section className="hero"><div className="hero-noise"/><div className="container hero-layout"><div className="hero-copy"><div className="eyebrow"><span/>KANDY • SRI LANKA</div><h1>Visibility that makes your <em>business matter.</em></h1></div><div className="hero-side"><p className="hero-side-lead">Kandy Ads is a full-service advertising and brand visibility partner. We design, produce and install the physical touchpoints that make businesses easier to notice, trust and remember.</p><div className="hero-actions"><Link to="/contact" className="btn primary">Start a project <ArrowUpRight/></Link><Link to="/projects" className="btn ghost">Explore our work <ChevronRight/></Link></div><div className="hero-side-meta"><span>01</span><div>Strategy <i/> Design <i/> Production <i/> Installation</div></div></div></div><div className="hero-bottom container"><span>Scroll to explore</span><div/></div></section>}
function Home(){return <><Hero/><section className="belief container"><div className="section-tag">WHY KANDY ADS</div><div className="belief-grid"><Reveal><h2>Not just advertising.<br/><span>A complete visibility partner.</span></h2></Reveal><Reveal delay={.08}><p>When a customer sees your sign, enters your shop, passes your vehicle or discovers your campaign, every detail contributes to how they judge your business. We bring those details together.</p><Link to="/about" className="text-link">Why businesses choose us <ArrowUpRight/></Link></Reveal></div></section><CapabilitySection/><IntegratedSection/><WhySection/><Partners/><IndustryBand/><ProcessPreview/><FinalCTA/></>}
function CapabilitySection(){return <section className="capabilities"><div className="container"><div className="cap-head"><div><div className="section-tag">WHAT WE CAN DO</div><h2>Everything your brand needs to <span>show up strong.</span></h2></div><p>Instead of coordinating multiple vendors, bring your visibility requirements to one experienced team — from a single signboard to a wider retail or outdoor rollout.</p></div><div className="cap-grid">{services.map((s,i)=>{const Icon=s.icon;return <Reveal key={s.slug} delay={i*.03}><Link to={'/services/'+s.slug} className="cap-card"><div className="cap-top"><span>0{i+1}</span><Icon/></div><small>{s.kicker}</small><h3>{s.title}</h3><p>{s.desc}</p><span className="card-arrow"><ArrowUpRight/></span></Link></Reveal>})}</div></div></section>}
function IntegratedSection(){const blocks=[['01','ONE BRIEF','Start with your business objective, location and customer experience.'],['02','ONE CREATIVE DIRECTION','Design, materials and formats are considered as one system.'],['03','ONE PRODUCTION FLOW','Printing, fabrication and finishing stay connected to the agreed direction.'],['04','ONE FINISHED RESULT','Installation and handover complete the journey with one accountable team.']];return <section className="integrated-section"><div className="container"><div className="integrated-intro"><div><div className="section-tag">WHY ONE PARTNER</div><h2>One brief. One team.<br/><span>One accountable result.</span></h2></div><p>Good brand visibility should feel coordinated. We connect the creative idea with what can actually be produced, installed and maintained on site.</p></div><div className="integrated-grid">{blocks.map((b,i)=><Reveal key={b[0]} delay={i*.04}><div className="integrated-card"><span>{b[0]}</span><h3>{b[1]}</h3><p>{b[2]}</p><div className="integrated-line"/></div></Reveal>)}</div></div></section>}
function WhySection(){return <section className="why-section"><div className="container"><div className="why-intro"><div><div className="section-tag">THE KANDY ADS DIFFERENCE</div><h2>Confidence comes from <span>knowing who's handling it.</span></h2></div><p>From the first conversation to the final installation, we keep the work connected. That means fewer handovers, fewer surprises and a finished result that feels intentional.</p></div><div className="reason-grid">{reasons.map((r,i)=><Reveal key={r[0]} delay={i*.03}><div className="reason"><span>0{i+1}</span><Check/><h3>{r[0]}</h3><p>{r[1]}</p></div></Reveal>)}</div></div></section>}
function Partners(){return <section className="partners container"><div className="partners-head"><div><div className="section-tag">BRANDS IN OUR WORK</div><h2>Built around real businesses.</h2></div><p>Selected brands and business environments visible in the Kandy Ads portfolio. This section is intentionally labelled as portfolio evidence until the confirmed client-partner list is finalized.</p></div><div className="partner-strip">{brandExamples.map((b,i)=><div key={b.name} className="partner-item"><span>0{i+1}</span>{b.logo?<img src={b.logo} alt={b.name}/>:<b>{b.name}</b>}</div>)}</div><div className="partners-note">For the final production website, confirmed client and partner logos can replace the portfolio references shown here.</div></section>}
function IndustryBand(){return <section className="industry-band"><div className="container"><div><div className="section-tag light-tag">BUILT FOR BUSINESS</div><h2>Different industries.<br/><strong>One standard of execution.</strong></h2><p>From retail and hospitality to healthcare, education, finance and corporate spaces, we adapt the solution to the way your customers see and use your business.</p><Link to="/industries" className="btn light-btn">Explore industries <ArrowUpRight/></Link></div><div className="industry-list">{industries.map((x,i)=><Link key={x} to="/industries"><span>0{i+1}</span>{x}<ArrowUpRight/></Link>)}</div></div></section>}
function ProcessPreview(){const steps=[['01','DISCOVER','Understand the business, site, audience and objective.'],['02','DESIGN','Turn the brief into a clear visual and production direction.'],['03','PRODUCE','Print, fabricate, finish and quality-check every component.'],['04','INSTALL','Coordinate the site, install professionally and hand over ready.'],['05','SUPPORT','Stay available for the next rollout, refresh or new location.']];return <section className="process-preview"><div className="container"><div className="strip-head"><div><div className="section-tag light-tag">OUR METHOD</div><h2>From idea to installation — <span>without losing the thread.</span></h2><p className="process-lead">A clear five-stage workflow keeps decisions visible, responsibilities clear and the final result aligned with the original brief.</p></div><Link to="/process" className="text-link light-link">See our process <ArrowUpRight/></Link></div><div className="process-rail">{steps.map((s,i)=><Reveal key={s[0]} delay={i*.04}><div className="process-step"><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p><span className="step-dot"/></div></Reveal>)}</div></div></section>}
function FinalCTA(){return <section className="final-cta-wrap"><div className="container"><section className="lead-cta"><div className="lead-cta-mark"><img src={LOGO} alt=""/></div><div><div className="section-tag light-tag">LET'S BUILD YOUR NEXT TOUCHPOINT</div><h2>Tell us what your business needs to be seen.</h2><p>Share the location, idea, campaign or problem. We'll help turn it into a practical advertising solution.</p></div><Link to="/contact" className="btn light-btn">Request a quote <ArrowUpRight/></Link></section></div></section>}
function SectionHero({kicker,title,text}){return <section className="section-hero container"><div className="section-tag">{kicker}</div><h1>{title}</h1><p>{text}</p></section>}
function Page({children}){return <>{children}</>}
function About(){return <Page><SectionHero kicker="ABOUT KANDY ADS" title="A local advertising partner built around execution." text="Kandy Ads is a Kandy-based advertising agency focused on helping businesses grow through creative, practical and high-quality brand visibility solutions."/><section className="split container"><div className="big-copy">We don't stop at the idea.<br/><span>We make it real.</span></div><div className="rich-copy"><p>Our work spans signage, vehicle branding, outdoor advertising, digital printing, retail branding, exhibitions and promotional displays.</p><p>That means clients can work with one team from concept and design through production and installation.</p><div className="mini-points"><div><ShieldCheck/><b>Quality-led</b><span>Careful materials and finishing.</span></div><div><Factory/><b>Production capable</b><span>Made for real-world spaces.</span></div><div><Zap/><b>Responsive</b><span>Practical communication.</span></div></div></div></section><section className="about-statement"><div className="container"><div className="statement-number">K / 01</div><h2>Advertising should not only look good in a presentation. <span>It should work in the physical world.</span></h2></div></section><ImageFeature image="Screenshot 2026-08-30 142840.png" title="Built for the places people actually see." text="Our portfolio includes storefronts, commercial interiors, road-facing signs, vehicle branding and full display systems."/><Partners/><FinalCTA/></Page>}
function ImageFeature({image,title,text}){return <section className="image-feature container"><div><img src={ASSET+image} alt={title}/></div><div><div className="section-tag">THE RESULT</div><h2>{title}</h2><p>{text}</p></div></section>}
function Services(){return <Page><SectionHero kicker="SERVICES" title="Every surface is a chance to be remembered." text="Choose one service or combine several. We make the full journey easier by connecting creative thinking with production and installation."/><section className="container service-list">{services.map((s,i)=>{const Icon=s.icon;return <Link className="service-row" to={'/services/'+s.slug} key={s.slug}><span>0{i+1}</span><Icon/><div><small>{s.kicker}</small><h2>{s.title}</h2><p>{s.desc}</p></div><ArrowUpRight/></Link>})}</section><FinalCTA/></Page>}
function ServiceDetail(){const {slug}=useParams();const s=services.find(x=>x.slug===slug)||services[0];const category={signage:'Signage','vehicle-branding':'Vehicle Branding','outdoor-advertising':'Outdoor Advertising',printing:'Print & Displays','retail-branding':'Retail Branding',events:'Events'}[s.slug]||'Signage';const related=portfolio.filter(p=>p[1]===category).slice(0,4);return <Page><SectionHero kicker={'SERVICE / '+s.title.toUpperCase()} title={s.title} text={s.desc}/><section className="detail-hero container"><div className="detail-feature"><img src={ASSET+(related[0]?.[2]||portfolio[0][2])} alt={s.title}/></div><div className="detail-panel"><div className="section-tag">WHAT YOU GET</div><h2>Designed for visibility. Built for the real world.</h2><ul><li>Consultation and project briefing</li><li>Design direction and artwork support</li><li>Material and finish recommendations</li><li>Production / fabrication</li><li>Site coordination and installation</li></ul><Link to="/contact" className="btn primary">Discuss your project <ArrowUpRight/></Link></div></section><section className="container projects-strip" style={{paddingTop:80}}><div className="section-tag">RELATED WORK</div><h2>See how this category comes to life.</h2><div className="four-grid" style={{paddingTop:35}}>{related.map(p=><Link to="/projects" className="project-card" key={p[0]}><img src={ASSET+p[2]} alt={p[0]}/><div><span>{p[1]}</span><h3>{p[0]}</h3></div></Link>)}</div></section><FinalCTA/></Page>}
function Projects(){const [cat,setCat]=React.useState('All');const cats=['All','Signage','Vehicle Branding','Outdoor Advertising','Retail Branding','Print & Displays','Events','Displays','Promotional'];const filtered=cat==='All'?portfolio:portfolio.filter(p=>p[1]===cat);return <Page><SectionHero kicker="PROJECTS" title="Proof is the portfolio." text="A visual library of Kandy Ads work — signs, branding, displays, vehicles and physical brand experiences."/><div className="container filters">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="container project-grid">{filtered.map(p=><motion.div className="project-card" layout initial={{opacity:0}} animate={{opacity:1}} key={p[0]}><img src={ASSET+p[2]} alt={p[0]}/><div><span>{p[1]}</span><h3>{p[0]}</h3><p>Selected portfolio reference</p></div></motion.div>)}</div><FinalCTA/></Page>}
function Industries(){return <Page><SectionHero kicker="INDUSTRIES" title="Advertising that fits the way your business operates." text="Different industries need different visibility. We adapt the solution to the customer journey, location and practical needs of the sector."/><div className="container industry-grid">{industries.map((x,i)=><div key={x}><span>0{i+1}</span><h2>{x}</h2><p>Branding and advertising touchpoints tailored to the customer journey, location and practical needs of the sector.</p><Link to="/contact">Talk about your project <ArrowUpRight size={16}/></Link></div>)}</div><FinalCTA/></Page>}
function Process(){const steps=[['01','DISCOVER','Understand the business, site, audience and objective.'],['02','DESIGN','Turn the brief into a clear visual and production direction.'],['03','PRODUCE','Print, fabricate, finish and quality-check every component.'],['04','INSTALL','Coordinate the site, install professionally and hand over ready.'],['05','SUPPORT','Stay available for the next rollout, refresh or new location.']];return <Page><SectionHero kicker="PROCESS" title="A clear path from brief to installed reality." text="Good execution starts before production. Our process keeps strategy, design, fabrication and installation connected."/><div className="container timeline">{steps.map(s=><div key={s[0]}><span>{s[0]}</span><div><small>KANDY ADS METHOD</small><h2>{s[1]}</h2><p>{s[2]}</p></div></div>)}</div><FinalCTA/></Page>}
function Contact(){return <Page><SectionHero kicker="CONTACT" title="Let's build something people notice." text="Tell us what you are trying to achieve, where it needs to happen and what you already have. We'll help shape the next step."/><section className="container contact-grid"><div><div className="contact-card"><Phone/><span>CALL / WHATSAPP</span><h3>+94 77 000 0000</h3><p>For quick project discussions and site requirements.</p><a href="https://wa.me/94770000000">Start a WhatsApp conversation <ArrowUpRight size={15}/></a></div><div className="contact-card"><Mail/><span>EMAIL</span><h3>info@kandyads.lk</h3><p>Send your brief, artwork or quotation request.</p><a href="mailto:info@kandyads.lk">Send an email <ArrowUpRight size={15}/></a></div><div className="contact-card"><MapPin/><span>LOCATION</span><h3>Kandy, Sri Lanka</h3><p>Serving businesses across Kandy and beyond.</p></div></div><form className="quote-form" onSubmit={e=>e.preventDefault()}><label>NAME<input required placeholder="Your name"/></label><label>COMPANY<input placeholder="Company name"/></label><label>PHONE<input placeholder="Phone / WhatsApp"/></label><label>EMAIL<input type="email" placeholder="Email address"/></label><label>SERVICE<select defaultValue=""><option value="" disabled>Select a service</option>{services.map(s=><option key={s.slug}>{s.title}</option>)}</select></label><label>PROJECT LOCATION<input placeholder="Where will it be installed?"/></label><label>PROJECT DETAILS<textarea rows="6" placeholder="Tell us what you need..."/></label><button className="btn primary" type="submit">Send enquiry <ArrowUpRight/></button></form></section></Page>}
function Footer(){return <footer><div className="container footer-grid"><div><div className="footer-brand"><img src={LOGO} alt="Kandy Ads"/><span>KANDY ADS</span></div><p>Creative advertising, signage and physical brand visibility solutions from Kandy, Sri Lanka.</p></div><div><b>Explore</b><Link to="/about">About Kandy Ads</Link><Link to="/services">All services</Link><Link to="/projects">Projects</Link><Link to="/industries">Industries</Link><Link to="/process">Our process</Link><Link to="/contact">Contact</Link></div><div><b>Capabilities</b>{services.slice(0,4).map(s=><Link key={s.slug} to={'/services/'+s.slug}>{s.title}</Link>)}</div><div><b>Start a project</b><span>Kandy, Sri Lanka</span><a href="tel:+94770000000">+94 77 000 0000</a><a href="mailto:info@kandyads.lk">info@kandyads.lk</a><Link className="footer-cta" to="/contact">Request a quote <ArrowUpRight size={15}/></Link></div></div><div className="container foot-bottom"><span>© {new Date().getFullYear()} Kandy Ads. All rights reserved.</span><span>Advertising • Branding • Production</span></div></footer>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
