import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, useLocation, useParams } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowUpRight, Menu, X, MessageCircle, Phone, Mail, MapPin, ChevronRight, Sparkles, Factory, PenTool, ShieldCheck, Zap, Globe2 } from 'lucide-react';
import './styles.css';

const ASSET='/src/assets/';
const portfolio=[
 ['Casting Signs','Signage','Screenshot 2026-08-30 142854.png'],['Uncommon Signs','Signage','Screenshot 2026-08-30 142840.png'],['Cladding & Facades','Retail Branding','Screenshot 2026-08-30 142816.png'],['Vehicle Branding','Vehicle Branding','Screenshot 2026-08-30 142803.png'],['LED Road Sign Boards','Signage','Screenshot 2026-08-30 142751.png'],['Sunboard Panels','Print & Displays','Screenshot 2026-08-30 142739.png'],['Promotional Items','Promotional','Screenshot 2026-08-30 142729.png'],['X Stands','Events','Screenshot 2026-08-30 142720.png'],['Neon Sign Boards','Signage','Screenshot 2026-08-30 142708.png'],['Stickers','Print & Displays','Screenshot 2026-08-30 142702.png'],['Exhibition Stalls','Events','Screenshot 2026-08-30 142653.png'],['Stainless Steel Sign Boards','Signage','Screenshot 2026-08-30 142607.png'],['Stand Boards','Displays','Screenshot 2026-08-30 142556.png'],['Dealer Boards','Retail Branding','Screenshot 2026-08-30 142548.png'],['Fiber Letter Sign Boards','Signage','Screenshot 2026-08-30 142541.png'],['Pylon Sign Boards','Outdoor Advertising','Screenshot 2026-08-30 142530.png'],['Export Sign Boards','Signage','Screenshot 2026-08-30 142523.png'],['LED Sign Boards','Signage','Screenshot 2026-08-30 142508.png'],['Flex Hoardings','Outdoor Advertising','Screenshot 2026-08-30 142458.png']
]
const services=[
 {slug:'signage',title:'Signage & Signboards',kicker:'MAKE YOUR LOCATION WORK HARDER',desc:'Indoor, outdoor, LED, neon, stainless steel, channel letters, pylon boards and custom sign systems built for day-and-night visibility.',icon:Zap},
 {slug:'vehicle-branding',title:'Vehicle Branding',kicker:'TURN EVERY JOURNEY INTO MEDIA',desc:'High-impact vehicle graphics and wraps that transform everyday fleets into moving brand touchpoints.',icon:Globe2},
 {slug:'outdoor-advertising',title:'Outdoor Advertising',kicker:'BE SEEN WHERE PEOPLE MOVE',desc:'Hoardings, flex displays, road signs, dealer boards and strategic physical advertising for strong local visibility.',icon:MapPin},
 {slug:'printing',title:'Digital Printing & Displays',kicker:'FROM FILE TO FINISH',desc:'Large-format printing, stickers, sunboard panels, point-of-sale graphics and promotional displays.',icon:PenTool},
 {slug:'retail-branding',title:'Retail & Commercial Branding',kicker:'MAKE YOUR SPACE YOUR BRAND',desc:'Shopfronts, wall graphics, cladding, internal branding and wayfinding systems designed as one experience.',icon:Factory},
 {slug:'events',title:'Exhibitions & Promotional',kicker:'LOOK READY FOR THE SPOTLIGHT',desc:'Exhibition stalls, X stands and promotional items that make launches, expos and events more memorable.',icon:Sparkles}
];
const industries=['Retail & Supermarkets','Banking & Finance','Hotels & Tourism','Education','Healthcare','Food & Beverage','Real Estate','Corporate'];

function useScrollTop(){ const {pathname}=useLocation(); React.useEffect(()=>window.scrollTo(0,0),[pathname]); }
function App(){useScrollTop(); return <><Navbar/><PageTransition><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<ServiceDetail/>}/><Route path="/projects" element={<Projects/>}/><Route path="/industries" element={<Industries/>}/><Route path="/process" element={<Process/>}/><Route path="/contact" element={<Contact/>}/></Routes></PageTransition><Footer/><FloatingActions/></>}
function PageTransition({children}){return <AnimatePresence mode="wait"><motion.main key={useLocation().pathname} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.45,ease:'easeOut'}}>{children}</motion.main></AnimatePresence>}
function Navbar(){const [open,setOpen]=React.useState(false); const nav=[['About','/about'],['Services','/services'],['Projects','/projects'],['Industries','/industries'],['Process','/process']]; return <header className="nav"><div className="nav-inner"><Link to="/" className="brand" onClick={()=>setOpen(false)}><span className="brand-mark">K</span><span>KANDY<span>ADS</span></span></Link><nav className={open?'open':''}>{nav.map(([x,u])=><Link key={u} to={u} onClick={()=>setOpen(false)}>{x}</Link>)}<Link to="/contact" className="nav-cta" onClick={()=>setOpen(false)}>Get a Quote <ArrowUpRight size={16}/></Link></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="menu">{open?<X/>:<Menu/>}</button></div></header>}
function FloatingActions(){return <div className="float-actions"><a href="https://wa.me/94770000000" aria-label="WhatsApp"><MessageCircle/></a><Link to="/contact" aria-label="Quote"><ArrowUpRight/></Link></div>}
function Hero(){return <section className="hero"><div className="hero-grid"><div><div className="eyebrow"><span></span> KANDY • SRI LANKA</div><h1>Make your brand <em>impossible</em> to ignore.</h1><p className="lead">Creative advertising, signage and brand visibility solutions — designed, produced and installed by one team.</p><div className="hero-actions"><Link to="/contact" className="btn primary">Start a project <ArrowUpRight/></Link><Link to="/projects" className="btn ghost">See our work <ChevronRight/></Link></div><div className="hero-proof"><div><b>01</b><span>Creative<br/>direction</span></div><div><b>02</b><span>Production<br/>& fabrication</span></div><div><b>03</b><span>Professional<br/>installation</span></div></div></div><div className="hero-visual"><motion.div className="hero-card card-one" animate={{y:[0,-10,0],rotate:[-2,-1, -2]}} transition={{duration:5,repeat:Infinity,ease:'easeInOut'}}><img src={ASSET+'Screenshot 2026-08-30 142729.png'}/><span>LED SIGNAGE</span></motion.div><motion.div className="hero-card card-two" animate={{y:[0,12,0],rotate:[3,2,3]}} transition={{duration:6,repeat:Infinity,ease:'easeInOut'}}><img src={ASSET+'Screenshot 2026-08-30 142854.png'}/><span>VEHICLE BRANDING</span></motion.div><div className="hero-orb"></div></div></div><div className="scroll-cue">SCROLL <span></span></div></section>}
function Home(){return <><Hero/><SectionIntro eyebrow="WHAT WE DO" title="From first sketch to final installation." text="Kandy Ads helps businesses turn ideas into physical brand experiences — from a single signboard to full retail and outdoor campaigns."/><section className="services-preview"><div className="container service-grid">{services.map((s,i)=>{const Icon=s.icon;return <motion.div className="service-card" key={s.slug} whileHover={{y:-8}}><div className="service-number">0{i+1}</div><Icon/><h3>{s.title}</h3><p>{s.desc}</p><Link to={'/services/'+s.slug}>Explore <ArrowUpRight size={16}/></Link></motion.div>})}</div></section><ProjectsStrip/><section className="industry-band"><div className="container"><div><div className="eyebrow light"><span></span> BUILT FOR BUSINESS</div><h2>One brand. Every touchpoint.</h2><p>From retail counters to roadside visibility, we create a consistent brand presence wherever your customers meet you.</p><Link to="/industries" className="btn light-btn">Explore industries <ArrowUpRight/></Link></div><div className="industry-cloud">{industries.map((x,i)=><motion.div key={x} initial={{opacity:0,x:20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.05}}>{x}</motion.div>)}</div></div></section><ProcessPreview/><CTA/></>}
function SectionIntro({eyebrow,title,text}){return <section className="section-intro container"><div className="eyebrow"><span></span>{eyebrow}</div><h2>{title}</h2><p>{text}</p></section>}
function ProjectsStrip(){return <section className="projects-strip container"><div className="strip-head"><div><div className="eyebrow"><span></span> SELECTED WORK</div><h2>Real work. Real places.</h2></div><Link to="/projects" className="text-link">View all projects <ArrowUpRight size={17}/></Link></div><div className="masonry">{portfolio.slice(0,6).map((p,i)=><Link to="/projects" className={'masonry-item mi'+i} key={p[0]}><img src={ASSET+p[2]}/><div><span>{p[1]}</span><h3>{p[0]}</h3><ArrowUpRight/></div></Link>)}</div></section>}
function ProcessPreview(){const steps=[['DISCOVER','Understand the business, location, audience and objective.'],['DESIGN','Develop a visual direction that fits your brand and space.'],['PRODUCE','Fabricate, print, finish and prepare with attention to detail.'],['INSTALL','Coordinate site work and install professionally.']];return <section className="process-preview"><div className="container"><div className="strip-head"><div><div className="eyebrow light"><span></span> OUR METHOD</div><h2>A smoother way to build visibility.</h2></div><Link to="/process" className="text-link light-link">See our process <ArrowUpRight size={17}/></Link></div><div className="process-grid">{steps.map((s,i)=><motion.div key={s[0]} whileInView={{opacity:1,y:0}} initial={{opacity:0,y:20}} viewport={{once:true}} transition={{delay:i*.08}}><b>0{i+1}</b><h3>{s[0]}</h3><p>{s[1]}</p></motion.div>)}</div></div></section>}
function CTA(){return <section className="cta container"><div className="cta-inner"><div><div className="eyebrow light"><span></span> START SOMETHING STRONG</div><h2>Ready to make your brand stand out?</h2></div><Link to="/contact" className="btn light-btn">Request a quote <ArrowUpRight/></Link></div></section>}
function About(){return <Page><SectionHero kicker="ABOUT KANDY ADS" title="A local advertising partner built around execution." text="Kandy Ads is a Kandy-based advertising agency focused on helping businesses grow through creative, practical and high-quality brand visibility solutions."/><section className="split container"><div className="big-copy">We don't stop at the idea.<br/><span>We make it real.</span></div><div className="rich-copy"><p>Our work spans signage, vehicle branding, outdoor advertising, digital printing, retail branding, exhibitions and promotional displays.</p><p>That means clients can work with one team from concept and design through production and installation.</p><div className="mini-points"><div><ShieldCheck/><b>Quality-led</b><span>Careful materials and finishing.</span></div><div><Factory/><b>Production capable</b><span>Made for real-world spaces.</span></div><div><Zap/><b>Responsive</b><span>Practical communication.</span></div></div></div></section><ImageFeature image="Screenshot 2026-08-30 142840.png" title="Built for the places people actually see." text="Our portfolio includes storefronts, commercial interiors, road-facing signs, vehicle branding and full display systems."/><section className="vision container"><div><div className="eyebrow"><span></span> OUR VISION</div><h2>Help good businesses become more visible.</h2></div><div><p>We believe advertising should not just look good in a presentation. It should work in the physical world — at the roadside, on the storefront, inside the shop and on the move.</p><p>That principle shapes the new Kandy Ads experience.</p></div></section><CTA/></Page>}
function Services(){return <Page><SectionHero kicker="SERVICES" title="Every surface is a chance to be remembered." text="Choose one service or combine several. Our website structure makes it easier for businesses to find the exact advertising solution they need."/><section className="container service-list">{services.map((s,i)=>{const Icon=s.icon;return <Link className="service-row" to={'/services/'+s.slug} key={s.slug}><span>0{i+1}</span><Icon/><div><small>{s.kicker}</small><h2>{s.title}</h2><p>{s.desc}</p></div><ArrowUpRight/></Link>})}</section><CTA/></Page>}
function ServiceDetail(){const {slug}=useParams(); const s=services.find(x=>x.slug===slug)||services[0]; const related=portfolio.filter(p=>p[1]===({signage:'Signage','vehicle-branding':'Vehicle Branding','outdoor-advertising':'Outdoor Advertising','printing':'Print & Displays','retail-branding':'Retail Branding','events':'Events'}[s.slug]||'Signage')).slice(0,4); return <Page><SectionHero kicker={'SERVICE / '+s.title.toUpperCase()} title={s.title} text={s.desc}/><section className="detail-hero container"><div className="detail-feature"><img src={ASSET+(related[0]?.[2]||portfolio[0][2])}/></div><div className="detail-panel"><div className="eyebrow"><span></span> WHAT YOU GET</div><h2>Designed for visibility. Built for the real world.</h2><ul><li>Consultation and project briefing</li><li>Design direction and artwork support</li><li>Material and finish recommendations</li><li>Production / fabrication</li><li>Site coordination and installation</li></ul><Link to="/contact" className="btn primary">Discuss your project <ArrowUpRight/></Link></div></section><SectionIntro eyebrow="RELATED WORK" title="See how this category comes to life." text="Selected examples from the supplied Kandy Ads portfolio. The full website can expand this into searchable case studies."/><div className="container four-grid">{related.map(p=><Link to="/projects" className="project-card" key={p[0]}><img src={ASSET+p[2]}/><div><span>{p[1]}</span><h3>{p[0]}</h3></div></Link>)}</div><CTA/></Page>}
function Projects(){const [cat,setCat]=React.useState('All'); const cats=['All','Signage','Vehicle Branding','Outdoor Advertising','Retail Branding','Print & Displays','Events','Displays','Promotional']; const filtered=cat==='All'?portfolio:portfolio.filter(p=>p[1]===cat); return <Page><SectionHero kicker="PROJECTS" title="Proof is the portfolio." text="A visual library of Kandy Ads work — signs, branding, displays, vehicles and physical brand experiences."/><div className="container filters">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="container project-grid">{filtered.map((p,i)=><motion.div className="project-card" layout initial={{opacity:0}} animate={{opacity:1}} key={p[0]}><img src={ASSET+p[2]}/><div><span>{p[1]}</span><h3>{p[0]}</h3><p>Selected portfolio reference</p></div></motion.div>)}</div><CTA/></Page>}
function Industries(){return <Page><SectionHero kicker="INDUSTRIES" title="Advertising that fits the way your business operates." text="Different industries need different visibility. The website can later evolve into dedicated landing pages for each major client segment."/><div className="container industry-grid">{industries.map((x,i)=><motion.div key={x} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}}><span>0{i+1}</span><h2>{x}</h2><p>Branding and advertising touchpoints tailored to the customer journey, location and practical needs of the sector.</p><Link to="/contact">Talk about your project <ArrowUpRight size={16}/></Link></motion.div>)}</div><CTA/></Page>}
function Process(){return <Page><SectionHero kicker="PROCESS" title="A clear process from idea to installation." text="The goal is simple: reduce friction for the client and keep quality visible at every stage."/><div className="container timeline">{[['01','Discover','We understand the business, space, audience, brand and objective.'],['02','Plan','We recommend the right format, materials, dimensions and production approach.'],['03','Design','We create the visual direction and align the artwork with the physical application.'],['04','Produce','Printing, fabrication and finishing happen with a focus on consistency and durability.'],['05','Install','Site coordination, installation and final checks bring the project to life.']].map((x,i)=><motion.div key={x[0]} initial={{opacity:0,x:i%2?-25:25}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><span>{x[0]}</span><div><small>STEP {x[0]}</small><h2>{x[1]}</h2><p>{x[2]}</p></div></motion.div>)}</div><CTA/></Page>}
function Contact(){return <Page><SectionHero kicker="START A PROJECT" title="Tell us what needs to be seen." text="Share the basics and our team can follow up with a practical next step."/><section className="container contact-grid"><div><div className="contact-card"><span>WHATSAPP</span><h3>+94 77 000 0000</h3><p>Replace with your official business number.</p><a href="https://wa.me/94770000000">Message us <ArrowUpRight size={16}/></a></div><div className="contact-card"><span>EMAIL</span><h3>hello@kandyads.lk</h3><p>Replace with your official inbox.</p><a href="mailto:hello@kandyads.lk">Send an email <ArrowUpRight size={16}/></a></div><div className="contact-card"><span>LOCATION</span><h3>Kandy, Sri Lanka</h3><p>Service coverage can be expanded across Sri Lanka.</p></div></div><form className="quote-form" onSubmit={e=>e.preventDefault()}><label>Full name<input placeholder="Your name"/></label><label>Company<input placeholder="Company name"/></label><label>Phone / WhatsApp<input placeholder="07X XXX XXXX"/></label><label>Email<input type="email" placeholder="you@company.com"/></label><label>Service<select><option>Select a service</option>{services.map(s=><option key={s.slug}>{s.title}</option>)}</select></label><label>Project details<textarea rows="5" placeholder="Tell us about the location, size, quantity and deadline..."/></label><button className="btn primary" type="submit">Send enquiry <ArrowUpRight/></button></form></section></Page>}
function Page({children}){return <div>{children}</div>}
function SectionHero({kicker,title,text}){return <section className="section-hero container"><div className="eyebrow"><span></span>{kicker}</div><h1>{title}</h1><p>{text}</p></section>}
function ImageFeature({image,title,text}){return <section className="image-feature container"><div><img src={ASSET+image}/></div><div><div className="eyebrow"><span></span> WHAT WE BUILD</div><h2>{title}</h2><p>{text}</p><Link to="/projects" className="text-link">See the portfolio <ArrowUpRight size={17}/></Link></div></section>}
function Footer(){return <footer><div className="container footer-grid"><div><Link to="/" className="brand footer-brand"><span className="brand-mark">K</span><span>KANDY<span>ADS</span></span></Link><p>Creative advertising, signage and brand visibility solutions from Kandy, Sri Lanka.</p></div><div><b>Explore</b><Link to="/services">Services</Link><Link to="/projects">Projects</Link><Link to="/about">About</Link><Link to="/process">Process</Link></div><div><b>Start</b><Link to="/contact">Get a Quote</Link><a href="tel:+94770000000">Call</a><a href="https://wa.me/94770000000">WhatsApp</a></div><div><b>Website</b><span>www.kandyads.lk</span><span>Kandy, Sri Lanka</span></div></div><div className="container foot-bottom"><span>© {new Date().getFullYear()} Kandy Ads. Demo website concept.</span><span>Built as a React + Framer Motion prototype.</span></div></footer>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
