import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Clock3, Package, Users, Truck, Wallet, CheckSquare, Plus, RefreshCw } from 'lucide-react';
import { api } from '../../../api';
import Modal from '../../../components/common/Modal';
import './job-detail.css';

const money=v=>`LKR ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=v=>v?new Date(v).toLocaleDateString():'—';
const statuses=['DRAFT','READY','IN_PROGRESS','BLOCKED','REVIEW','COMPLETED','CANCELLED'];
function Metric({label,value}){return <div className="job-metric"><span>{label}</span><strong>{value}</strong></div>}
function Section({title,icon:Icon,action,children}){return <section className="job-section"><div className="job-section-head"><h2>{title}</h2><div className="job-section-actions">{action}{Icon&&<Icon size={17}/>}</div></div>{children}</section>}
function Field({label,children}){return <label className="form-field"><span>{label}</span>{children}</label>}

export default function JobDetailPage(){
 const {id}=useParams();
 const [state,setState]=React.useState({loading:true,error:'',data:null});
 const [lookups,setLookups]=React.useState({employees:[],vendors:[],materials:[]});
 const [modal,setModal]=React.useState(null);
 const [saving,setSaving]=React.useState(false);
 const [form,setForm]=React.useState({title:'',employeeId:'',vendorId:'',estimatedHours:'',agreedCost:'',materialId:'',requiredQty:'',taskDescription:'',taskEmployeeId:'',taskPriority:'MEDIUM',taskDueDate:''});
 const load=React.useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const r=await api.getJob(id);const profit=await api.getJobProfitability(id);setState({loading:false,error:'',data:{...r.data,profitability:profit.data}})}catch(e){setState({loading:false,error:e.message||'Unable to load job',data:null})}},[id]);
 React.useEffect(()=>{load()},[load]);
 React.useEffect(()=>{let active=true;Promise.all([api.listEmployees({pageSize:100}),api.listVendors({pageSize:100}),api.listMaterials({})]).then(([e,v,m])=>{if(active)setLookups({employees:e.data||[],vendors:v.data||[],materials:m.data||[]})}).catch(()=>{});return()=>{active=false}},[]);
 async function statusChange(status){setSaving(true);try{await api.updateJobStatus(id,{status});await load()}catch(e){setState(s=>({...s,error:e.message||'Unable to update status'}))}finally{setSaving(false)}}
 async function submitTask(){setSaving(true);try{await api.createTask({jobId:Number(id),title:form.title,description:form.taskDescription||undefined,employeeId:form.taskEmployeeId?Number(form.taskEmployeeId):undefined,priority:form.taskPriority,dueDate:form.taskDueDate||undefined});setModal(null);setForm(f=>({...f,title:'',taskDescription:'',taskEmployeeId:'',taskPriority:'MEDIUM',taskDueDate:''}));await load()}catch(e){setState(s=>({...s,error:e.message||'Unable to create task'}))}finally{setSaving(false)}}
 async function submitAssignment(){setSaving(true);try{await api.createJobAssignment(id,{employeeId:form.employeeId?Number(form.employeeId):null,vendorId:form.vendorId?Number(form.vendorId):null,estimatedHours:form.estimatedHours?Number(form.estimatedHours):null,agreedCost:form.agreedCost?Number(form.agreedCost):null});setModal(null);setForm(f=>({...f,employeeId:'',vendorId:'',estimatedHours:'',agreedCost:''}));await load()}catch(e){setState(s=>({...s,error:e.message||'Unable to create assignment'}))}finally{setSaving(false)}}
 async function submitMaterial(){setSaving(true);try{await api.createJobMaterialRequirement(id,{materialId:Number(form.materialId),requiredQty:Number(form.requiredQty)});setModal(null);setForm(f=>({...f,materialId:'',requiredQty:''}));await load()}catch(e){setState(s=>({...s,error:e.message||'Unable to add material requirement'}))}finally{setSaving(false)}}
 if(state.loading)return <div className="detail-state">Loading job…</div>; if(state.error&&!state.data)return <div className="detail-state error-state">{state.error}</div>;
 const j=state.data,p=j.profitability;
 return <div className="job-detail">
  {state.error&&<div className="form-error">{state.error}</div>}
  <Link className="back-link" to="/jobs"><ArrowLeft size={15}/> Back to Jobs</Link>
  <div className="job-hero"><div><p className="eyebrow">JOB / {j.number}</p><h1>{j.title}</h1><p>{j.project?.name||'—'} · {j.project?.client?.companyName||'—'}</p></div><div className="job-hero-actions"><select value={j.status} disabled={saving} onChange={e=>statusChange(e.target.value)} aria-label="Job status">{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="secondary" onClick={load}><RefreshCw size={15}/> Refresh</button></div></div>
  <div className="job-metrics"><Metric label="Revenue" value={money(j.revenue)}/><Metric label="Estimated cost" value={money(Number(j.estimatedMaterial)+Number(j.estimatedLabour)+Number(j.estimatedOutsource)+Number(j.estimatedExpense))}/><Metric label="Actual cost" value={money(p?.actual?.total)}/><Metric label="Margin" value={p?.marginPercent==null?'—':`${Number(p.marginPercent).toFixed(1)}%`}/></div>
  <div className="detail-grid-2">
   <Section title="Tasks" icon={CheckSquare} action={<button className="section-add" onClick={()=>setModal('task')}><Plus size={14}/> Add</button>}>{j.tasks?.length?j.tasks.map(t=><div className="related-row" key={t.id}><div><strong>{t.title}</strong><small>{t.employee?.name||'Unassigned'} · {t.status}{t.dueDate?` · due ${date(t.dueDate)}`:''}</small></div><span>{t.estimatedHours||0}h planned</span></div>):<div className="empty-note">No tasks yet.</div>}</Section>
   <Section title="Assignments" icon={Users} action={<button className="section-add" onClick={()=>setModal('assignment')}><Plus size={14}/> Add</button>}>{j.assignments?.length?j.assignments.map(a=><div className="related-row" key={a.id}><div><strong>{a.employee?.name||a.vendor?.companyName||'Unassigned'}</strong><small>{a.employee?'Internal':'External'}{a.agreedCost?` · ${money(a.agreedCost)}`:''}</small></div><span>{a.estimatedHours||0}h</span></div>):<div className="empty-note">No assignments yet.</div>}</Section>
   <Section title="Material requirements" icon={Package} action={<button className="section-add" onClick={()=>setModal('material')}><Plus size={14}/> Add</button>}>{j.materialRequirements?.length?j.materialRequirements.map(m=><div className="related-row" key={m.id}><div><strong>{m.material?.name||'Material'}</strong><small>{m.material?.sku||''}</small></div><span>{m.requiredQty} required</span></div>):<div className="empty-note">No material requirements yet.</div>}</Section>
   <Section title="Outsourcing" icon={Truck}>{j.outsourceOrders?.length?j.outsourceOrders.map(o=><div className="related-row" key={o.id}><div><strong>{o.number}</strong><small>{o.vendor?.companyName||'Vendor'} · {o.status}</small></div><span>{money(o.agreedCost)}</span></div>):<div className="empty-note">No outsourcing orders.</div>}</Section>
   <Section title="Time & labour" icon={Clock3}><div className="summary-lines"><span>Hours recorded <b>{p?.hours||0}h</b></span><span>Labour cost <b>{money(p?.actual?.labour)}</b></span></div></Section>
   <Section title="Direct expenses" icon={Wallet}>{j.expenses?.length?j.expenses.map(e=><div className="related-row" key={e.id}><div><strong>{e.number}</strong><small>{e.category?.name||'Expense'} · {e.status}</small></div><span>{money(e.amount)}</span></div>):<div className="empty-note">No job expenses.</div>}</Section>
  </div>
  <div className="cost-card"><div><p className="eyebrow">ACTUAL COST</p><h2>{money(p?.actual?.total)}</h2></div><div><span>Material {money(p?.actual?.material)}</span><span>Labour {money(p?.actual?.labour)}</span><span>Outsource {money(p?.actual?.outsource)}</span><span>Expenses {money(p?.actual?.expense)}</span></div></div>

  <Modal open={modal==='task'} title="Add task" description="Create a production task inside this job." onClose={()=>setModal(null)} width="680px"><div className="form-grid form-grid-2"><Field label="Task title"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Assign employee"><select value={form.taskEmployeeId} onChange={e=>setForm({...form,taskEmployeeId:e.target.value})}><option value="">Unassigned</option>{lookups.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="Priority"><select value={form.taskPriority} onChange={e=>setForm({...form,taskPriority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></Field><Field label="Due date"><input type="date" value={form.taskDueDate} onChange={e=>setForm({...form,taskDueDate:e.target.value})}/></Field><Field label="Description"><textarea rows="4" value={form.taskDescription} onChange={e=>setForm({...form,taskDescription:e.target.value})}/></Field></div><div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>Cancel</button><button className="primary" disabled={saving||!form.title.trim()} onClick={submitTask}>Create task</button></div></Modal>
  <Modal open={modal==='assignment'} title="Add assignment" description="Assign internal staff or an external vendor to this job." onClose={()=>setModal(null)} width="680px"><div className="form-grid form-grid-2"><Field label="Employee"><select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value,vendorId:''})}><option value="">Not internal</option>{lookups.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="Vendor"><select value={form.vendorId} onChange={e=>setForm({...form,vendorId:e.target.value,employeeId:''})}><option value="">Not outsourced</option>{lookups.vendors.map(v=><option key={v.id} value={v.id}>{v.companyName}</option>)}</select></Field><Field label="Estimated hours"><input type="number" min="0" step="0.25" value={form.estimatedHours} onChange={e=>setForm({...form,estimatedHours:e.target.value})}/></Field><Field label="Agreed cost (LKR)"><input type="number" min="0" step="0.01" value={form.agreedCost} onChange={e=>setForm({...form,agreedCost:e.target.value})}/></Field></div><div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>Cancel</button><button className="primary" disabled={saving||(!form.employeeId&&!form.vendorId)} onClick={submitAssignment}>Add assignment</button></div></Modal>
  <Modal open={modal==='material'} title="Add material requirement" description="Reserve a material requirement for this job." onClose={()=>setModal(null)} width="560px"><div className="form-grid"><Field label="Material"><select value={form.materialId} onChange={e=>setForm({...form,materialId:e.target.value})}><option value="">Select material</option>{lookups.materials.map(m=><option key={m.id} value={m.id}>{m.sku} · {m.name}</option>)}</select></Field><Field label="Required quantity"><input type="number" min="0.001" step="0.001" value={form.requiredQty} onChange={e=>setForm({...form,requiredQty:e.target.value})}/></Field></div><div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>Cancel</button><button className="primary" disabled={saving||!form.materialId||!form.requiredQty} onClick={submitMaterial}>Add requirement</button></div></Modal>
 </div>;
}
