import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { canTransition, taskTransitions } from '../workflow/workflow.rules.js';

const taskStatuses = ['PENDING','READY','IN_PROGRESS','BLOCKED','REVIEW','COMPLETED','CANCELLED'] as const;
const createSchema=z.object({jobId:z.coerce.number().int().positive(),title:z.string().min(2).max(200),description:z.string().max(5000).optional(),employeeId:z.coerce.number().int().positive().optional(),priority:z.string().max(30).optional(),startDate:z.coerce.date().optional(),dueDate:z.coerce.date().optional(),estimatedHours:z.coerce.number().nonnegative().optional(),status:z.enum(taskStatuses).optional()});
const updateSchema=createSchema.partial().omit({jobId:true});
const statusSchema=z.object({status:z.enum(taskStatuses)});

export async function tasksRoutes(app:FastifyInstance){
  app.get('/api/v1/tasks',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),jobId:z.coerce.number().int().positive().optional(),employeeId:z.coerce.number().int().positive().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const where={job:{project:{is:{}}},...(q.status?{status:q.status as any}:{}),...(q.jobId?{jobId:q.jobId}:{}),...(q.employeeId?{employeeId:q.employeeId}:{}),...(q.search?{title:{contains:q.search}}:{})};const [items,total]=await Promise.all([prisma.task.findMany({where,include:{job:true,employee:true},orderBy:{dueDate:'asc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.task.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.post('/api/v1/tasks',async(request,reply)=>{const input=createSchema.parse(request.body);const job=await prisma.job.findFirst({where:{id:input.jobId,project:{is:{}}}});if(!job)return reply.badRequest('Job not found');if(input.employeeId){const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');}const item=await prisma.task.create({data:input,include:{job:true,employee:true}});return reply.code(201).send({data:item});});
  app.get('/api/v1/tasks/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const item=await prisma.task.findFirst({where:{id,job:{project:{is:{}}}},include:{job:{include:{project:true}},employee:true,timeEntries:true}});if(!item)return reply.notFound('Task not found');return {data:item};});
  app.patch('/api/v1/tasks/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=updateSchema.parse(request.body);const existing=await prisma.task.findFirst({where:{id,job:{project:{is:{}}}}});if(!existing)return reply.notFound('Task not found');if(input.employeeId){const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');}if(input.status&& !canTransition(taskTransitions,existing.status,input.status))return reply.badRequest(`Invalid task transition: ${existing.status} -> ${input.status}`);if(existing.status==='COMPLETED'&&input.status&&input.status!=='COMPLETED')return reply.badRequest('Completed tasks cannot be reopened');const completedAt=input.status==='COMPLETED'?new Date():existing.completedAt;const item=await prisma.task.update({where:{id},data:{...input,completedAt},include:{job:true,employee:true}});return {data:item};});
  app.patch('/api/v1/tasks/:id/status',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=statusSchema.parse(request.body);const existing=await prisma.task.findFirst({where:{id,job:{project:{is:{}}}}});if(!existing)return reply.notFound('Task not found');if(!canTransition(taskTransitions,existing.status,input.status))return reply.badRequest(`Invalid task transition: ${existing.status} -> ${input.status}`);const completedAt=input.status==='COMPLETED'?new Date():existing.completedAt;const item=await prisma.task.update({where:{id},data:{status:input.status,completedAt},include:{job:true,employee:true}});return {data:item};});
}
