import { Prisma } from '@prisma/client';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { canTransition, taskTransitions } from '../workflow/workflow.rules.js';

const taskStatuses = ['PENDING','READY','IN_PROGRESS','BLOCKED','REVIEW','COMPLETED','CANCELLED'] as const;
const createSchema=z.object({jobId:z.coerce.number().int().positive(),title:z.string().trim().min(2).max(200),description:z.string().max(5000).optional(),notes:z.string().max(10000).optional().nullable(),employeeId:z.coerce.number().int().positive().optional().nullable(),parentTaskId:z.coerce.number().int().positive().optional().nullable(),priority:z.string().max(30).optional().nullable(),startDate:z.coerce.date().optional().nullable(),dueDate:z.coerce.date().optional().nullable(),estimatedHours:z.coerce.number().nonnegative().optional().nullable(),status:z.enum(taskStatuses).optional()});
const updateSchema=createSchema.partial().omit({jobId:true});
const statusSchema=z.object({status:z.enum(taskStatuses)});
const dependencySchema=z.object({dependsOnTaskId:z.coerce.number().int().positive()});
const checklistCreateSchema=z.object({title:z.string().trim().min(1).max(255),required:z.coerce.boolean().optional().default(true),sortOrder:z.coerce.number().int().min(0).max(100000).optional().default(0)});
const checklistUpdateSchema=z.object({title:z.string().trim().min(1).max(255).optional(),required:z.coerce.boolean().optional(),completed:z.coerce.boolean().optional(),sortOrder:z.coerce.number().int().min(0).max(100000).optional()}).refine(v=>Object.keys(v).length>0,{message:'At least one field is required'});
function actorId(request:FastifyRequest){const id=Number((request.user as {sub?:string}).sub);return Number.isInteger(id)&&id>0?id:null;}
async function audit(request:FastifyRequest,action:string,entityId:number,after:unknown,before?:unknown){await prisma.auditLog.create({data:{userId:actorId(request),action,entity:'Task',entityId:String(entityId),beforeJson:before===null?Prisma.DbNull:before as any,afterJson:after as any}});}
async function taskForId(id:number){return prisma.task.findFirst({where:{id,job:{project:{is:{}}}}});}
async function sameJobTask(id:number,jobId:number){return prisma.task.findFirst({where:{id,jobId}});}
async function parentId(taskId:number){const rows=await prisma.$queryRaw<Array<{parentTaskId:number|null}>>(Prisma.sql`SELECT parentTaskId FROM Task WHERE id=${taskId}`);return rows[0]?.parentTaskId??null;}
async function taskNotes(taskId:number){const rows=await prisma.$queryRaw<Array<{notes:string|null}>>(Prisma.sql`SELECT notes FROM Task WHERE id=${taskId}`);return rows[0]?.notes??null;}
async function taskAttachments(taskId:number){return prisma.attachment.findMany({where:{entityType:'TASK',entityId:taskId},select:{id:true,name:true,description:true,mimeType:true,sizeBytes:true,storageKey:true,url:true,uploadedBy:{select:{id:true,name:true,email:true}},createdAt:true},orderBy:{createdAt:'desc'}});}
async function subtasks(taskId:number){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,title,status,completedAt,employeeId FROM Task WHERE parentTaskId=${taskId} ORDER BY createdAt ASC`);}
async function dependencies(taskId:number){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT d.id,d.dependsOnTaskId,t.title,t.status FROM TaskDependency d JOIN Task t ON t.id=d.dependsOnTaskId WHERE d.taskId=${taskId} ORDER BY d.createdAt ASC`);}
async function dependents(taskId:number){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT d.id,d.taskId,t.title,t.status FROM TaskDependency d JOIN Task t ON t.id=d.taskId WHERE d.dependsOnTaskId=${taskId} ORDER BY d.createdAt ASC`);}
async function checklist(taskId:number){const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,title,required,completed,completedAt,sortOrder,createdAt,updatedAt FROM TaskChecklistItem WHERE taskId=${taskId} ORDER BY sortOrder ASC,id ASC`);return rows.map(item=>({...item,required:Boolean(item.required),completed:Boolean(item.completed)}));}
async function structure(taskId:number){const [parent,children,deps,dependentRows,items]=await Promise.all([parentId(taskId),subtasks(taskId),dependencies(taskId),dependents(taskId),checklist(taskId)]);const parentTask=parent?await prisma.task.findUnique({where:{id:parent},select:{id:true,title:true,status:true}}):null;return {parentTask,subtasks:children,dependencies:deps.map(d=>({id:Number(d.id),taskId:taskId,dependsOnTaskId:Number(d.dependsOnTaskId),dependsOnTask:{id:Number(d.dependsOnTaskId),title:d.title,status:d.status}})),dependents:dependentRows.map(d=>({id:Number(d.id),taskId:Number(d.taskId),dependsOnTaskId:taskId,task:{id:Number(d.taskId),title:d.title,status:d.status}})),checklistItems:items,_count:{subtasks:children.length,dependencies:deps.length}};}
async function enrichTask(item:any){const [notes,attachments,details]=await Promise.all([taskNotes(item.id),taskAttachments(item.id),structure(item.id)]);return {...item,notes,attachments,...details};}
async function dependencyPath(fromId:number,targetId:number){const visited=new Set<number>();let frontier=[fromId];while(frontier.length){const rows=await prisma.$queryRaw<Array<{dependsOnTaskId:number}>>(Prisma.sql`SELECT dependsOnTaskId FROM TaskDependency WHERE taskId IN (${Prisma.join(frontier)})`);frontier=[];for(const row of rows){const next=Number(row.dependsOnTaskId);if(next===targetId)return true;if(!visited.has(next)){visited.add(next);frontier.push(next);}}}return false;}
async function completionBlockers(taskId:number){const [deps,items]=await Promise.all([dependencies(taskId),prisma.$queryRaw<any[]>(Prisma.sql`SELECT id,title FROM TaskChecklistItem WHERE taskId=${taskId} AND required=true AND completed=false ORDER BY sortOrder ASC,id ASC`)]);return {dependencies:deps.filter(d=>!['COMPLETED','CANCELLED'].includes(d.status)),checklist:items};}
async function setParentTask(taskId:number,parentTaskId:number|null){await prisma.$executeRaw(Prisma.sql`UPDATE Task SET parentTaskId=${parentTaskId} WHERE id=${taskId}`);}
async function setTaskNotes(taskId:number,notes:string|null){await prisma.$executeRaw(Prisma.sql`UPDATE Task SET notes=${notes} WHERE id=${taskId}`);}

export async function tasksRoutes(app:FastifyInstance){
  app.get('/api/v1/tasks',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),jobId:z.coerce.number().int().positive().optional(),employeeId:z.coerce.number().int().positive().optional(),parentTaskId:z.coerce.number().int().positive().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);let ids:number[]|undefined;if(q.parentTaskId){const rows=await prisma.$queryRaw<Array<{id:number}>>(Prisma.sql`SELECT id FROM Task WHERE parentTaskId=${q.parentTaskId}`);ids=rows.map(r=>Number(r.id));if(!ids.length)return {data:[],meta:{page:q.page,pageSize:q.pageSize,total:0}};}const where={job:{project:{is:{}}},...(ids?{id:{in:ids}}:{}),...(q.status?{status:q.status as any}:{}),...(q.jobId?{jobId:q.jobId}:{}),...(q.employeeId?{employeeId:q.employeeId}:{}),...(q.search?{title:{contains:q.search}}:{})};const [items,total]=await Promise.all([prisma.task.findMany({where,include:{job:true,employee:true},orderBy:{dueDate:'asc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.task.count({where})]);const data=await Promise.all(items.map(enrichTask));return {data,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.post('/api/v1/tasks',async(request,reply)=>{const input=createSchema.parse(request.body);const job=await prisma.job.findFirst({where:{id:input.jobId,project:{is:{}}}});if(!job)return reply.badRequest('Job not found');if(input.employeeId){const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');}if(input.parentTaskId){const parent=await sameJobTask(input.parentTaskId,input.jobId);if(!parent)return reply.badRequest('Parent task not found in the same job');}const {parentTaskId,notes,...core}=input;const item=await prisma.task.create({data:core,include:{job:true,employee:true}});if(parentTaskId!==undefined)await setParentTask(item.id,parentTaskId);if(notes!==undefined)await setTaskNotes(item.id,notes??null);await audit(request,'TASK_CREATED',item.id,{taskId:item.id,title:item.title,parentTaskId:parentTaskId??null,notes:notes??null});return reply.code(201).send({data:await enrichTask(item)});});
  app.get('/api/v1/tasks/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const item=await prisma.task.findFirst({where:{id,job:{project:{is:{}}}},include:{job:{include:{project:true}},employee:true,timeEntries:true}});if(!item)return reply.notFound('Task not found');return {data:await enrichTask(item)};});
  app.patch('/api/v1/tasks/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=updateSchema.parse(request.body);const existing=await taskForId(id);if(!existing)return reply.notFound('Task not found');if(input.employeeId){const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');}if(input.parentTaskId!==undefined){if(input.parentTaskId===id)return reply.badRequest('A task cannot be its own parent');if(input.parentTaskId!==null){const parent=await sameJobTask(input.parentTaskId,existing.jobId);if(!parent)return reply.badRequest('Parent task not found in the same job');}}if(existing.status==='COMPLETED'&&input.status&&input.status!=='COMPLETED')return reply.badRequest('Completed tasks cannot be reopened');if(input.status&&!canTransition(taskTransitions,existing.status,input.status))return reply.badRequest(`Invalid task transition: ${existing.status} -> ${input.status}`);if(input.status==='COMPLETED'){const blockers=await completionBlockers(id);if(blockers.dependencies.length||blockers.checklist.length)return reply.badRequest('Task cannot be completed while dependencies or required checklist items are open');}const {parentTaskId,notes,...core}=input;const item=await prisma.task.update({where:{id},data:{...core,completedAt:input.status==='COMPLETED'?new Date():existing.completedAt},include:{job:true,employee:true}});if(parentTaskId!==undefined)await setParentTask(id,parentTaskId);if(notes!==undefined)await setTaskNotes(id,notes??null);await audit(request,'TASK_UPDATED',id,input,existing);return {data:await enrichTask(item)};});
  app.patch('/api/v1/tasks/:id/status',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=statusSchema.parse(request.body);const existing=await taskForId(id);if(!existing)return reply.notFound('Task not found');if(!canTransition(taskTransitions,existing.status,input.status))return reply.badRequest(`Invalid task transition: ${existing.status} -> ${input.status}`);if(input.status==='COMPLETED'){const blockers=await completionBlockers(id);if(blockers.dependencies.length||blockers.checklist.length)return reply.badRequest('Task cannot be completed while dependencies or required checklist items are open');}const item=await prisma.$transaction(async tx=>{const updated=await tx.task.update({where:{id},data:{status:input.status,completedAt:input.status==='COMPLETED'?new Date():existing.completedAt},include:{job:true,employee:true}});await tx.auditLog.create({data:{userId:actorId(request),action:'TASK_STATUS_CHANGED',entity:'Task',entityId:String(id),beforeJson:{status:existing.status},afterJson:{status:updated.status,completedAt:updated.completedAt}}});return updated;});return {data:await enrichTask(item)};});
  app.post('/api/v1/tasks/:id/dependencies',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const input=dependencySchema.parse(request.body);const task=await taskForId(taskId);if(!task)return reply.notFound('Task not found');if(input.dependsOnTaskId===taskId)return reply.badRequest('A task cannot depend on itself');const dependency=await sameJobTask(input.dependsOnTaskId,task.jobId);if(!dependency)return reply.badRequest('Dependency task not found in the same job');if(await dependencyPath(input.dependsOnTaskId,taskId))return reply.badRequest('Dependency would create a cycle');const duplicate=await prisma.$queryRaw<Array<{id:number}>>(Prisma.sql`SELECT id FROM TaskDependency WHERE taskId=${taskId} AND dependsOnTaskId=${input.dependsOnTaskId} LIMIT 1`);if(duplicate.length)return reply.badRequest('Dependency already exists');await prisma.$executeRaw(Prisma.sql`INSERT INTO TaskDependency (taskId,dependsOnTaskId) VALUES (${taskId},${input.dependsOnTaskId})`);const rows=await dependencies(taskId);const item=rows.find(d=>Number(d.dependsOnTaskId)===input.dependsOnTaskId);await audit(request,'TASK_DEPENDENCY_ADDED',taskId,{dependsOnTaskId:input.dependsOnTaskId});return reply.code(201).send({data:item});});
  app.delete('/api/v1/tasks/:id/dependencies/:dependencyId',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const dependencyId=z.coerce.number().int().positive().parse((request.params as any).dependencyId);if(!await taskForId(taskId))return reply.notFound('Task not found');const result=await prisma.$executeRaw(Prisma.sql`DELETE FROM TaskDependency WHERE id=${dependencyId} AND taskId=${taskId}`);if(!result)return reply.notFound('Dependency not found');await audit(request,'TASK_DEPENDENCY_REMOVED',taskId,{dependencyId});return {data:{deleted:true}};});
  app.post('/api/v1/tasks/:id/checklist',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const input=checklistCreateSchema.parse(request.body);if(!await taskForId(taskId))return reply.notFound('Task not found');await prisma.$executeRaw(Prisma.sql`INSERT INTO TaskChecklistItem (taskId,title,required,completed,sortOrder,updatedAt) VALUES (${taskId},${input.title},${input.required},false,${input.sortOrder},CURRENT_TIMESTAMP(3))`);const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM TaskChecklistItem WHERE taskId=${taskId} ORDER BY id DESC LIMIT 1`);const item=rows[0];const data={...item,required:Boolean(item.required),completed:Boolean(item.completed)};await audit(request,'TASK_CHECKLIST_ADDED',taskId,{checklistId:item.id,title:item.title});return reply.code(201).send({data});});
  app.patch('/api/v1/tasks/:id/checklist/:itemId',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const itemId=z.coerce.number().int().positive().parse((request.params as any).itemId);const input=checklistUpdateSchema.parse(request.body);if(!await taskForId(taskId))return reply.notFound('Task not found');const existingRows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM TaskChecklistItem WHERE id=${itemId} AND taskId=${taskId}`);if(!existingRows.length)return reply.notFound('Checklist item not found');const existing=existingRows[0];const completedAt=input.completed===true?new Date():input.completed===false?null:existing.completedAt;await prisma.$executeRaw(Prisma.sql`UPDATE TaskChecklistItem SET title=COALESCE(${input.title??null},title),required=COALESCE(${input.required??null},required),completed=COALESCE(${input.completed??null},completed),completedAt=${completedAt},sortOrder=COALESCE(${input.sortOrder??null},sortOrder),updatedAt=CURRENT_TIMESTAMP(3) WHERE id=${itemId} AND taskId=${taskId}`);const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM TaskChecklistItem WHERE id=${itemId}`);const data={...rows[0],required:Boolean(rows[0].required),completed:Boolean(rows[0].completed)};await audit(request,'TASK_CHECKLIST_UPDATED',taskId,input,existing);return {data};});
  app.delete('/api/v1/tasks/:id/checklist/:itemId',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const itemId=z.coerce.number().int().positive().parse((request.params as any).itemId);if(!await taskForId(taskId))return reply.notFound('Task not found');const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM TaskChecklistItem WHERE id=${itemId} AND taskId=${taskId}`);if(!rows.length)return reply.notFound('Checklist item not found');await prisma.$executeRaw(Prisma.sql`DELETE FROM TaskChecklistItem WHERE id=${itemId} AND taskId=${taskId}`);await audit(request,'TASK_CHECKLIST_REMOVED',taskId,{checklistId:itemId,title:rows[0].title});return {data:{deleted:true}};});
}
