import { Prisma } from '@prisma/client';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { canTransition, taskTransitions } from '../workflow/workflow.rules.js';

const taskStatuses = ['PENDING','READY','IN_PROGRESS','BLOCKED','REVIEW','COMPLETED','CANCELLED'] as const;
const createSchema=z.object({jobId:z.coerce.number().int().positive(),title:z.string().trim().min(2).max(200),description:z.string().max(5000).optional(),employeeId:z.coerce.number().int().positive().optional().nullable(),parentTaskId:z.coerce.number().int().positive().optional().nullable(),priority:z.string().max(30).optional().nullable(),startDate:z.coerce.date().optional().nullable(),dueDate:z.coerce.date().optional().nullable(),estimatedHours:z.coerce.number().nonnegative().optional().nullable(),status:z.enum(taskStatuses).optional()});
const updateSchema=createSchema.partial().omit({jobId:true});
const statusSchema=z.object({status:z.enum(taskStatuses)});
const dependencySchema=z.object({dependsOnTaskId:z.coerce.number().int().positive()});
const checklistCreateSchema=z.object({title:z.string().trim().min(1).max(255),required:z.coerce.boolean().optional().default(true),sortOrder:z.coerce.number().int().min(0).max(100000).optional().default(0)});
const checklistUpdateSchema=z.object({title:z.string().trim().min(1).max(255).optional(),required:z.coerce.boolean().optional(),completed:z.coerce.boolean().optional(),sortOrder:z.coerce.number().int().min(0).max(100000).optional()}).refine(v=>Object.keys(v).length>0,{message:'At least one field is required'});

function actorId(request:FastifyRequest){const id=Number((request.user as {sub?:string}).sub);return Number.isInteger(id)&&id>0?id:null;}
async function audit(request:FastifyRequest,action:string,entityId:number,after:unknown,before?:unknown){await prisma.auditLog.create({data:{userId:actorId(request),action,entity:'Task',entityId:String(entityId),beforeJson:before===null?Prisma.DbNull:before as any,afterJson:after as any}});}

async function taskForId(id:number){return prisma.task.findFirst({where:{id,job:{project:{is:{}}}}});}
async function sameJobTask(id:number,jobId:number){return prisma.task.findFirst({where:{id,jobId}});}
async function hasDependencyPath(fromId:number,targetId:number){
  const visited=new Set<number>();
  let frontier=[fromId];
  while(frontier.length){
    const next=await prisma.taskDependency.findMany({where:{taskId:{in:frontier}},select:{dependsOnTaskId:true}});
    frontier=[];
    for(const row of next){if(row.dependsOnTaskId===targetId)return true;if(!visited.has(row.dependsOnTaskId)){visited.add(row.dependsOnTaskId);frontier.push(row.dependsOnTaskId);}}
  }
  return false;
}
async function completionBlockers(taskId:number){
  const [dependencies,checklist]=await Promise.all([
    prisma.taskDependency.findMany({where:{taskId},include:{dependsOnTask:{select:{id:true,title:true,status:true}}}}),
    prisma.taskChecklistItem.findMany({where:{taskId,required:true,completed:false},orderBy:{sortOrder:'asc'}}),
  ]);
  return {dependencies:dependencies.filter(d=>!['COMPLETED','CANCELLED'].includes(d.dependsOnTask.status)),checklist};
}

export async function tasksRoutes(app:FastifyInstance){
  app.get('/api/v1/tasks',async request=>{const q=z.object({search:z.string().optional(),status:z.string().optional(),jobId:z.coerce.number().int().positive().optional(),employeeId:z.coerce.number().int().positive().optional(),parentTaskId:z.coerce.number().int().positive().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const where={job:{project:{is:{}}},...(q.status?{status:q.status as any}:{}),...(q.jobId?{jobId:q.jobId}:{}),...(q.employeeId?{employeeId:q.employeeId}:{}),...(q.parentTaskId?{parentTaskId:q.parentTaskId}:{}),...(q.search?{title:{contains:q.search}}:{})};const [items,total]=await Promise.all([prisma.task.findMany({where,include:{job:true,employee:true,parentTask:{select:{id:true,title:true}},subtasks:{select:{id:true,title:true,status:true,completedAt:true}},_count:{select:{subtasks:true,dependencies:true}}},orderBy:{dueDate:'asc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.task.count({where})]);return {data:items,meta:{page:q.page,pageSize:q.pageSize,total}};});
  app.post('/api/v1/tasks',async(request,reply)=>{const input=createSchema.parse(request.body);const job=await prisma.job.findFirst({where:{id:input.jobId,project:{is:{}}}});if(!job)return reply.badRequest('Job not found');if(input.employeeId){const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');}if(input.parentTaskId){const parent=await sameJobTask(input.parentTaskId,input.jobId);if(!parent)return reply.badRequest('Parent task not found in the same job');}const item=await prisma.task.create({data:input,include:{job:true,employee:true,parentTask:{select:{id:true,title:true}}});await audit(request,'TASK_CREATED',item.id,{taskId:item.id,title:item.title});return reply.code(201).send({data:item});});
  app.get('/api/v1/tasks/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const item=await prisma.task.findFirst({where:{id,job:{project:{is:{}}}},include:{job:{include:{project:true}},employee:true,timeEntries:true,parentTask:{select:{id:true,title:true,status:true}},subtasks:{include:{employee:true},orderBy:{createdAt:'asc'}},dependencies:{include:{dependsOnTask:{select:{id:true,title:true,status:true}}},orderBy:{createdAt:'asc'}},dependents:{include:{task:{select:{id:true,title:true,status:true}}},orderBy:{createdAt:'asc'}},checklistItems:{orderBy:[{sortOrder:'asc'},{id:'asc'}]}}});if(!item)return reply.notFound('Task not found');return {data:item};});
  app.patch('/api/v1/tasks/:id',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=updateSchema.parse(request.body);const existing=await taskForId(id);if(!existing)return reply.notFound('Task not found');if(input.employeeId){const employee=await prisma.employee.findUnique({where:{id:input.employeeId}});if(!employee)return reply.badRequest('Employee not found');}if(input.parentTaskId){if(input.parentTaskId===id)return reply.badRequest('A task cannot be its own parent');const parent=await sameJobTask(input.parentTaskId,existing.jobId);if(!parent)return reply.badRequest('Parent task not found in the same job');}if(existing.status==='COMPLETED'&&input.status&&input.status!=='COMPLETED')return reply.badRequest('Completed tasks cannot be reopened');if(input.status&&!canTransition(taskTransitions,existing.status,input.status))return reply.badRequest(`Invalid task transition: ${existing.status} -> ${input.status}`);if(input.status==='COMPLETED'){const blockers=await completionBlockers(id);if(blockers.dependencies.length||blockers.checklist.length)return reply.badRequest('Task cannot be completed while dependencies or required checklist items are open');}const completedAt=input.status==='COMPLETED'?new Date():existing.completedAt;const item=await prisma.task.update({where:{id},data:{...input,completedAt},include:{job:true,employee:true,parentTask:{select:{id:true,title:true}}});await audit(request,'TASK_UPDATED',id,input,existing);return {data:item};});
  app.patch('/api/v1/tasks/:id/status',async(request,reply)=>{const id=z.coerce.number().int().positive().parse((request.params as any).id);const input=statusSchema.parse(request.body);const existing=await taskForId(id);if(!existing)return reply.notFound('Task not found');if(!canTransition(taskTransitions,existing.status,input.status))return reply.badRequest(`Invalid task transition: ${existing.status} -> ${input.status}`);if(input.status==='COMPLETED'){const blockers=await completionBlockers(id);if(blockers.dependencies.length||blockers.checklist.length)return reply.badRequest('Task cannot be completed while dependencies or required checklist items are open');}const completedAt=input.status==='COMPLETED'?new Date():existing.completedAt;const item=await prisma.task.update({where:{id},data:{status:input.status,completedAt},include:{job:true,employee:true,parentTask:{select:{id:true,title:true}}}});await audit(request,'TASK_STATUS_CHANGED',id,{from:existing.status,to:input.status},existing.status);return {data:item};});

  app.post('/api/v1/tasks/:id/dependencies',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const input=dependencySchema.parse(request.body);const task=await taskForId(taskId);if(!task)return reply.notFound('Task not found');if(input.dependsOnTaskId===taskId)return reply.badRequest('A task cannot depend on itself');const dependency=await sameJobTask(input.dependsOnTaskId,task.jobId);if(!dependency)return reply.badRequest('Dependency task not found in the same job');if(await hasDependencyPath(input.dependsOnTaskId,taskId))return reply.badRequest('Dependency would create a cycle');const item=await prisma.taskDependency.create({data:{taskId,dependsOnTaskId:input.dependsOnTaskId},include:{dependsOnTask:{select:{id:true,title:true,status:true}}}}).catch(error=>{if((error as {code?:string}).code==='P2002')return null;throw error;});if(!item)return reply.badRequest('Dependency already exists');await audit(request,'TASK_DEPENDENCY_ADDED',taskId,{dependencyId:item.id,dependsOnTaskId:input.dependsOnTaskId});return reply.code(201).send({data:item});});
  app.delete('/api/v1/tasks/:id/dependencies/:dependencyId',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const dependencyId=z.coerce.number().int().positive().parse((request.params as any).dependencyId);const task=await taskForId(taskId);if(!task)return reply.notFound('Task not found');const dependency=await prisma.taskDependency.findFirst({where:{id:dependencyId,taskId}});if(!dependency)return reply.notFound('Dependency not found');await prisma.taskDependency.delete({where:{id:dependencyId}});await audit(request,'TASK_DEPENDENCY_REMOVED',taskId,{dependencyId,dependsOnTaskId:dependency.dependsOnTaskId});return {data:{deleted:true}};});

  app.post('/api/v1/tasks/:id/checklist',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const input=checklistCreateSchema.parse(request.body);const task=await taskForId(taskId);if(!task)return reply.notFound('Task not found');const item=await prisma.taskChecklistItem.create({data:{...input,taskId}});await audit(request,'TASK_CHECKLIST_ADDED',taskId,{checklistId:item.id,title:item.title});return reply.code(201).send({data:item});});
  app.patch('/api/v1/tasks/:id/checklist/:itemId',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const itemId=z.coerce.number().int().positive().parse((request.params as any).itemId);const input=checklistUpdateSchema.parse(request.body);const task=await taskForId(taskId);if(!task)return reply.notFound('Task not found');const existing=await prisma.taskChecklistItem.findFirst({where:{id:itemId,taskId}});if(!existing)return reply.notFound('Checklist item not found');const completedAt=input.completed===true?new Date():input.completed===false?null:existing.completedAt;const item=await prisma.taskChecklistItem.update({where:{id:itemId},data:{...input,completedAt}});await audit(request,'TASK_CHECKLIST_UPDATED',taskId,input,existing);return {data:item};});
  app.delete('/api/v1/tasks/:id/checklist/:itemId',async(request,reply)=>{const taskId=z.coerce.number().int().positive().parse((request.params as any).id);const itemId=z.coerce.number().int().positive().parse((request.params as any).itemId);const task=await taskForId(taskId);if(!task)return reply.notFound('Task not found');const existing=await prisma.taskChecklistItem.findFirst({where:{id:itemId,taskId}});if(!existing)return reply.notFound('Checklist item not found');await prisma.taskChecklistItem.delete({where:{id:itemId}});await audit(request,'TASK_CHECKLIST_REMOVED',taskId,{checklistId:itemId,title:existing.title});return {data:{deleted:true}};});
}
